scram::gui::Validator Class Reference
scram::gui::Validator Class Reference
Provider of common validators.
#include <validator.h>
Static Public Member Functions
static const QValidator * name ()
static const QValidator * percent ()
static const QValidator * probability ()
static const QValidator * nonNegative ()
Detailed Description
Provider of common validators.
Definition at line 28 of file validator.h.
Member Function Documentation
const QValidator * scram::gui::Validator::name () static
Returns
The validator suitable for MEF element names.
Definition at line 31 of file validator.cpp.
Referenced by scram::gui::EventDialog::EventDialog(), and scram::gui::NameDialog::NameDialog().
const QValidator * scram::gui::Validator::percent () static
Returns
The validator for integer percent with '' optional.
Definition at line 39 of file validator.cpp.
Referenced by scram::gui::MainWindow::MainWindow().
const QValidator * scram::gui::Validator::probability () static
Returns
The floating point probability value validator.
Definition at line 46 of file validator.cpp.
Referenced by scram::gui::EventDialog::EventDialog().
const QValidator * scram::gui::Validator::nonNegative () static
Returns
The validator for non-negative floating-point numbers.
Definition at line 52 of file validator.cpp.
Referenced by scram::gui::EventDialog::EventDialog().
The documentation for this class was generated from the following files:
validator.h
validator.cpp