scram::gui::ZoomableView Class Reference
scram::gui::ZoomableView Class Reference
The base class for graphics views with default zoom logic.
#include <zoomableview.h>
Public Slots
void setZoom (int level)
Accepts requests to change the zoom to the given level.
void zoomIn (int deltaLevel)
Incrementally zooms in by the absolute increment in the level.
void zoomOut (int deltaLevel)
Incrementally zooms out by the absolute decrement in the level.
void zoomBestFit ()
Automatically adjusts the zoom to fit the view into the current scene.
Signals
void zoomChanged (int level)
Public Member Functions
int getZoom () const
Protected Member Functions
void wheelEvent (QWheelEvent *event) override
Provides support for zoom-in/out with a mouse while holding Control key.
Detailed Description
The base class for graphics views with default zoom logic.
The zoom level is given as percents.
Definition at line 30 of file zoomableview.h.
Member Function Documentation
int scram::gui::ZoomableView::getZoom () const inline
Returns
The zoom value in percentages.
Definition at line 38 of file zoomableview.h.
References setZoom(), and zoomChanged().
void scram::gui::ZoomableView::zoomChanged (int level) signal
Parameters
[in] level The current zoom level.
Referenced by scram::gui::MainWindow::addInputFiles(), getZoom(), and setZoom().
The documentation for this class was generated from the following files:
zoomableview.h
zoomableview.cpp