scram::gui::model::BasicEvent Class Reference
scram::gui::model::BasicEvent Class Reference
The proxy to manage mef::BasicEvent.
#include <model.h>
Classes
class SetExpression
Sets the basic event expression.
class SetFlavor
Sets the flavor of the basic event.
Public Types
enum Flavor { Basic = 0, Undeveloped }
Basic event flavors.
Public Types inherited from scram::gui::model::Proxy< BasicEvent, mef::BasicEvent >
using Origin = mef::BasicEvent
The MEF type.
Signals
void expressionChanged (mef::Expression *expression)
void flavorChanged (Flavor flavor)
Signals inherited from scram::gui::model::Element
void labelChanged (const QString &label)
void idChanged (const QString &id)
Public Member Functions
BasicEvent (mef::BasicEvent *basicEvent)
Initializes proxy with the MEF basic event and its implicit flavor.
Flavor flavor () const
mef::Expression * expression () const
template<typename T = double>
T probability () const
Public Member Functions inherited from scram::gui::model::Element
QString id () const
QString label () const
Public Member Functions inherited from scram::gui::model::Proxy< BasicEvent, mef::BasicEvent >
const mef::BasicEvent * data () const
mef::BasicEvent * data ()
Static Public Member Functions
static QString flavorToString (Flavor flavor)
Converts a basic event flavor to a UI string.
Additional Inherited Members
Protected Member Functions inherited from scram::gui::model::Element
Element (mef::Element *element)
Stores the reference to the original MEF Element to manage.
Detailed Description
The proxy to manage mef::BasicEvent.
Definition at line 180 of file model.h.
Member Function Documentation
Flavor scram::gui::model::BasicEvent::flavor () const inline
Returns
The flavor of the basic event.
Definition at line 204 of file model.h.
Referenced by BasicEvent(), scram::gui::MainWindow::extract(), scram::gui::diagram::Gate::Gate(), scram::gui::model::BasicEvent::SetFlavor::redo(), and scram::gui::EventDialog::setupData().
mef::Expression* scram::gui::model::BasicEvent::expression () const inline
Returns
The current expression of this basic event. nullptr if no expression has been set.
Definition at line 208 of file model.h.
Referenced by scram::gui::MainWindow::extract().
template<typename T = double> T scram::gui::model::BasicEvent::probability () const inline
Returns
The probability value of the event.
Precondition
The basic event has expression or the type has null state.
Definition at line 217 of file model.h.
void scram::gui::model::BasicEvent::expressionChanged (mef::Expression * expression) signal
Parameters
[in] expression The new expression of the basic event.
Referenced by scram::gui::model::BasicEventContainerModel::data(), and scram::gui::model::BasicEvent::SetExpression::redo().
void scram::gui::model::BasicEvent::flavorChanged (Flavor flavor) signal
Parameters
[in] flavor The new flavor of the basic event.
Referenced by scram::gui::model::BasicEventContainerModel::data(), scram::gui::diagram::DiagramScene::DiagramScene(), and scram::gui::model::BasicEvent::SetFlavor::redo().
The documentation for this class was generated from the following files:
model.h
model.cpp