scram::gui::diagram::Gate Class Reference
scram::gui::diagram::Gate Class Reference
Fault tree intermediate events or gates.
#include <diagram.h>
Public Member Functions
Gate (model::Gate *event, model::Model *model, std::unordered_map< const mef::Gate *, Gate * > *transfer, QGraphicsItem *parent=nullptr)
Constructs the graph with the transfer symbols for gates.
std::unique_ptr< QGraphicsItem > getGateGraphicsType (mef::Connective type)
Constructs graphics object representing the given gate type.
double width () const override
void addTransferOut ()
Adds the transfer-out symbol besides the gate shape.
Public Member Functions inherited from scram::gui::diagram::Event
model::Element * data () const
QRectF boundingRect () const final
Required standard member functions of QGraphicsItem interface.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) final
Required standard member functions of QGraphicsItem interface.
Additional Inherited Members
Protected Member Functions inherited from scram::gui::diagram::Event
Event (model::Element *event, QGraphicsItem *parent=nullptr)
Assigns an event to a presentation view.
QGraphicsItem * getTypeGraphics () const
void setTypeGraphics (QGraphicsItem *item)
Releases the current derived class item, and sets the new one.
QSizeF units () const
Protected Attributes inherited from scram::gui::diagram::Event
model::Element * m_event
The model data.
Static Protected Attributes inherited from scram::gui::diagram::Event
static const QSizeF m_size = {16, 11}
The confining size of the Event graphics in characters.
static const double m_baseHeight = 6.5
The height of the confining space used only by the Event base class.
static const double m_idBoxLength = 10
The length of the ID box in characters.
static const double m_labelBoxHeight = 4
The height of the Label box in characters.
Detailed Description
Fault tree intermediate events or gates.
Definition at line 138 of file diagram.h.
Constructor & Destructor Documentation
scram::gui::diagram::Gate::Gate (model::Gate * event, model::Model * model, std::unordered_map< const mef::Gate *, Gate * > * transfer, QGraphicsItem * parent = nullptr)
Constructs the graph with the transfer symbols for gates.
Parameters
event The event to be converted into a graphics item.
model The model with wrapper object with signals.
transfer The set of already processed gates to be shown as transfer event.
parent The optional parent graphics item.
Definition at line 163 of file diagram.cpp.
References scram::gui::model::Gate::args(), scram::gui::model::BasicEvent::flavor(), getGateGraphicsType(), GUI_ASSERT, scram::gui::diagram::Event::m_baseHeight, scram::gui::diagram::Event::m_size, scram::gui::diagram::Event::setTypeGraphics(), scram::gui::model::Gate::type(), and scram::gui::diagram::Event::units().
Member Function Documentation
double scram::gui::diagram::Gate::width () const override virtual
Returns
The width of the whole subgraph.
Reimplemented from scram::gui::diagram::Event.
Definition at line 337 of file diagram.cpp.
The documentation for this class was generated from the following files:
diagram.h
diagram.cpp