scram::gui::model::Gate Class Reference
scram::gui::model::Gate Class Reference
The proxy to manage mef::Gate.
#include <model.h>
Classes
class SetFormula
Formula modification commands.
Signals
void formulaChanged ()
Indicates gate formula changes or resets.
Signals inherited from scram::gui::model::Element
void labelChanged (const QString &label)
void idChanged (const QString &id)
Public Member Functions
Gate (mef::Gate *gate)
template<typename T = mef::Connective>
T type () const
int numArgs () const
std::optional< int > minNumber () const
const std::vector< mef::Formula::Arg > & args () const
Public Member Functions inherited from scram::gui::model::Element
QString id () const
QString label () const
Public Member Functions inherited from scram::gui::model::Proxy< Gate, mef::Gate >
const mef::Gate * data () const
mef::Gate * data ()
Additional Inherited Members
Public Types inherited from scram::gui::model::Proxy< Gate, mef::Gate >
using Origin = mef::Gate
The MEF type.
Protected Member Functions inherited from scram::gui::model::Element
Element (mef::Element *element)
Stores the reference to the original MEF Element to manage.
Detailed Description
The proxy to manage mef::Gate.
Precondition
The gate formula is flat.
Definition at line 323 of file model.h.
Constructor & Destructor Documentation
scram::gui::model::Gate::Gate (mef::Gate * gate) inline explicit
Parameters
[in,out] gate The MEF gate with a flat formula.
Definition at line 329 of file model.h.
Member Function Documentation
template<typename T = mef::Connective> T scram::gui::model::Gate::type () const inline
Returns
The current connective of the gate.
Definition at line 333 of file model.h.
References scram::gui::_().
Referenced by scram::gui::MainWindow::extract(), scram::gui::diagram::Gate::Gate(), and scram::gui::EventDialog::setupData().
int scram::gui::model::Gate::numArgs () const inline
Returns
The number of gate arguments.
Definition at line 367 of file model.h.
Referenced by scram::gui::MainWindow::extract().
std::optional<int> scram::gui::model::Gate::minNumber () const inline
Returns
The min number of the gate formula.
Definition at line 370 of file model.h.
Referenced by scram::gui::MainWindow::extract(), and scram::gui::EventDialog::setupData().
const std::vector<mef::Formula::Arg>& scram::gui::model::Gate::args () const inline
Returns
Event arguments of the gate.
Definition at line 376 of file model.h.
Referenced by scram::gui::MainWindow::extract(), scram::gui::diagram::Gate::Gate(), and scram::gui::EventDialog::setupData().
The documentation for this class was generated from the following file:
model.h