scram::gui::diagram::DiagramScene Class Reference
scram::gui::diagram::DiagramScene Class Reference
The scene for the fault tree diagram.
#include <diagram.h>
Signals
void activated (model::Element *event)
Public Member Functions
DiagramScene (model::Gate *event, model::Model *model, QObject *parent=nullptr)
Recursively populates the scene with fault tree object graphics.
Detailed Description
The scene for the fault tree diagram.
Definition at line 169 of file diagram.h.
Constructor & Destructor Documentation
scram::gui::diagram::DiagramScene::DiagramScene (model::Gate * event, model::Model * model, QObject * parent = nullptr)
Recursively populates the scene with fault tree object graphics.
Parameters
[in] event The root proxy gate of the fault tree.
[in] model The model proxy managing the data.
[in,out] parent The optional owner of this object.
<
Todo:
Remove the implicit delete.
Definition at line 357 of file diagram.cpp.
References activated(), scram::gui::model::BasicEvent::flavorChanged(), scram::gui::model::Gate::formulaChanged(), scram::gui::model::Model::gates(), GUI_ASSERT, and scram::gui::model::Model::removed().
Member Function Documentation
void scram::gui::diagram::DiagramScene::activated (model::Element * event) signal
Parameters
[in] event The event which graphics received activation.
Referenced by DiagramScene(), and scram::gui::MainWindow::constructElementTable< model::GateContainerModel >().
The documentation for this class was generated from the following files:
diagram.h
diagram.cpp