scram::gui::model::ElementContainerModel Class Reference
scram::gui::model::ElementContainerModel Class Reference
The base class for models to list elements in a table.
#include <elementcontainermodel.h>
Public Member Functions
int rowCount (const QModelIndex &parent) const override
Protected Member Functions
template<class T >
ElementContainerModel (const T &container, Model *model, QObject *parent=nullptr)
QModelIndex index (int row, int column, const QModelIndex &parent) const override
Puts the element pointer into the index's internal pointer.
QModelIndex parent (const QModelIndex &) const override
Assumes the table-layout and returns null index.
Element * getElement (int index) const
int getElementIndex (Element *element) const
const std::vector< Element * > & elements () const
virtual void connectElement (Element *element)
Connects of the element change signals to the table modification.
Detailed Description
The base class for models to list elements in a table.
The model contains the original element pointer for Qt::UserRole. This only applies to top-level indices.
Definition at line 42 of file elementcontainermodel.h.
Constructor & Destructor Documentation
template<class T > scram::gui::model::ElementContainerModel::ElementContainerModel (const T & container, Model * model, QObject * parent = nullptr) explicit protected
Template Parameters
T The container type of smart pointers to elements.
Parameters
[in] container The data container.
[in] model The model managing the proxy Elements.
[in,out] parent The optional owner of this object.
Definition at line 33 of file elementcontainermodel.cpp.
References scram::gui::model::Model::added(), and scram::gui::model::Model::removed().
Member Function Documentation
int scram::gui::model::ElementContainerModel::rowCount (const QModelIndex & parent) const override
Parameters
[in] parent The top index (i.e., not valid).
Returns
The number of elements in the list as the row count.
Definition at line 113 of file elementcontainermodel.cpp.
Referenced by scram::gui::model::GateContainerModel::rowCount().
Element * scram::gui::model::ElementContainerModel::getElement (int index) const protected
Parameters
[in] index The top row index in this container model.
Returns
The element with the given index (row).
Precondition
The index is valid.
Definition at line 70 of file elementcontainermodel.cpp.
References GUI_ASSERT, and index().
Referenced by index(), and parent().
int scram::gui::model::ElementContainerModel::getElementIndex (Element * element) const protected
Parameters
[in] element The element in this container model.
Returns
The current index (row) of the element.
Precondition
The element is in the table.
Definition at line 76 of file elementcontainermodel.cpp.
References connectElement(), GUI_ASSERT, and index().
Referenced by connectElement(), scram::gui::model::BasicEventContainerModel::data(), scram::gui::model::HouseEventContainerModel::data(), scram::gui::model::GateContainerModel::GateContainerModel(), parent(), and scram::gui::model::GateContainerModel::parent().
const std::vector<Element *>& scram::gui::model::ElementContainerModel::elements () const inline protected
Returns
The current elements in the container.
Definition at line 84 of file elementcontainermodel.h.
References connectElement().
Referenced by scram::gui::model::BasicEventContainerModel::BasicEventContainerModel(), scram::gui::model::GateContainerModel::GateContainerModel(), and scram::gui::model::HouseEventContainerModel::HouseEventContainerModel().
void scram::gui::model::ElementContainerModel::connectElement (Element * element) protected virtual
Connects of the element change signals to the table modification.
The base implementation only handles signals coming from base element. The derived classes need to override this function and append more connections.
Parameters
[in] element The element in this container model.
Definition at line 50 of file elementcontainermodel.cpp.
References getElementIndex(), scram::gui::model::Element::idChanged(), index(), and scram::gui::model::Element::labelChanged().
Referenced by scram::gui::model::BasicEventContainerModel::data(), scram::gui::model::HouseEventContainerModel::data(), elements(), scram::gui::model::GateContainerModel::GateContainerModel(), and getElementIndex().
The documentation for this class was generated from the following files:
elementcontainermodel.h
elementcontainermodel.cpp