scram::gui::ModelTree Class Reference
scram::gui::ModelTree Class Reference
The tree representation for the Model constructs.
#include <modeltree.h>
Public Types
enum Row { FaultTrees, Gates, BasicEvents, HouseEvents }
The top row containers of the tree.
Public Member Functions
ModelTree (model::Model *model, QObject *parent=nullptr)
Constructs with the proxy Model as the data.
QVariant data (const QModelIndex &index, int role) const override
Provides the data for the tree items.
int rowCount (const QModelIndex &parent) const override
Required standard member functions of QAbstractItemModel interface.
int columnCount (const QModelIndex &parent) const override
Required standard member functions of QAbstractItemModel interface.
QModelIndex index (int row, int column, const QModelIndex &parent) const override
Required standard member functions of QAbstractItemModel interface.
QModelIndex parent (const QModelIndex &index) const override
Required standard member functions of QAbstractItemModel interface.
Detailed Description
The tree representation for the Model constructs.
Definition at line 35 of file modeltree.h.
Member Function Documentation
QVariant scram::gui::ModelTree::data (const QModelIndex & index, int role) const override
Provides the data for the tree items.
Parameters
[in] index The index in this model.
[in] role The role of the data.
Returns
The index data for the given role.
Note
The Qt::UserRole provides the pointer to the original model element if applicable.
Definition at line 112 of file modeltree.cpp.
References scram::gui::_(), scram::gui::model::Model::basicEvents(), scram::gui::model::Model::faultTrees(), scram::gui::model::Model::gates(), GUI_ASSERT, and scram::gui::model::Model::houseEvents().
The documentation for this class was generated from the following files:
modeltree.h
modeltree.cpp