scram::gui::diagram::Event Class Reference
scram::gui::diagram::Event Class Reference
The base class for probabilistic events in a fault tree.
#include <diagram.h>
Public Member Functions
virtual double width () const
model::Element * data () const
QRectF boundingRect () const final
Required standard member functions of QGraphicsItem interface.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) final
Required standard member functions of QGraphicsItem interface.
Protected Member Functions
Event (model::Element *event, QGraphicsItem *parent=nullptr)
Assigns an event to a presentation view.
QGraphicsItem * getTypeGraphics () const
void setTypeGraphics (QGraphicsItem *item)
Releases the current derived class item, and sets the new one.
QSizeF units () const
Protected Attributes
model::Element * m_event
The model data.
Static Protected Attributes
static const QSizeF m_size = {16, 11}
The confining size of the Event graphics in characters.
static const double m_baseHeight = 6.5
The height of the confining space used only by the Event base class.
static const double m_idBoxLength = 10
The length of the ID box in characters.
static const double m_labelBoxHeight = 4
The height of the Label box in characters.
Detailed Description
The base class for probabilistic events in a fault tree.
The base event item provides only the boxes containing the name and description of the event. A derived class must provide the symbolic representation of its kind.
The sizes are measured in units of character height and average width. This class provides the reference units for derived classes to use. All derived class shapes should stay within the allowed box limits to make the fault tree structure layered.
Definition at line 47 of file diagram.h.
Constructor & Destructor Documentation
scram::gui::diagram::Event::Event (model::Element * event, QGraphicsItem * parent = nullptr) explicit protected
Assigns an event to a presentation view.
Parameters
event The model event.
parent The parent Graphics event.
Definition at line 51 of file diagram.cpp.
References scram::gui::model::Element::idChanged(), and scram::gui::model::Element::labelChanged().
Member Function Documentation
double scram::gui::diagram::Event::width () const virtual
Returns
The width of the whole subgraph.
Reimplemented in scram::gui::diagram::Gate.
Definition at line 73 of file diagram.cpp.
References m_size, and units().
model::Element* scram::gui::diagram::Event::data () const inline
Returns
The model data event.
Definition at line 63 of file diagram.h.
References m_event.
QGraphicsItem* scram::gui::diagram::Event::getTypeGraphics () const inline protected
Returns
The graphics of the derived class.
Definition at line 84 of file diagram.h.
References setTypeGraphics(), and units().
Referenced by scram::gui::diagram::Gate::addTransferOut().
void scram::gui::diagram::Event::setTypeGraphics (QGraphicsItem * item) protected
Releases the current derived class item, and sets the new one.
Parameters
item The new item to represent the derived type.
Definition at line 78 of file diagram.cpp.
References m_baseHeight, and units().
Referenced by scram::gui::diagram::BasicEvent::BasicEvent(), scram::gui::diagram::Gate::Gate(), getTypeGraphics(), scram::gui::diagram::HouseEvent::HouseEvent(), scram::gui::diagram::TransferIn::TransferIn(), and scram::gui::diagram::UndevelopedEvent::UndevelopedEvent().
QSizeF scram::gui::diagram::Event::units () const protected
Returns
Unit width (x) and height (y) for shapes.
Definition at line 67 of file diagram.cpp.
Referenced by scram::gui::diagram::Gate::addTransferOut(), scram::gui::diagram::BasicEvent::BasicEvent(), boundingRect(), scram::gui::diagram::Gate::Gate(), scram::gui::diagram::Gate::getGateGraphicsType(), getTypeGraphics(), scram::gui::diagram::HouseEvent::HouseEvent(), paint(), setTypeGraphics(), scram::gui::diagram::TransferIn::TransferIn(), scram::gui::diagram::UndevelopedEvent::UndevelopedEvent(), and width().
Member Data Documentation
const QSizeF scram::gui::diagram::Event::m_size = {16, 11} static protected
The confining size of the Event graphics in characters.
The derived event types should stay within this confinement.
Definition at line 68 of file diagram.h.
Referenced by scram::gui::diagram::BasicEvent::BasicEvent(), boundingRect(), scram::gui::diagram::Gate::Gate(), scram::gui::diagram::HouseEvent::HouseEvent(), paint(), scram::gui::diagram::TransferIn::TransferIn(), scram::gui::diagram::UndevelopedEvent::UndevelopedEvent(), and width().
const double scram::gui::diagram::Event::m_idBoxLength = 10 static protected
The length of the ID box in characters.
The height of the ID box is 1 character.
Definition at line 73 of file diagram.h.
Referenced by paint().
The documentation for this class was generated from the following files:
diagram.h
diagram.cpp