scram::gui::model::HouseEvent Class Reference
scram::gui::model::HouseEvent Class Reference
The proxy to manage mef::HouseEvent.
#include <model.h>
Classes
class SetState
Flips the house event state.
Signals
void stateChanged (bool value)
Signals inherited from scram::gui::model::Element
void labelChanged (const QString &label)
void idChanged (const QString &id)
Public Member Functions
HouseEvent (mef::HouseEvent *houseEvent)
template<typename T = bool>
T state () const
Public Member Functions inherited from scram::gui::model::Element
QString id () const
QString label () const
Public Member Functions inherited from scram::gui::model::Proxy< HouseEvent, mef::HouseEvent >
const mef::HouseEvent * data () const
mef::HouseEvent * data ()
Additional Inherited Members
Public Types inherited from scram::gui::model::Proxy< HouseEvent, mef::HouseEvent >
using Origin = mef::HouseEvent
The MEF type.
Protected Member Functions inherited from scram::gui::model::Element
Element (mef::Element *element)
Stores the reference to the original MEF Element to manage.
Detailed Description
The proxy to manage mef::HouseEvent.
Definition at line 281 of file model.h.
Constructor & Destructor Documentation
scram::gui::model::HouseEvent::HouseEvent (mef::HouseEvent * houseEvent) inline explicit
Parameters
[in,out] houseEvent The MEF house event.
Definition at line 287 of file model.h.
Member Function Documentation
template<typename T = bool> T scram::gui::model::HouseEvent::state () const inline
Returns
The state data of the house event.
Definition at line 291 of file model.h.
References scram::gui::model::boolToString().
Referenced by scram::gui::MainWindow::extract(), scram::gui::model::HouseEvent::SetState::redo(), and scram::gui::EventDialog::setupData().
void scram::gui::model::HouseEvent::stateChanged (bool value) signal
Parameters
[in] value The value of the house event's new state.
Referenced by scram::gui::model::HouseEventContainerModel::data(), and scram::gui::model::HouseEvent::SetState::redo().
The documentation for this class was generated from the following file:
model.h