scram::gui::EventDialog Class Reference
scram::gui::EventDialog Class Reference
The Dialog to create, present, and manipulate event data.
#include <eventdialog.h>
Public Types
enum EventType { HouseEvent = 1 << 0, BasicEvent = 1 << 1, Undeveloped = 1 << 2, Gate = 1 << 3 }
Event types as listed in the drop-down.
Public Slots
void validate ()
Triggers validation of the current data.
Signals
void validated (bool valid)
void formulaArgsChanged ()
Indicates changes in the list of formula arguments.
Public Member Functions
EventDialog (mef::Model *model, QWidget *parent=nullptr)
Creates a dialog for the definition of a new event.
EventType currentType () const
QString name () const
QString label () const
bool booleanConstant () const
std::unique_ptr< mef::Expression > expression () const
mef::Connective connective () const
int minNumber () const
std::vector< std::string > arguments () const
std::string faultTree () const
template<>
mef::FaultTree * getFaultTree (const mef::Gate *event) const
Finds fault tree container of the gate.
void setupData (const model::Gate &element)
Sets up the dialog with element data.
void setupData (const model::HouseEvent &element)
Sets up the dialog with element data.
void setupData (const model::BasicEvent &element)
Sets up the dialog with element data.
Detailed Description
The Dialog to create, present, and manipulate event data.
Only valid data is accepted by this dialog. That is, the dialog constrains the user input to be valid, and upon the acceptance, it guarantees that the data is valid for usage by the Model classes.
However, the requested data must be relevant to the current type.
Precondition
The model is normalized.
Todo:
Generalize to all model element types.
Definition at line 54 of file eventdialog.h.
Constructor & Destructor Documentation
scram::gui::EventDialog::EventDialog (mef::Model * model, QWidget * parent = nullptr) explicit
Creates a dialog for the definition of a new event.
Parameters
[in,out] model The model with valid data.
[in,out] parent The optional owner of this object.
Todo:
Implement container change.
Todo:
Enable fault-tree as a container for events.
Definition at line 47 of file eventdialog.cpp.
References scram::gui::_(), formulaArgsChanged(), GUI_ASSERT, scram::gui::Validator::name(), name(), scram::gui::Validator::nonNegative(), scram::gui::Validator::probability(), validate(), and validated().
Member Function Documentation
void scram::gui::EventDialog::setupData (const model::Gate & element)
Sets up the dialog with element data.
Parameters
[in] element The existing valid element in the model.
Precondition
Only one element type is requested for the setup.
Todo:
Consider providing a template constructor instead.
Todo:
Deal with type changes of the top gate.
<
Todo:
Bogus signal order conflicts.
Definition at line 296 of file eventdialog.cpp.
References scram::gui::model::Gate::args(), scram::gui::model::Proxy< E, T >::data(), formulaArgsChanged(), scram::gui::model::Gate::minNumber(), and scram::gui::model::Gate::type().
Referenced by scram::gui::MainWindow::extract(), faultTree(), getFaultTree(), scram::gui::MainWindow::constructElementTable< model::GateContainerModel >(), and setupData().
void scram::gui::EventDialog::setupData (const model::HouseEvent & element)
Sets up the dialog with element data.
Parameters
[in] element The existing valid element in the model.
Precondition
Only one element type is requested for the setup.
Todo:
Consider providing a template constructor instead.
Todo:
Deal with type changes of the top gate.
<
Todo:
Bogus signal order conflicts.
Definition at line 265 of file eventdialog.cpp.
References scram::gui::model::Proxy< E, T >::data(), setupData(), and scram::gui::model::HouseEvent::state().
void scram::gui::EventDialog::setupData (const model::BasicEvent & element)
Sets up the dialog with element data.
Parameters
[in] element The existing valid element in the model.
Precondition
Only one element type is requested for the setup.
Todo:
Consider providing a template constructor instead.
Todo:
Deal with type changes of the top gate.
<
Todo:
Bogus signal order conflicts.
Definition at line 272 of file eventdialog.cpp.
References scram::gui::model::Proxy< E, T >::data(), scram::gui::model::BasicEvent::flavor(), GUI_ASSERT, and setupData().
EventType scram::gui::EventDialog::currentType () const inline
Returns
The type being defined by this dialog.
Definition at line 88 of file eventdialog.h.
Referenced by scram::gui::MainWindow::extract().
QString scram::gui::EventDialog::name () const inline
Returns
The name data.
Definition at line 94 of file eventdialog.h.
Referenced by arguments(), EventDialog(), scram::gui::MainWindow::extract(), and faultTree().
QString scram::gui::EventDialog::label () const inline
Returns
The label data.
Definition at line 96 of file eventdialog.h.
Referenced by scram::gui::MainWindow::extract().
bool scram::gui::EventDialog::booleanConstant () const inline
Returns
The Boolean constant data.
Definition at line 99 of file eventdialog.h.
References expression().
Referenced by scram::gui::MainWindow::extract().
std::unique_ptr< mef::Expression > scram::gui::EventDialog::expression () const
Returns
The probability expression for basic events. nullptr if no expression is defined.
Definition at line 320 of file eventdialog.cpp.
References GUI_ASSERT.
Referenced by booleanConstant(), and scram::gui::MainWindow::extract().
mef::Connective scram::gui::EventDialog::connective () const inline
Returns
The connective for the formula.
Definition at line 106 of file eventdialog.h.
Referenced by scram::gui::MainWindow::extract().
int scram::gui::EventDialog::minNumber () const inline
Returns
The value for the min number for formulas.
Definition at line 112 of file eventdialog.h.
References arguments().
Referenced by scram::gui::MainWindow::extract().
std::vector< std::string > scram::gui::EventDialog::arguments () const
Returns
The set of formula argument ids.
Definition at line 179 of file eventdialog.cpp.
References name().
Referenced by scram::gui::MainWindow::extract(), and minNumber().
std::string scram::gui::EventDialog::faultTree () const inline
Returns
The fault tree container name.
Definition at line 118 of file eventdialog.h.
References formulaArgsChanged(), name(), setupData(), validate(), and validated().
Referenced by scram::gui::MainWindow::extract(), and getFaultTree().
void scram::gui::EventDialog::validated (bool valid) signal
Parameters
[in] valid True if the current changes and data are valid.
Referenced by EventDialog(), faultTree(), and validate().
The documentation for this class was generated from the following files:
eventdialog.h
eventdialog.cpp