scram::gui::model::Proxy< E, T > Class Template Reference
scram::gui::model::Proxy< E, T > Class Template Reference
Provides the type and data of the origin for Proxy Elements.
#include <model.h>
Public Types
using Origin = T
The MEF type.
Public Member Functions
const T * data () const
T * data ()
Detailed Description
template<class E, class T>
class scram::gui::model::Proxy< E, T >
Provides the type and data of the origin for Proxy Elements.
Template Parameters
E The Element class.
T The MEF class.
Definition at line 161 of file model.h.
Member Function Documentation
template<class E, class T> const T* scram::gui::model::Proxy< E, T >::data () const inline
Returns
The original data managed by the proxy.
Definition at line 168 of file model.h.
Referenced by scram::gui::model::BasicEvent::SetExpression::redo(), scram::gui::model::BasicEvent::SetFlavor::redo(), scram::gui::model::HouseEvent::SetState::redo(), scram::gui::model::Gate::SetFormula::redo(), and scram::gui::EventDialog::setupData().
template<class E, class T> T* scram::gui::model::Proxy< E, T >::data () inline
Returns
The original data managed by the proxy.
Definition at line 172 of file model.h.
The documentation for this class was generated from the following file:
model.h