scram::gui::MainWindow Class Reference
scram::gui::MainWindow Class Reference
#include <mainwindow.h>
Signals
void projectChanged ()
Indicates addition of new input or project files.
Public Member Functions
MainWindow (QWidget *parent=nullptr)
bool setProjectFile (const std::string &projectFilePath, std::vector< std::string > inputFiles={})
Loads a model and analysis from a project file.
bool addInputFiles (const std::vector< std::string > &inputFiles)
Adds a new set of model elements from input files.
template<>
mef::FaultTree * getFaultTree (mef::Gate *gate)
Specialization to find the fault tree container of a gate.
template<>
void removeEvent (model::Gate *event, mef::FaultTree *faultTree)
Specialization to deal with complexities of gate/fault-tree removal.
template<>
std::unique_ptr< mef::Formula > extract (const EventDialog &dialog)
Specialization to construct formula out of event editor data.
template<>
std::unique_ptr< mef::BasicEvent > extract (const EventDialog &dialog)
Specialization to construct basic event out of event editor data.
template<>
std::unique_ptr< mef::HouseEvent > extract (const EventDialog &dialog)
Specialization to construct house event out of event editor data.
template<>
std::unique_ptr< mef::Gate > extract (const EventDialog &dialog)
Specialization to construct gate out of event editor data.
Detailed Description
Todo:
Static build issues if the header is included.
Definition at line 55 of file mainwindow.h.
Constructor & Destructor Documentation
scram::gui::MainWindow::MainWindow (QWidget * parent = nullptr) explicit
Parameters
[in,out] parent The optional owner of this object.
Definition at line 154 of file mainwindow.cpp.
References scram::gui::_(), GUI_ASSERT, and scram::gui::Validator::percent().
Member Function Documentation
bool scram::gui::MainWindow::setProjectFile (const std::string & projectFilePath, std::vector< std::string > inputFiles = {})
Loads a model and analysis from a project file.
Parameters
[in] projectFilePath The path to the project configuration file.
[in] inputFiles Additional input files for model initialization.
Returns
true if the initialization is successful.
Postcondition
No side effects are left-over if the initialization is not successful.
Definition at line 284 of file mainwindow.cpp.
References scram::gui::_(), and addInputFiles().
Referenced by main().
bool scram::gui::MainWindow::addInputFiles (const std::vector< std::string > & inputFiles)
Adds a new set of model elements from input files.
Parameters
[in] inputFiles Paths to input files.
Returns
true if the addition is successful.
Postcondition
If the addition of any file is not successful, the model is left in its original state as if this function had not been called (i.e., transactional).
Definition at line 314 of file mainwindow.cpp.
References scram::gui::_(), GUI_ASSERT, projectChanged(), scram::gui::ZoomableView::zoomBestFit(), and scram::gui::ZoomableView::zoomChanged().
Referenced by main(), and setProjectFile().
template<> mef::FaultTree* scram::gui::MainWindow::getFaultTree (mef::Gate * gate)
Specialization to find the fault tree container of a gate.
Parameters
[in] gate The gate belonging exactly to one fault tree.
Returns
The fault tree container with the given gate.
Todo:
Duplicate code from EventDialog.
Definition at line 1019 of file mainwindow.cpp.
References GUI_ASSERT.
template<> std::unique_ptr<mef::Formula> scram::gui::MainWindow::extract (const EventDialog & dialog)
Specialization to construct formula out of event editor data.
Parameters
[in] dialog The valid event dialog with data for a gate formula.
Returns
A new formula with arguments from the event dialog.
Todo:
Add into the parent undo.
Definition at line 1150 of file mainwindow.cpp.
References scram::gui::EventDialog::arguments(), scram::gui::EventDialog::connective(), and scram::gui::EventDialog::minNumber().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp