scram::gui::model::Element Class Reference
scram::gui::model::Element Class Reference
The base proxy Element model for mef::Element.
#include <model.h>
Classes
class SetId
Sets the name of an Element.
class SetLabel
Sets the label of an Element.
Signals
void labelChanged (const QString &label)
void idChanged (const QString &id)
Public Member Functions
QString id () const
QString label () const
Protected Member Functions
Element (mef::Element *element)
Stores the reference to the original MEF Element to manage.
Friends
template<class , class >
class Proxy
Detailed Description
The base proxy Element model for mef::Element.
Definition at line 66 of file model.h.
Member Function Documentation
QString scram::gui::model::Element::id () const inline
Returns
A unique ID string for element within the element type-group.
Precondition
The element is public.
Definition at line 77 of file model.h.
Referenced by scram::gui::model::BasicEventContainerModel::data(), scram::gui::model::HouseEventContainerModel::data(), scram::gui::model::GateContainerModel::data(), scram::gui::MainWindow::extract(), scram::gui::EventDialog::getFaultTree(), scram::gui::diagram::Event::paint(), scram::gui::model::Model::SetName::redo(), and scram::gui::MainWindow::removeEvent().
QString scram::gui::model::Element::label () const inline
Returns
The additional description for the element.
Definition at line 80 of file model.h.
Referenced by scram::gui::MainWindow::extract(), scram::gui::EventDialog::getFaultTree(), scram::gui::diagram::Event::paint(), scram::gui::model::Element::SetLabel::redo(), and scram::gui::model::Element::SetId< T >::redo().
void scram::gui::model::Element::labelChanged (const QString & label) signal
Parameters
[in] label The new label of the element.
Referenced by scram::gui::model::ElementContainerModel::connectElement(), scram::gui::diagram::Event::Event(), scram::gui::model::Element::SetLabel::redo(), and scram::gui::model::Element::SetId< T >::redo().
void scram::gui::model::Element::idChanged (const QString & id) signal
Parameters
[in] id The new ID of the element.
Referenced by scram::gui::model::ElementContainerModel::connectElement(), scram::gui::diagram::Event::Event(), and scram::gui::model::Element::SetId< T >::redo().
The documentation for this class was generated from the following file:
model.h