language.h File Reference
language.h File Reference
Localization and translation facilities.
#include <string>
#include <vector>
#include <QString>
Functions
const std::string & scram::gui::translationsPath ()
std::vector< std::string > scram::gui::translations ()
QString scram::gui::nativeLanguageName (const std::string &locale)
Detailed Description
Localization and translation facilities.
Definition in file language.h.
Function Documentation
const std::string & scram::gui::translationsPath ()
Returns
The path to SCRAM GUI translations directory.
Definition at line 36 of file language.cpp.
References scram::gui::translationsPath().
Referenced by scram::gui::translations(), and scram::gui::translationsPath().
std::vector< std::string > scram::gui::translations ()
Returns
Available translations represented with locale with underscores.
Postcondition
The default English is not expected to be in translations.
Definition at line 43 of file language.cpp.
References scram::gui::translations(), and scram::gui::translationsPath().
Referenced by scram::gui::translations().
QString scram::gui::nativeLanguageName (const std::string & locale)
Parameters
[in] locale The locale code with underscores.
Returns
The native language name ready to be used in UI.
Precondition
The locale string is valid as required by QLocale.
The locale language is a valid human language (not "C").
Definition at line 69 of file language.cpp.
References GUI_ASSERT, and scram::gui::nativeLanguageName().
Referenced by scram::gui::nativeLanguageName().