/// @file fault_tree.h
/// Fault Tree.
#ifndef SCRAM_FAULT_TREE_H_
#define SCRAM_FAULT_TREE_H_

#include <map>
#include <string>

#include <boost/shared_ptr.hpp>
#include <boost/unordered_map.hpp>

#include "error.h"
#include "event.h"

typedef boost::shared_ptr<scram::Event> EventPtr;
typedef boost::shared_ptr<scram::Gate> GatePtr;
typedef boost::shared_ptr<scram::PrimaryEvent> PrimaryEventPtr;

namespace scram {

/// @class FaultTree
/// Fault tree representation.
class FaultTree {

 public:
  /// The main constructor of the Fault Tree.
  /// @param[in] name The name identificator of this fault tree.
  explicit FaultTree(std::string name);

  virtual ~FaultTree() {}

  /// New tree methhods.
  void AddGate(GatePtr& gate);

  /// @returns The name of this tree.
  const std::string& name() { return name_; }

  /// @returns The warnings generated by all the tree operations.
  const std::string& warnings() { return warnings_; }

  /// @returns The top gate.
  const GatePtr& top_event() { return top_event_; }

  /// @returns The container of intermediate events.
  const boost::unordered_map<std::string, GatePtr>& inter_events() {
    return inter_events_;
  }

  /// @returns The container of primary events of this tree.
  /// @note Assuming that all events in this tree are defined to be gates or
  /// primary events.
  const boost::unordered_map<std::string, PrimaryEventPtr>& primary_events() {
    if (changed_) GatherPrimaryEvents();
    return primary_events_;
  }

 private:
  /// Picks primary events of this tree.
  /// Locks the tree from any further changes.
  void GatherPrimaryEvents();

  /// Picks primary events of the specified gate.
  /// The primary events are put into the approriate container.
  void GetPrimaryEvents(GatePtr& gate);

  /// The name of this fault tree.
  std::string name_;
  /// This member is used to provide any warnings about assumptions,
  /// calculations, and settings. These warnings must be written into output
  /// file.
  std::string warnings_;

  /// Id of a top event.
  std::string top_event_id_;

  /// Top event.
  GatePtr top_event_;

  /// Holder for intermediate events.
  boost::unordered_map<std::string, GatePtr> inter_events_;

  /// Container for the primary events of the tree.
  boost::unordered_map<std::string, PrimaryEventPtr> primary_events_;

  /// Indication if the events in the tree have changed.
  bool changed_;
};

}  // namespace scram

#endif  // SCRAM_FAULT_TREE_H_
