bdd.h File Reference
bdd.h File Reference
Fault tree analysis with the Binary Decision Diagram algorithms.
#include <cmath>
#include <algorithm>
#include <forward_list>
#include <memory>
#include <unordered_map>
#include <utility>
#include <vector>
#include <boost/functional/hash.hpp>
#include <boost/noncopyable.hpp>
#include <boost/smart_ptr/intrusive_ptr.hpp>
#include "pdag.h"
#include "settings.h"
Classes
class scram::core::Vertex< T >
Representation of a vertex in BDD graphs.
struct scram::core::IntrusivePtrCast< T, W >
Provides pointer and reference cast wrappers for intrusive Vertex pointers.
class scram::core::WeakIntrusivePtr< T >
A weak pointer to store in BDD unique tables.
class scram::core::Terminal< T >
Representation of terminal vertices in BDD graphs.
class scram::core::Vertex< T >
Representation of a vertex in BDD graphs.
class scram::core::Terminal< T >
Representation of terminal vertices in BDD graphs.
class scram::core::NonTerminal< T >
Representation of non-terminal vertices in BDD graphs.
class scram::core::Ite
Representation of non-terminal if-then-else vertices in BDD graphs.
class scram::core::UniqueTable< T >
A hash table for keeping BDD reduced.
class scram::core::CacheTable< V >
A hash table without collision resolution.
class scram::core::Bdd
Analysis of PDAGs with Binary Decision Diagrams.
struct scram::core::Bdd::Function
Holder of computation resultant functions and gate representations.
class scram::core::Bdd::Consensus
Provides access to consensus calculation private facilities.
Typedefs
template<class T >
using scram::core::IntrusivePtr = boost::intrusive_ptr< T >
The default management of BDD vertices.
using scram::core::ItePtr = IntrusivePtr< Ite >
Shared if-then-else vertices.
Functions
int scram::core::GetPrimeNumber (int n)
Prime number generation for hash tables.
Detailed Description
Fault tree analysis with the Binary Decision Diagram algorithms.
Definition in file bdd.h.
Typedef Documentation
template<class T > using scram::core::IntrusivePtr = typedef boost::intrusive_ptr<T>
The default management of BDD vertices.
Template Parameters
T The type of the main functional BDD vertex.
Definition at line 45 of file bdd.h.
Function Documentation
int scram::core::GetPrimeNumber (int n)
Prime number generation for hash tables.
Parameters
[in] n The starting candidate for a prime number.
Returns
Probable prime number >= n.
Definition at line 32 of file bdd.cc.
References scram::core::GetPrimeNumber().
Referenced by scram::core::CacheTable< Function >::CacheTable(), scram::core::GetPrimeNumber(), and scram::core::UniqueTable< scram::core::Ite >::UniqueTable().