bits.h File Reference
bits.h File Reference
Helper constexpr functions to make bit operations explicit.
Functions
constexpr bool ext::test_bit (std::uint64_t bits, int index) noexcept
Tests the value of a bit.
constexpr int ext::count_trailing_zero_bits (std::uint64_t bits) noexcept
Counts the trailing zero bits.
constexpr int ext::one_bit_index (std::uint64_t bits) noexcept
Helper function to map single bit integer/enum values into indices.
Detailed Description
Helper constexpr functions to make bit operations explicit.
Definition in file bits.h.
Function Documentation
constexpr bool ext::test_bit (std::uint64_t bits, int index) noexcept
Tests the value of a bit.
Parameters
[in] bits The array of bits.
[in] index The index of the bit to test.
Returns
The bit value in the given index.
Precondition
The index is in [0, size(bit-array)).
Definition at line 33 of file bits.h.
References ext::test_bit().
Referenced by ext::count_trailing_zero_bits(), and ext::test_bit().
constexpr int ext::count_trailing_zero_bits (std::uint64_t bits) noexcept
Counts the trailing zero bits.
Parameters
[in] bits The positive number representing a bit array.
Returns
The number of trailing 0 bits (the index of the first 1 bit).
Precondition
bits is not 0.
Definition at line 45 of file bits.h.
References ext::count_trailing_zero_bits(), and ext::test_bit().
Referenced by ext::count_trailing_zero_bits(), and ext::one_bit_index().
constexpr int ext::one_bit_index (std::uint64_t bits) noexcept
Helper function to map single bit integer/enum values into indices.
Parameters
[in] bits The value represented as an array of bits.
Returns
The index of the first 1 bit in the positive bit array.
Precondition
The bits value is not 0.
Definition at line 63 of file bits.h.
References ext::count_trailing_zero_bits(), and ext::one_bit_index().
Referenced by ext::one_bit_index().