scram::mef::Link Class Reference
scram::mef::Link Class Reference
A link to another event tree in end-states only.
#include <instruction.h>
Public Member Functions
Link (const EventTree &event_tree)
const EventTree & event_tree () const
Public Member Functions inherited from scram::mef::Visitable< Link >
void Accept (InstructionVisitor *visitor) const final
Calls visit with the object pointer T*.
Public Member Functions inherited from scram::mef::NodeMark
Mark mark () const
void mark (Mark label)
Sets the mark for this node.
Additional Inherited Members
Public Types inherited from scram::mef::NodeMark
enum Mark : std::uint8_t { kClear = 0, kTemporary, kPermanent }
Possible marks for the node.
Detailed Description
A link to another event tree in end-states only.
Definition at line 174 of file instruction.h.
Constructor & Destructor Documentation
scram::mef::Link::Link (const EventTree & event_tree) inline explicit
Parameters
[in] event_tree The event tree to be linked in the end-sequence.
Definition at line 177 of file instruction.h.
Member Function Documentation
const EventTree& scram::mef::Link::event_tree () const inline
Returns
The referenced event tree in the link.
Definition at line 180 of file instruction.h.
Referenced by scram::core::EventTreeAnalysis::Analyze(), scram::mef::cycle::GetConnector(), and scram::mef::cycle::GetUniqueName().
The documentation for this class was generated from the following file:
instruction.h