scram::mef::Rule Class Reference
scram::mef::Rule Class Reference
A reusable collection of instructions.
#include <instruction.h>
Public Member Functions
void instructions (std::vector< Instruction * > instructions)
const std::vector< Instruction * > & instructions () const
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Visitable< Rule >
void Accept (InstructionVisitor *visitor) const final
Calls visit with the object pointer T*.
Public Member Functions inherited from scram::mef::NodeMark
Mark mark () const
void mark (Mark label)
Sets the mark for this node.
Public Member Functions inherited from scram::mef::Usage
bool usage () const
void usage (bool usage)
Static Public Attributes
static constexpr const char * kTypeString = "rule"
For error messages.
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Public Types inherited from scram::mef::NodeMark
enum Mark : std::uint8_t { kClear = 0, kTemporary, kPermanent }
Possible marks for the node.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Detailed Description
A reusable collection of instructions.
Definition at line 147 of file instruction.h.
Member Function Documentation
void scram::mef::Rule::instructions (std::vector< Instruction * > instructions) inline
Parameters
[in] instructions One or more instructions for the sequence.
Definition at line 157 of file instruction.h.
Referenced by scram::mef::cycle::ContinueConnector(), scram::mef::Initializer::Define(), and scram::mef::InstructionVisitor::Visit().
const std::vector<Instruction*>& scram::mef::Rule::instructions () const inline
Returns
The instructions to be applied in the rule.
Definition at line 163 of file instruction.h.
The documentation for this class was generated from the following file:
instruction.h