scram::mef::IfThenElse Class Reference
scram::mef::IfThenElse Class Reference
Conditional application of instructions.
#include <instruction.h>
Public Member Functions
IfThenElse (Expression *expression, Instruction *then_instruction, Instruction *else_instruction=nullptr)
Expression * expression () const
Instruction * then_instruction () const
Instruction * else_instruction () const
Public Member Functions inherited from scram::mef::Visitable< IfThenElse >
void Accept (InstructionVisitor *visitor) const final
Calls visit with the object pointer T*.
Detailed Description
Conditional application of instructions.
Definition at line 103 of file instruction.h.
Constructor & Destructor Documentation
scram::mef::IfThenElse::IfThenElse (Expression * expression, Instruction * then_instruction, Instruction * else_instruction = nullptr) inline
Parameters
[in] expression The expression to evaluate for truth.
[in] then_instruction The required instruction to execute.
[in] else_instruction An optional instruction for the false case.
Definition at line 108 of file instruction.h.
Member Function Documentation
Expression* scram::mef::IfThenElse::expression () const inline
Returns
The conditional expression of the ternary instruction.
Definition at line 115 of file instruction.h.
Referenced by scram::mef::InstructionVisitor::Visit().
Instruction* scram::mef::IfThenElse::then_instruction () const inline
Returns
The instruction to execute if the expression is true.
Definition at line 118 of file instruction.h.
Referenced by scram::mef::cycle::ContinueConnector(), scram::mef::InstructionVisitor::Visit(), and scram::mef::NullVisitor::Visit().
Instruction* scram::mef::IfThenElse::else_instruction () const inline
Returns
The instruction to execute if the expression is false. nullptr if the else instruction is optional and not set.
Definition at line 122 of file instruction.h.
Referenced by scram::mef::cycle::ContinueConnector(), scram::mef::InstructionVisitor::Visit(), and scram::mef::NullVisitor::Visit().
The documentation for this class was generated from the following file:
instruction.h