scram::core::Node Class Reference
scram::core::Node Class Reference abstract
An abstract base class that represents a node in a PDAG.
#include <pdag.h>
Public Member Functions
Node (Pdag *graph) noexcept
Creates a unique graph node as a member of a PDAG.
virtual ~Node ()=0
Abstract class.
Pdag & graph ()
int index () const
int order () const
void order (int val)
Sets the order number for this node.
int opti_value () const
void opti_value (int val)
Sets the optimization value for failure propagation.
bool Visit (int time)
Registers the visit time for this node upon graph traversal.
int EnterTime () const
int ExitTime () const
int LastVisit () const
virtual int min_time () const
virtual int max_time () const
bool Revisited () const
bool Visited () const
void ClearVisits ()
Clears all the visit information. Resets the visit times to 0s.
int pos_count () const
int neg_count () const
void AddCount (bool positive)
Increases the count of this node.
void ResetCount ()
Resets positive and negative counts of this node.
Public Member Functions inherited from scram::core::NodeParentManager
const ParentMap & parents () const
Additional Inherited Members
Public Types inherited from scram::core::NodeParentManager
using Parent = std::pair< int, GateWeakPtr >
Parent index and ptr.
using ParentMap = ext::linear_map< int, GateWeakPtr, ext::MoveEraser >
A map type of parent gate positive indices and weak pointers to them.
Detailed Description
An abstract base class that represents a node in a PDAG.
The index of the node is a unique identifier for the node. The node holds weak pointers to the parents that are managed by the parents.
Precondition
A node does not outlive its PDAG.
Definition at line 113 of file pdag.h.
Constructor & Destructor Documentation
scram::core::Node::Node (Pdag * graph) explicit noexcept
Creates a unique graph node as a member of a PDAG.
Parameters
[in] graph The graph this node belongs to.
Definition at line 48 of file pdag.cc.
References ~Node().
Member Function Documentation
Pdag& scram::core::Node::graph () inline
Returns
The host graph of the node.
Definition at line 123 of file pdag.h.
Referenced by scram::core::Gate::Clone(), and scram::core::Gate::MakeConstant().
int scram::core::Node::index () const inline
Returns
The index of this node.
Definition at line 126 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Analyze(), scram::core::Bdd::Bdd(), scram::core::Gate::Clone(), scram::core::Gate::CoalesceGate(), scram::core::Gate::EraseArg(), scram::core::Gate::EraseArgs(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Preprocessor::GateSet::insert(), scram::core::Gate::JoinNullGate(), scram::core::Gate::MakeConstant(), scram::core::operator<<(), scram::core::Gate::TransferArg(), and scram::core::Zbdd::Zbdd().
int scram::core::Node::order () const inline
Returns
Assigned order for this node.
Definition at line 129 of file pdag.h.
Referenced by scram::core::Bdd::Analyze(), scram::core::Bdd::Bdd(), scram::core::Zbdd::FindOrAddVertex(), scram::core::pdag::TopologicalOrder(), and scram::core::Zbdd::Zbdd().
void scram::core::Node::order (int val) inline
Sets the order number for this node.
The order is interpreted by the assigner.
Parameters
[in] val Positive integer.
Definition at line 135 of file pdag.h.
int scram::core::Node::opti_value () const inline
Returns
Optimization value for failure propagation.
Definition at line 138 of file pdag.h.
Referenced by scram::core::Preprocessor::PropagateState().
void scram::core::Node::opti_value (int val) inline
Sets the optimization value for failure propagation.
Parameters
[in] val Value that makes sense to the caller.
Definition at line 143 of file pdag.h.
bool scram::core::Node::Visit (int time) inline
Registers the visit time for this node upon graph traversal.
This information can be used to detect dependencies.
Parameters
[in] time The current visit time of this node. It must be positive.
Returns
true if this node was previously visited.
false if this is visited and re-visited only once.
Definition at line 153 of file pdag.h.
Referenced by scram::core::Preprocessor::GatherCommonNodes().
int scram::core::Node::EnterTime () const inline
Returns
The time when this node was first encountered or entered.
0 if no enter time is registered.
Definition at line 168 of file pdag.h.
int scram::core::Node::ExitTime () const inline
Returns
The exit time upon traversal of the graph.
0 if no exit time is registered.
Definition at line 172 of file pdag.h.
int scram::core::Node::LastVisit () const inline
Returns
The last time this node was visited.
0 if no last time is registered.
Definition at line 176 of file pdag.h.
virtual int scram::core::Node::min_time () const inline virtual
Returns
The minimum time of the visit.
0 if no time is registered.
Reimplemented in scram::core::Gate.
Definition at line 180 of file pdag.h.
virtual int scram::core::Node::max_time () const inline virtual
Returns
The maximum time of the visit.
0 if no time is registered.
Reimplemented in scram::core::Gate.
Definition at line 184 of file pdag.h.
bool scram::core::Node::Revisited () const inline
Returns
false if this node was only visited once upon graph traversal.
true if this node was revisited at least one more time.
Definition at line 188 of file pdag.h.
bool scram::core::Node::Visited () const inline
Returns
true if this node was visited at least once.
false if this node was never visited upon traversal.
Definition at line 192 of file pdag.h.
int scram::core::Node::pos_count () const inline
Returns
The positive count of this node.
Definition at line 198 of file pdag.h.
int scram::core::Node::neg_count () const inline
Returns
The negative count of this node.
Definition at line 201 of file pdag.h.
void scram::core::Node::AddCount (bool positive) inline
Increases the count of this node.
Parameters
[in] positive Indication of a positive node.
Definition at line 206 of file pdag.h.
The documentation for this class was generated from the following files:
pdag.h
pdag.cc