scram::core::RiskAnalysis Class Reference
scram::core::RiskAnalysis Class Reference
Main system that performs analyses.
#include <risk_analysis.h>
Classes
struct Context
Provides the optional context of the analysis.
struct EtaResult
The analysis results grouped by an event-tree.
struct Result
The analysis results binding to the unique analysis target.
Public Member Functions
RiskAnalysis (mef::Model *model, const Settings &settings)
const mef::Model & model () const
void Analyze () noexcept
Analyzes the model and performs computations specified in the settings.
const std::vector< Result > & results () const
const std::vector< EtaResult > & event_tree_results () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Main system that performs analyses.
Definition at line 43 of file risk_analysis.h.
Constructor & Destructor Documentation
scram::core::RiskAnalysis::RiskAnalysis (mef::Model * model, const Settings & settings)
Parameters
[in] model An analysis model with fault trees, events, etc.
[in] settings Analysis settings for the given model.
Note
The model is not const because mission time and event-tree walk context are manipulated. However, at the end of analysis, everything is reset.
Todo:
Make the analysis work with a constant model.
Definition at line 33 of file risk_analysis.cc.
Member Function Documentation
const mef::Model& scram::core::RiskAnalysis::model () const inline
Returns
The model under analysis.
Definition at line 93 of file risk_analysis.h.
References Analyze().
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::core::RiskAnalysis::Analyze () noexcept
Analyzes the model and performs computations specified in the settings.
Note
This function must be called only after full initialization of the model with or without its probabilities.
Precondition
The analysis is performed only once.
Definition at line 36 of file risk_analysis.cc.
References scram::mef::Model::alignments(), scram::mef::Model::context(), scram::core::RiskAnalysis::Result::fault_tree_analysis, scram::mef::Model::fault_trees(), scram::core::RiskAnalysis::Result::importance_analysis, scram::INFO, scram::mef::Model::initiating_events(), LOG, scram::mef::Model::mission_time(), scram::core::Settings::mission_time(), scram::mef::Element::name(), scram::core::RiskAnalysis::Result::probability_analysis, scram::mef::RandomDeviate::seed(), scram::core::Settings::seed(), scram::core::Analysis::settings(), scram::mef::HouseEvent::state(), scram::mef::Composite< Ts >::table(), scram::core::RiskAnalysis::Result::uncertainty_analysis, and scram::mef::MissionTime::value().
Referenced by model().
const std::vector<Result>& scram::core::RiskAnalysis::results () const inline
Returns
The results of the analysis.
Definition at line 106 of file risk_analysis.h.
Referenced by scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<EtaResult>& scram::core::RiskAnalysis::event_tree_results () const inline
Returns
The results of the event tree analysis.
Definition at line 109 of file risk_analysis.h.
Referenced by scram::Reporter::Report().
The documentation for this class was generated from the following files:
risk_analysis.h
risk_analysis.cc