scram::core::zbdd::CutSetContainer Class Reference
scram::core::zbdd::CutSetContainer Class Reference
Storage for generated cut sets in MOCUS.
#include <zbdd.h>
Public Member Functions
CutSetContainer (const Settings &settings, int module_index, int gate_index_bound) noexcept
Default constructor to initialize member variables.
VertexPtr ConvertGate (const Gate &gate) noexcept
Converts a PDAG gate into intermediate cut sets.
int GetNextGate () noexcept
Finds a gate in intermediate cut sets.
VertexPtr ExtractIntermediateCutSets (int index) noexcept
Extracts (removes!) intermediate cut sets containing a node with a given index.
VertexPtr ExpandGate (const VertexPtr &gate_zbdd, const VertexPtr &cut_sets) noexcept
Expands the intermediate ZBDD representation of a gate in intermediate cut sets containing the gate.
void Merge (const VertexPtr &vertex) noexcept
Merges a set of cut sets into the main container.
void EliminateComplements () noexcept
Eliminates all complements from cut sets.
void EliminateConstantModules () noexcept
Removes constant modules from cut sets.
void Minimize () noexcept
Minimizes cut sets in the container.
std::map< int, std::pair< bool, int > > GatherModules () noexcept
Gathers all module indices in the cut sets.
Public Member Functions inherited from scram::core::Zbdd
Zbdd (Bdd *bdd, const Settings &settings) noexcept
Converts Reduced Ordered BDD into Zero-Suppressed BDD.
Zbdd (const Pdag *graph, const Settings &settings) noexcept
Constructor with the analysis target.
void Analyze (const Pdag *graph=nullptr) noexcept
Runs the analysis with the representation of a PDAG as ZBDD.
const Zbdd & products () const
std::size_t size () const
bool empty () const
bool base () const
auto begin () const
auto end () const
Additional Inherited Members
Public Types inherited from scram::core::Zbdd
using VertexPtr = IntrusivePtr< Vertex< SetNode >>
ZBDD vertex base.
using TerminalPtr = IntrusivePtr< Terminal< SetNode >>
Terminal vertex.
Protected Member Functions inherited from scram::core::Zbdd
Zbdd (const Settings &settings, bool coherent=false, int module_index=0) noexcept
The common constructor to initialize member variables.
const VertexPtr & root () const
void root (const VertexPtr &vertex)
Sets a new root vertex for ZBDD.
const Settings & settings () const
const std::map< int, std::unique_ptr< Zbdd > > & modules () const
void Log () noexcept
Logs properties of the Zbdd.
SetNodePtr FindOrAddVertex (int index, const VertexPtr &high, const VertexPtr &low, int order, bool module=false, bool coherent=false) noexcept
Finds or adds a unique SetNode in the ZBDD.
SetNodePtr FindOrAddVertex (const Gate &gate, const VertexPtr &high, const VertexPtr &low) noexcept
Find or adds a ZBDD SetNode vertex using information from gates.
template<Connective Type>
VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
VertexPtr Apply (Connective type, const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
template<Connective Type>
VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Applies Boolean operation to ZBDD graph non-terminal vertices.
VertexPtr EliminateComplements (const VertexPtr &vertex, std::unordered_map< int, VertexPtr > *wide_results) noexcept
Removes complements of variables from products.
void EliminateConstantModules () noexcept
Removes constant modules from products.
VertexPtr Minimize (const VertexPtr &vertex) noexcept
Removes subsets in ZBDD.
int GatherModules (const VertexPtr &vertex, int current_order, std::map< int, std::pair< bool, int >> *modules) noexcept
Traverses ZBDD to find modules and adjusted cut-offs.
void ApplySubstitutions (const std::vector< Pdag::Substitution > &substitutions) noexcept
Applies non-declarative substitutions at the end of analysis.
void ClearTables () noexcept
Clears all memoization tables.
void Freeze () noexcept
Freezes the graph.
void JoinModule (int index, std::unique_ptr< Zbdd > container) noexcept
Joins a ZBDD representing a module gate.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND connective for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND connective for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR connective for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR connective for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
Protected Attributes inherited from scram::core::Zbdd
const TerminalPtr kBase_
Terminal Base (Unity/1) set.
const TerminalPtr kEmpty_
Terminal Empty (Null/0) set.
Detailed Description
Storage for generated cut sets in MOCUS.
The semantics is similar to a set of cut sets. The container assumes special variable ordering. Gates to be processed must be ordered to the top.
Definition at line 885 of file zbdd.h.
Constructor & Destructor Documentation
scram::core::zbdd::CutSetContainer::CutSetContainer (const Settings & settings, int module_index, int gate_index_bound) noexcept
Default constructor to initialize member variables.
Parameters
[in] settings Settings that control analysis complexity.
[in] module_index The of a module if known.
[in] gate_index_bound The exclusive lower bound for gate indices.
Precondition
No complements of gates.
Gates are indexed sequentially starting from a number larger than the lower bound.
Basic events are indexed sequentially up to a number less than or equal to the given lower bound.
Definition at line 885 of file zbdd.cc.
Member Function Documentation
Zbdd::VertexPtr scram::core::zbdd::CutSetContainer::ConvertGate (const Gate & gate) noexcept
Converts a PDAG gate into intermediate cut sets.
Parameters
[in] gate The target AND/OR gate with arguments.
Returns
The root vertex of the ZBDD representing the gate cut sets.
Definition at line 890 of file zbdd.cc.
References scram::core::Zbdd::Apply(), scram::core::Zbdd::ClearTables(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Zbdd::kBase_, scram::core::Zbdd::kEmpty_, scram::core::Settings::limit_order(), and scram::core::Zbdd::settings().
int scram::core::zbdd::CutSetContainer::GetNextGate () inline noexcept
Finds a gate in intermediate cut sets.
Returns
The index of the gate in intermediate cut sets.
0 if no gates are found.
Precondition
Variable ordering puts the gate to the top (root).
Definition at line 914 of file zbdd.h.
References scram::core::NonTerminal< T >::index(), scram::core::NonTerminal< SetNode >::index(), scram::core::NonTerminal< T >::module(), scram::core::IntrusivePtrCast< SetNode >::Ref(), scram::core::Zbdd::root(), and scram::core::Vertex< SetNode >::terminal().
Zbdd::VertexPtr scram::core::zbdd::CutSetContainer::ExtractIntermediateCutSets (int index) noexcept
Extracts (removes!) intermediate cut sets containing a node with a given index.
Parameters
[in] index The index of the gate.
Returns
The root of the ZBDD containing the intermediate cut sets.
Precondition
Variable ordering puts the gate to the top (root).
Postcondition
The extracted cut sets are pre-processed by removing the vertex with the index of the gate.
Definition at line 916 of file zbdd.cc.
References scram::DEBUG5, LOG, scram::core::IntrusivePtrCast< SetNode >::Ptr(), scram::core::IntrusivePtrCast< SetNode >::Ref(), scram::core::Zbdd::root(), and scram::core::Zbdd::settings().
Zbdd::VertexPtr scram::core::zbdd::CutSetContainer::ExpandGate (const VertexPtr & gate_zbdd, const VertexPtr & cut_sets) noexcept
Expands the intermediate ZBDD representation of a gate in intermediate cut sets containing the gate.
Parameters
[in] gate_zbdd The intermediate ZBDD of the gate.
[in] cut_sets A collection of cut sets.
Returns
The root vertex of the resulting ZBDD.
Precondition
The intermediate cut sets are pre-processed by removing the vertex with the index of the gate.
Definition at line 927 of file zbdd.cc.
References scram::core::Settings::limit_order(), scram::core::SetNode::max_set_order(), scram::core::IntrusivePtrCast< SetNode >::Ref(), and scram::core::Zbdd::settings().
void scram::core::zbdd::CutSetContainer::Merge (const VertexPtr & vertex) noexcept
Merges a set of cut sets into the main container.
Parameters
[in] vertex The root ZBDD vertex representing the cut sets.
Precondition
The argument ZBDD cut sets are managed by this container.
Definition at line 936 of file zbdd.cc.
References scram::core::Zbdd::ClearTables(), scram::core::Settings::limit_order(), scram::core::SetNode::max_set_order(), scram::core::IntrusivePtrCast< SetNode >::Ref(), scram::core::Zbdd::root(), and scram::core::Zbdd::settings().
void scram::core::zbdd::CutSetContainer::EliminateComplements () inline noexcept
Eliminates all complements from cut sets.
This can only be done if the cut set generation is certain not to have conflicts.
Precondition
The cut sets have negative literals, i.e., non-coherent.
Postcondition
Sub-modules are not processed.
Definition at line 961 of file zbdd.h.
References scram::core::Zbdd::EliminateComplements(), and scram::core::Zbdd::root().
void scram::core::zbdd::CutSetContainer::EliminateConstantModules () inline noexcept
Removes constant modules from cut sets.
Constant modules are likely to happen after complement elimination.
Precondition
All modules have been processed.
Definition at line 970 of file zbdd.h.
References scram::core::Zbdd::EliminateConstantModules().
void scram::core::zbdd::CutSetContainer::Minimize () inline noexcept
Minimizes cut sets in the container.
Postcondition
Sub-modules are not processed.
Definition at line 975 of file zbdd.h.
References scram::core::Zbdd::Minimize(), and scram::core::Zbdd::root().
std::map<int, std::pair<bool, int> > scram::core::zbdd::CutSetContainer::GatherModules () inline noexcept
Gathers all module indices in the cut sets.
Returns
An unordered map module of indices, coherence, and cut-offs.
Definition at line 980 of file zbdd.h.
References scram::core::Zbdd::GatherModules(), scram::core::NonTerminal< T >::index(), scram::core::Zbdd::JoinModule(), scram::core::Zbdd::Log(), scram::core::Zbdd::modules(), and scram::core::Zbdd::root().
The documentation for this class was generated from the following files:
zbdd.h
zbdd.cc