scram::core::ImportanceAnalysis Class Reference
scram::core::ImportanceAnalysis Class Reference abstract
Analysis of importance factors of risk model variables.
#include <importance_analysis.h>
Public Member Functions
ImportanceAnalysis (const ProbabilityAnalysis *prob_analysis)
Importance analysis on the fault tree represented by its probability analysis.
void Analyze () noexcept
Performs quantitative analysis of importance factors of basic events in products.
const std::vector< ImportanceRecord > & importance () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Analysis of importance factors of risk model variables.
Definition at line 55 of file importance_analysis.h.
Constructor & Destructor Documentation
scram::core::ImportanceAnalysis::ImportanceAnalysis (const ProbabilityAnalysis * prob_analysis) explicit
Importance analysis on the fault tree represented by its probability analysis.
Parameters
[in] prob_analysis Completed probability analysis.
Definition at line 32 of file importance_analysis.cc.
Member Function Documentation
void scram::core::ImportanceAnalysis::Analyze () noexcept
Performs quantitative analysis of importance factors of basic events in products.
Precondition
Analysis is called only once.
Definition at line 35 of file importance_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), CLOCK, scram::core::Bdd::Function::complement, scram::core::Ite::complement_edge(), scram::DEBUG3, DUR, scram::core::Ite::factor(), scram::core::NonTerminal< T >::high(), scram::core::NonTerminal< T >::index(), scram::core::Pdag::kVariableStartIndex, LOG, scram::core::NonTerminal< T >::low(), scram::core::NonTerminal< T >::mark(), scram::core::NonTerminal< T >::module(), scram::core::ImportanceFactors::occurrence, scram::core::NonTerminal< T >::order(), scram::mef::BasicEvent::p(), scram::core::Ite::p(), scram::core::IntrusivePtrCast< Ite >::Ref(), and scram::core::Bdd::Function::vertex.
const std::vector<ImportanceRecord>& scram::core::ImportanceAnalysis::importance () const inline
Returns
A collection of important events and their importance factors.
Precondition
The importance analysis is done.
Definition at line 75 of file importance_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
The documentation for this class was generated from the following files:
importance_analysis.h
importance_analysis.cc