scram::xml::Element Class Reference
scram::xml::Element Class Reference
XML Element adaptor.
#include <xml.h>
Classes
class Range
The range for elements.
Public Member Functions
Element (const xmlElement *element)
const char * filename () const
int line () const
std::string_view name () const
bool has_attribute (const char *name) const
Queries element attribute existence.
std::string_view attribute (const char *name) const
Retrieves the XML element's attribute values.
template<typename T >
std::enable_if_t< std::is_arithmetic_v< T >, std::optional< T > > attribute (const char *name) const
Generic attribute value extraction following XML data types.
std::string_view text () const
template<typename T >
std::enable_if_t< std::is_arithmetic_v< T >, T > text () const
Generic text value extraction following XML data types.
std::optional< Element > child (std::string_view name="") const
Range children () const
auto children (std::string_view name) const
Detailed Description
XML Element adaptor.
Definition at line 171 of file xml.h.
Constructor & Destructor Documentation
scram::xml::Element::Element (const xmlElement * element) inline explicit
Parameters
[in] element The element in the XML document.
Definition at line 250 of file xml.h.
Member Function Documentation
const char* scram::xml::Element::filename () const inline
Returns
The URI of the file containing the element.
Precondition
The document has been loaded from a file.
Definition at line 257 of file xml.h.
Referenced by scram::mef::Initializer::Define(), and scram::Project::Project().
int scram::xml::Element::line () const inline
Returns
The line number of the element.
Definition at line 260 of file xml.h.
Referenced by scram::mef::Initializer::Define(), scram::mef::Initializer::Initializer(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), and scram::Project::Project().
std::string_view scram::xml::Element::name () const inline
Returns
The name of the XML element.
Precondition
The element has a name.
Definition at line 265 of file xml.h.
Referenced by attribute(), children(), scram::mef::Initializer::Define(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), scram::Project::Project(), and scram::mef::Initializer::Register().
bool scram::xml::Element::has_attribute (const char * name) const inline
Queries element attribute existence.
Parameters
[in] name The non-empty attribute name.
Returns
true if the element has an attribute with the given name.
Note
This is an inefficient way to work with optional attributes. Use the attribute(name) member function directly for optionals.
Definition at line 275 of file xml.h.
Referenced by scram::mef::Initializer::Define().
std::string_view scram::xml::Element::attribute (const char * name) const inline
Retrieves the XML element's attribute values.
Parameters
[in] name The name of the requested attribute.
Returns
The attribute value or empty string if no attribute (optional attribute).
Precondition
XML attributes never contain empty strings.
XML attribute values are simple texts w/o DTD processing.
Definition at line 288 of file xml.h.
Referenced by scram::mef::Initializer::Define(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), scram::Project::Project(), and scram::mef::Initializer::Register().
template<typename T > std::enable_if_t<std::is_arithmetic_v<T>, std::optional<T> > scram::xml::Element::attribute (const char * name) const inline
Generic attribute value extraction following XML data types.
Template Parameters
T The attribute value type (numeric).
Parameters
[in] name The name of the attribute.
Returns
The value of type T interpreted from attribute value. None if the attribute doesn't exists (optional).
Exceptions
ValidityError Casting is unsuccessful.
Definition at line 310 of file xml.h.
References name().
std::string_view scram::xml::Element::text () const inline
Returns
The XML element's text.
Precondition
The Element has text.
Definition at line 327 of file xml.h.
template<typename T > std::enable_if_t<std::is_arithmetic_v<T>, T> scram::xml::Element::text () const inline
Generic text value extraction following XML data types.
Template Parameters
T The attribute value type (numeric).
Returns
The value of type T interpreted from attribute value.
Precondition
The text is not empty.
Exceptions
ValidityError Casting is unsuccessful.
Definition at line 346 of file xml.h.
std::optional<Element> scram::xml::Element::child (std::string_view name = "") const inline
Parameters
[in] name The name of the child element. Empty string to request any first child element.
Returns
The first child element (with the given name).
Definition at line 361 of file xml.h.
Referenced by scram::mef::Initializer::Define(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), scram::Project::Project(), and scram::mef::Initializer::Register().
Range scram::xml::Element::children () const inline
Returns
All the Element children.
Definition at line 370 of file xml.h.
Referenced by scram::mef::Initializer::Define(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), scram::Project::Project(), and scram::mef::Initializer::Register().
auto scram::xml::Element::children (std::string_view name) const inline
Parameters
[in] name The name to filter children elements.
Returns
The range of Element children with the given name.
Precondition
The name must live at least as long as the returned range lives.
Definition at line 377 of file xml.h.
References name().
The documentation for this class was generated from the following file:
xml.h