scram::core::EventTreeAnalysis Class Reference
scram::core::EventTreeAnalysis Class Reference
Event tree analysis functionality.
#include <event_tree_analysis.h>
Classes
struct Result
The analysis results binding to the unique analysis target.
Public Member Functions
EventTreeAnalysis (const mef::InitiatingEvent &initiating_event, const Settings &settings, mef::Context *context)
void Analyze () noexcept
Analyzes an event tree given the initiating event.
const mef::InitiatingEvent & initiating_event () const
const std::vector< Result > & sequences () const
std::vector< Result > & sequences ()
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Event tree analysis functionality.
Definition at line 37 of file event_tree_analysis.h.
Constructor & Destructor Documentation
scram::core::EventTreeAnalysis::EventTreeAnalysis (const mef::InitiatingEvent & initiating_event, const Settings & settings, mef::Context * context)
Parameters
[in] initiating_event The unique initiating event.
[in] settings The analysis settings.
[in] context The context to communicate with test-events.
Precondition
The initiating event has its event tree.
Definition at line 28 of file event_tree_analysis.cc.
References scram::mef::Formula::ArgSet::Add(), scram::mef::Formula::args(), scram::mef::Formula::connective(), scram::mef::Gate::formula(), scram::mef::Id::id(), scram::mef::Formula::max_number(), scram::mef::Formula::min_number(), scram::mef::Element::name(), and scram::mef::HouseEvent::state().
Member Function Documentation
const mef::InitiatingEvent& scram::core::EventTreeAnalysis::initiating_event () const inline
Returns
The initiating event of the event tree analysis.
Definition at line 59 of file event_tree_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and sequences().
const std::vector<Result>& scram::core::EventTreeAnalysis::sequences () const inline
Returns
The results of the event tree analysis.
Definition at line 65 of file event_tree_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and sequences().
std::vector<Result>& scram::core::EventTreeAnalysis::sequences () inline
Returns
The results of the event tree analysis.
Definition at line 66 of file event_tree_analysis.h.
References initiating_event(), and sequences().
The documentation for this class was generated from the following files:
event_tree_analysis.h
event_tree_analysis.cc