scram::mef::FaultTree Class Reference
scram::mef::FaultTree Class Reference
Fault tree representation as a container of gates, basic and house events, and other information.
#include <fault_tree.h>
Public Member Functions
FaultTree (const std::string &name)
The main constructor of the Fault Tree.
const std::vector< const Gate * > & top_events () const
void CollectTopEvents ()
Collects top event gates in this fault tree with components.
Public Member Functions inherited from scram::mef::Component
Component (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs a component assuming that it exists within some fault tree.
auto gates () const
auto basic_events () const
auto house_events () const
auto parameters () const
auto ccf_groups () const
auto components () const
void Add (Gate *element)
Adds MEF constructs into this component container.
void Add (BasicEvent *element)
Adds MEF constructs into this component container.
void Add (HouseEvent *element)
Adds MEF constructs into this component container.
void Add (CcfGroup *element)
Adds MEF constructs into this component container.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Composite< Container< Component, Component, true, false >, Container< Component, BasicEvent, false, false >, Container< Component, HouseEvent, false, false >, Container< Component, Gate, false, false >, Container< Component, Parameter, false, false >, Container< Component, CcfGroup, false, false > >
auto table () const
auto table ()
const T & Get (const typename ContainerType::key_type &id) const
Retrieves an element from the container.
T & Get (const typename ContainerType::key_type &id)
Retrieves an element from the container.
Static Public Attributes
static constexpr const char * kTypeString = "fault tree"
Type identifier string for error messages.
Static Public Attributes inherited from scram::mef::Component
static constexpr const char * kTypeString = "component/fault tree"
Type identifier string for error messages.
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Protected Member Functions inherited from scram::mef::Component
void GatherGates (std::unordered_set< Gate * > *gates)
Recursively traverses components to gather gates relevant to the whole component.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Protected Member Functions inherited from scram::mef::Composite< Container< Component, Component, true, false >, Container< Component, BasicEvent, false, false >, Container< Component, HouseEvent, false, false >, Container< Component, Gate, false, false >, Container< Component, Parameter, false, false >, Container< Component, CcfGroup, false, false > >
decltype(auto) data () const
Detailed Description
Fault tree representation as a container of gates, basic and house events, and other information.
Additional functionality of a fault tree includes detection of top events.
Definition at line 123 of file fault_tree.h.
Constructor & Destructor Documentation
scram::mef::FaultTree::FaultTree (const std::string & name) explicit
The main constructor of the Fault Tree.
Fault trees are assumed to be public and belong to the root model.
Parameters
[in] name The name identifier of this fault tree.
Definition at line 61 of file fault_tree.cc.
Member Function Documentation
const std::vector<const Gate*>& scram::mef::FaultTree::top_events () const inline
Returns
The collected top events of this fault tree.
Definition at line 135 of file fault_tree.h.
References scram::mef::Component::gates().
void scram::mef::FaultTree::CollectTopEvents ()
Collects top event gates in this fault tree with components.
This function is essential to guess the analysis targets if the user does not supply any. If the structure of the fault tree changes, this function must be called again to update the top events.
Precondition
Gate marks are clear.
Definition at line 63 of file fault_tree.cc.
References scram::mef::Formula::args(), scram::mef::Gate::formula(), scram::mef::Component::gates(), scram::mef::Component::GatherGates(), scram::mef::NodeMark::kClear, and scram::mef::NodeMark::mark().
The documentation for this class was generated from the following files:
fault_tree.h
fault_tree.cc