scram::mef::RandomDeviate Class Reference
scram::mef::RandomDeviate Class Reference
Abstract base class for all deviate expressions.
#include <random_deviate.h>
Public Member Functions
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
virtual void Validate () const
Validates the expression.
virtual double value () noexcept=0
virtual Interval interval () noexcept
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Static Public Member Functions
static void seed (unsigned seed) noexcept
Sets the seed of the underlying random number generator.
Protected Member Functions
std::mt19937 & rng ()
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Abstract base class for all deviate expressions.
These expressions provide quantification for uncertainty and sensitivity.
Note
Only single RNG is embedded for convenience. All the distributions share this RNG. This is not suitable for parallelized simulations!!!
Todo:
Parametrize with RNG (requires mef::Expression interface change).
Definition at line 42 of file random_deviate.h.
Member Function Documentation
bool scram::mef::RandomDeviate::IsDeviate () inline override virtual noexcept
Determines if the value of the expression contains deviate expressions.
The default logic is to check arguments with uncertainties for sampling. Derived expression classes must decide if they don't have arguments, or if they are random deviates.
Returns
true if the expression's value deviates from its mean.
false if the expression's value does not need sampling.
Warning
Improper registration of arguments may yield silent failure.
Reimplemented from scram::mef::Expression.
Definition at line 46 of file random_deviate.h.
static void scram::mef::RandomDeviate::seed (unsigned seed) inline static noexcept
Sets the seed of the underlying random number generator.
Parameters
[in] seed The seed for RNGs.
Note
This is static! Used by all the deriving deviates.
Definition at line 53 of file random_deviate.h.
Referenced by scram::core::RiskAnalysis::Analyze().
std::mt19937& scram::mef::RandomDeviate::rng () inline protected
Returns
RNG to be used by derived classes.
Definition at line 57 of file random_deviate.h.
Referenced by scram::mef::GammaDeviate::interval(), scram::mef::BetaDeviate::interval(), scram::mef::LognormalDeviate::LognormalDeviate(), scram::mef::UniformDeviate::Validate(), scram::mef::NormalDeviate::Validate(), and scram::mef::Histogram::value().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc