scram::mef::BetaDeviate Class Reference
scram::mef::BetaDeviate Class Reference
Beta distribution.
#include <random_deviate.h>
Public Member Functions
BetaDeviate (Expression *alpha, Expression *beta)
Setup for Beta distribution.
void Validate () const override
double value () noexceptoverride
Interval interval () noexceptoverride
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Static Public Member Functions inherited from scram::mef::RandomDeviate
static void seed (unsigned seed) noexcept
Sets the seed of the underlying random number generator.
Protected Member Functions inherited from scram::mef::RandomDeviate
std::mt19937 & rng ()
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Beta distribution.
Definition at line 220 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::BetaDeviate::BetaDeviate (Expression * alpha, Expression * beta)
Setup for Beta distribution.
Parameters
[in] alpha Alpha shape parameter of Gamma distribution.
[in] beta Beta shape parameter of Gamma distribution.
Definition at line 147 of file random_deviate.cc.
Member Function Documentation
void scram::mef::BetaDeviate::Validate () const override virtual
Exceptions
DomainError (alpha <= 0) or (beta <= 0)
Reimplemented from scram::mef::Expression.
Definition at line 150 of file random_deviate.cc.
References SCRAM_THROW, and scram::mef::Expression::value().
double scram::mef::BetaDeviate::value () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 231 of file random_deviate.h.
References scram::mef::Expression::interval().
Interval scram::mef::BetaDeviate::interval () override virtual noexcept
Returns
99 percentile.
Reimplemented from scram::mef::Expression.
Definition at line 162 of file random_deviate.cc.
References scram::mef::RandomDeviate::rng(), and scram::mef::Expression::value().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc