ext::linear_map< Key, Value, ErasePolicy, Sequence > Class Template Reference
ext::linear_map< Key, Value, ErasePolicy, Sequence > Class Template Reference
An adaptor map with lookup complexity O(N) based on sequence (contiguous structure by default).
#include <linear_map.h>
Public Types
using key_type = Key
Public typedefs.
using mapped_type = Value
Public typedefs.
using value_type = std::pair< key_type, mapped_type >
Public typedefs.
using container_type = Sequence< value_type >
Public typedefs.
using pointer = typename container_type::pointer
Iterator-related typedefs redeclared from the underlying container type.
using const_pointer = typename container_type::const_pointer
Iterator-related typedefs redeclared from the underlying container type.
using reference = typename container_type::reference
Iterator-related typedefs redeclared from the underlying container type.
using const_reference = typename container_type::const_reference
Iterator-related typedefs redeclared from the underlying container type.
using iterator = typename container_type::iterator
Iterator-related typedefs redeclared from the underlying container type.
using const_iterator = typename container_type::const_iterator
Iterator-related typedefs redeclared from the underlying container type.
using reverse_iterator = typename container_type::reverse_iterator
Iterator-related typedefs redeclared from the underlying container type.
using const_reverse_iterator = typename container_type::const_reverse_iterator
Iterator-related typedefs redeclared from the underlying container type.
using size_type = typename container_type::size_type
Iterator-related typedefs redeclared from the underlying container type.
using difference_type = typename container_type::difference_type
Iterator-related typedefs redeclared from the underlying container type.
Public Member Functions
size_type count (const key_type &key) const
Determines if an entry with the given key in the map.
template<typename Iterator >
void insert (Iterator first1, Iterator last1)
Inserts a range of elements.
template<typename... Ts>
std::pair< iterator, bool > emplace (Ts &&...args)
Attempts to build and insert an entry.
size_type erase (const key_type &key)
Erases the entry with a key.
void swap (linear_map &other) noexcept
Swaps data with another linear map.
size_type size () const
bool empty () const
void clear () noexcept
Erases all entries in the map.
void reserve (size_type n)
Prepares the linear map for a specified number of entries.
size_type capacity () const
iterator begin ()
iterator end ()
linear_map ()=default
Standard constructors (copy and move are implicit).
linear_map (std::initializer_list< value_type > init_list)
Standard constructors (copy and move are implicit).
template<typename Iterator >
linear_map (Iterator first1, Iterator last1)
Standard constructors (copy and move are implicit).
const_iterator find (const key_type &key) const
Finds an entry in the map.
iterator find (const key_type &key)
Finds an entry in the map.
mapped_type & operator[] (const key_type &key)
Accesses an existing or default constructed entry.
mapped_type & operator[] (key_type &&key)
Accesses an existing or default constructed entry.
const mapped_type & at (const key_type &key) const
Accesses the value of the entry.
mapped_type & at (const key_type &key)
Accesses the value of the entry.
std::pair< iterator, bool > insert (const value_type &p)
Inserts a key-value pair into the map if the pair is not in the map.
std::pair< iterator, bool > insert (value_type &&p)
Inserts a key-value pair into the map if the pair is not in the map.
iterator erase (const_iterator pos)
Erases the entry pointed by an iterator.
iterator erase (iterator pos)
Erases the entry pointed by an iterator.
container_type & data ()
const container_type & data () const
const_iterator cbegin () const
const_iterator begin () const
const_iterator cend () const
const_iterator end () const
reverse_iterator rbegin ()
Corresponding reverse iterators.
reverse_iterator rend ()
Corresponding reverse iterators.
const_reverse_iterator crbegin () const
Corresponding reverse iterators.
const_reverse_iterator rbegin () const
Corresponding reverse iterators.
const_reverse_iterator crend () const
Corresponding reverse iterators.
const_reverse_iterator rend () const
Corresponding reverse iterators.
Friends
void swap (linear_map &lhs, linear_map &rhs) noexcept
Friend swap definition for convenience sake.
bool operator== (const linear_map &lhs, const linear_map &rhs)
Non-member equality test operators.
bool operator!= (const linear_map &lhs, const linear_map &rhs)
Non-member equality test operators.
Detailed Description
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector>
class ext::linear_map< Key, Value, ErasePolicy, Sequence >
An adaptor map with lookup complexity O(N) based on sequence (contiguous structure by default).
This map is designed for a small number of elements and for small <Key, Value> size pairs. Consider this class a convenient wrapper around std::vector<std::pair<Key, Value>>.
Since this map is based on the vector by default, the order of insertions is preserved, and it provides random access iterators.
The major differences from the standard library maps:
The entry is std::pair<Key, Value> instead of std::pair<const Key, Value>, which means that the key can be modified as long as it stays unique.
Iterators, references, pointers can be invalidated by modifier functions (insert, erase, reserve, etc.). This is the inherited behavior from std::vector.
Some API may be extra or missing.
The performance of the map critically depends on the number of entries, the size of the key-value pair, and the cost of comparing keys for equality. The advantage of the linear_map comes from cache-friendliness, and fewer CPU front-end and back-end stalls.
From crude experimental results with random entries comparing with std::map, std::unordered_map, boost::flat_map:
For Key=int, Value=Object, sizeof(Object)=24, the linear_map outperforms up to 50 entries.
For Key=std::string(20 char), Value=Object, sizeof(Object)=24, the linear_map performs equally well up to 10 entries.
Template Parameters
Key The type of the unique keys.
Value The type of the values associated with the keys.
ErasePolicy The policy class that provides erase(it, *container) static member function to control the element erasure from the container.
Sequence The underlying container type.
Definition at line 133 of file linear_map.h.
Member Function Documentation
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const_iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::find (const key_type & key) const inline
Finds an entry in the map.
Parameters
[in] key The key of the entry.
Returns
Iterator pointing to the entry, or end() if not found.
Definition at line 206 of file linear_map.h.
Referenced by ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::at(), ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::count(), ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::erase(), ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::insert(), and ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::operator[]().
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::find (const key_type & key) inline
Finds an entry in the map.
Parameters
[in] key The key of the entry.
Returns
Iterator pointing to the entry, or end() if not found.
Definition at line 211 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> size_type ext::linear_map< Key, Value, ErasePolicy, Sequence >::count (const key_type & key) const inline
Determines if an entry with the given key in the map.
Parameters
[in] key The key of the entry.
Returns
1 if there's an entry, 0 otherwise.
Definition at line 223 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> mapped_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::operator[] (const key_type & key) inline
Accesses an existing or default constructed entry.
Parameters
[in] key The key of the entry.
Returns
A reference to the value of the entry.
Definition at line 234 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> mapped_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::operator[] (key_type && key) inline
Accesses an existing or default constructed entry.
Parameters
[in] key The key of the entry.
Returns
A reference to the value of the entry.
Definition at line 242 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const mapped_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::at (const key_type & key) const inline
Accesses the value of the entry.
Parameters
[in] key The key of the entry.
Returns
The reference to the value.
Exceptions
std::out_of_range The entry is not in the map.
Definition at line 260 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> mapped_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::at (const key_type & key) inline
Accesses the value of the entry.
Parameters
[in] key The key of the entry.
Returns
The reference to the value.
Exceptions
std::out_of_range The entry is not in the map.
Definition at line 267 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> std::pair<iterator, bool> ext::linear_map< Key, Value, ErasePolicy, Sequence >::insert (const value_type & p) inline
Inserts a key-value pair into the map if the pair is not in the map.
Parameters
[in] p The entry.
Returns
A pair of an iterator and insertion flag. The iterator points to possibly inserted entry, and the flag indicates whether the entry is actually inserted.
Definition at line 281 of file linear_map.h.
Referenced by ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::emplace(), and ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::linear_map().
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> std::pair<iterator, bool> ext::linear_map< Key, Value, ErasePolicy, Sequence >::insert (value_type && p) inline
Inserts a key-value pair into the map if the pair is not in the map.
Parameters
[in] p The entry.
Returns
A pair of an iterator and insertion flag. The iterator points to possibly inserted entry, and the flag indicates whether the entry is actually inserted.
Definition at line 289 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> template<typename Iterator > void ext::linear_map< Key, Value, ErasePolicy, Sequence >::insert (Iterator first1, Iterator last1) inline
Inserts a range of elements.
The range is not assumed to be unique.
Template Parameters
Iterator Iterator to the container with key-value pairs.
Parameters
[in] first1 The beginning of the range.
[in] last1 The end of the range.
Definition at line 306 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> template<typename... Ts> std::pair<iterator, bool> ext::linear_map< Key, Value, ErasePolicy, Sequence >::emplace (Ts &&... args) inline
Attempts to build and insert an entry.
Parameters
[in] args Arguments for the construction of the entry.
Returns
An iterator pointing to the entry, and a flag indicating if the insertion actually happened.
Definition at line 320 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::erase (const_iterator pos) inline
Erases the entry pointed by an iterator.
Parameters
[in] pos An iterator pointing to the entry.
Returns
An iterator pointing after the entry.
Definition at line 331 of file linear_map.h.
Referenced by ext::linear_map< int, GateWeakPtr, ext::MoveEraser >::erase().
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::erase (iterator pos) inline
Erases the entry pointed by an iterator.
Parameters
[in] pos An iterator pointing to the entry.
Returns
An iterator pointing after the entry.
Definition at line 332 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> size_type ext::linear_map< Key, Value, ErasePolicy, Sequence >::erase (const key_type & key) inline
Erases the entry with a key.
Parameters
[in] key The key of the entry.
Returns
1 if the existing entry has been removed, 0 if there's no entry with the given key.
Definition at line 341 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> void ext::linear_map< Key, Value, ErasePolicy, Sequence >::swap (linear_map< Key, Value, ErasePolicy, Sequence > & other) inline noexcept
Swaps data with another linear map.
Parameters
[in] other Another linear map.
Definition at line 352 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> size_type ext::linear_map< Key, Value, ErasePolicy, Sequence >::size () const inline
Returns
The number of entries in the map.
Definition at line 355 of file linear_map.h.
Referenced by scram::core::Bdd::Analyze(), and scram::core::Zbdd::FindOrAddVertex().
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> bool ext::linear_map< Key, Value, ErasePolicy, Sequence >::empty () const inline
Returns
true if there are no entries.
Definition at line 358 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> void ext::linear_map< Key, Value, ErasePolicy, Sequence >::reserve (size_type n) inline
Prepares the linear map for a specified number of entries.
Parameters
[in] n The number of expected entries.
Definition at line 366 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> size_type ext::linear_map< Key, Value, ErasePolicy, Sequence >::capacity () const inline
Returns
The capacity of the underlying container.
Definition at line 369 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> container_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::data () inline
Returns
The underlying data container. The container elements are ordered exactly as inserted.
Definition at line 374 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const container_type& ext::linear_map< Key, Value, ErasePolicy, Sequence >::data () const inline
Returns
The underlying data container. The container elements are ordered exactly as inserted.
Definition at line 375 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::begin () inline
Returns
A read/write iterator pointing to the first entry.
Definition at line 379 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::end () inline
Returns
A read/write iterator pointing one past the last entry.
Definition at line 381 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const_iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::cbegin () const inline
Returns
A read-only iterator pointing to the first entry.
Definition at line 386 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const_iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::begin () const inline
Returns
A read-only iterator pointing to the first entry.
Definition at line 387 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const_iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::cend () const inline
Returns
A read-only iterator pointing one past the last entry.
Definition at line 393 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> const_iterator ext::linear_map< Key, Value, ErasePolicy, Sequence >::end () const inline
Returns
A read-only iterator pointing one past the last entry.
Definition at line 394 of file linear_map.h.
Friends And Related Function Documentation
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> bool operator== (const linear_map< Key, Value, ErasePolicy, Sequence > & lhs, const linear_map< Key, Value, ErasePolicy, Sequence > & rhs) friend
Non-member equality test operators.
The complexity is O(N^2).
Parameters
[in] lhs First map.
[in] rhs Second map.
Note
The order of elements is not relevant. If the order matters for equality, compare the underlying data containers directly.
Definition at line 145 of file linear_map.h.
template<typename Key, typename Value, class ErasePolicy = DefaultEraser, template< typename... > class Sequence = std::vector> bool operator!= (const linear_map< Key, Value, ErasePolicy, Sequence > & lhs, const linear_map< Key, Value, ErasePolicy, Sequence > & rhs) friend
Non-member equality test operators.
The complexity is O(N^2).
Parameters
[in] lhs First map.
[in] rhs Second map.
Note
The order of elements is not relevant. If the order matters for equality, compare the underlying data containers directly.
Definition at line 154 of file linear_map.h.
The documentation for this class was generated from the following file:
linear_map.h