scram::core::Ite Class Reference
scram::core::Ite Class Reference
Representation of non-terminal if-then-else vertices in BDD graphs.
#include <bdd.h>
Public Member Functions
bool complement_edge () const
void complement_edge (bool flag)
Sets the complement flag for the low edge.
double p () const
void p (double value)
Sets the probability of the function graph.
double factor () const
void factor (double value)
Memorized results of importance factor calculations.
Public Member Functions inherited from scram::core::NonTerminal< Ite >
NonTerminal (int index, int order, int id, const VertexPtr &high, const VertexPtr &low)
int index () const
int order () const
bool module () const
void module (bool flag)
Sets this vertex for representation of a module.
bool coherent () const
void coherent (bool flag)
Sets the flag for coherent modules.
const VertexPtr & high () const
const VertexPtr & low () const
bool mark () const
void mark (bool flag)
Marks this vertex.
Public Member Functions inherited from scram::core::Vertex< Ite >
Vertex (int id)
int id () const
bool terminal () const
int use_count () const
bool unique () const
Friends
int get_low_id (const Ite &ite) noexcept
Special handling of the complement flag in computing low id signature.
Additional Inherited Members
Static Public Member Functions inherited from scram::core::IntrusivePtrCast< Ite >
static IntrusivePtr< Ite > Ptr (const IntrusivePtr< Vertex< Ite >> &vertex)
static Ite & Ref (const IntrusivePtr< Vertex< Ite >> &vertex)
Protected Member Functions inherited from scram::core::Vertex< Ite >
~Vertex () noexcept
Communicates the destruction via the pointer to the unique table entry if there's any.
Detailed Description
Representation of non-terminal if-then-else vertices in BDD graphs.
This class is designed to help construct and manipulate BDD graphs.
This class provides one attributed complement edge. The attributed edge applies to the low/false/0 branch of the vertex. However, there is no logic to check if the complement edge manipulations are valid. Consistency is the responsibility of BDD algorithms and users.
Definition at line 327 of file bdd.h.
Member Function Documentation
bool scram::core::Ite::complement_edge () const inline
Returns
true if the low edge is complement.
Definition at line 341 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), and scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability().
void scram::core::Ite::complement_edge (bool flag) inline
Sets the complement flag for the low edge.
Parameters
[in] flag Indicator to treat the low branch as a complement.
Definition at line 346 of file bdd.h.
double scram::core::Ite::p () const inline
Returns
The probability of the function graph.
Definition at line 349 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), and scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability().
void scram::core::Ite::p (double value) inline
Sets the probability of the function graph.
Parameters
[in] value Calculated value for the probability.
Definition at line 354 of file bdd.h.
double scram::core::Ite::factor () const inline
Returns
Saved results of importance factor calculations.
Definition at line 357 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze().
void scram::core::Ite::factor (double value) inline
Memorized results of importance factor calculations.
Parameters
[in] value Calculation results for importance factor.
Definition at line 362 of file bdd.h.
Friends And Related Function Documentation
int get_low_id (const Ite & ite) friend
Special handling of the complement flag in computing low id signature.
Parameters
[in] ite Ite vertex.
Returns
The signed number for complement low id.
Definition at line 333 of file bdd.h.
The documentation for this class was generated from the following file:
bdd.h