scram::mef::Id Class Reference
scram::mef::Id Class Reference
Mixin class for assigning unique identifiers to elements.
#include <element.h>
Public Member Functions
Id (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs an element with an original name.
const std::string & id () const
std::string_view id_view () const
std::string_view full_path () const
void id (std::string name)
Resets the element ID.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Static Public Member Functions
static const std::string & unique_name (const Element &element)
Produces unique name for the model element within the same type.
static const std::string & unique_name (const Id &element)
Produces unique name for the model element within the same type.
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Detailed Description
Mixin class for assigning unique identifiers to elements.
Definition at line 306 of file element.h.
Constructor & Destructor Documentation
scram::mef::Id::Id (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Constructs an element with an original name.
The name is expected to conform to identifier requirements described in the MEF documentation and additions.
Parameters
[in] name The local identifier name.
Exceptions
LogicError The name is required and empty.
ValidityError The name is malformed. Sets the role of an element upon creation. The base reference path must be formatted according to the MEF documentation and additions.
Parameters
[in] role A role specifier of the element.
[in] base_path The series of containers to get this event.
Exceptions
ValidityError The base path string is malformed.
ValidityError Private element at model/global scope.
Mangles the element name into a unique id. Private elements get their full path as their ids, while public elements retain their name as ids.
Definition at line 77 of file element.cc.
References scram::mef::GetFullPath().
Member Function Documentation
const std::string& scram::mef::Id::id () const inline
Returns
The unique id that is set upon the construction of this element.
Definition at line 318 of file element.h.
References scram::mef::Element::name(), and scram::mef::Role::role().
Referenced by scram::mef::Substitution::Add(), scram::mef::Formula::ArgSet::Add(), scram::mef::Initializer::Define(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::mef::Formula::Swap(), and unique_name().
std::string_view scram::mef::Id::id_view () const inline
Returns
The string view to the id to be used as a table key.
Definition at line 324 of file element.h.
std::string_view scram::mef::Id::full_path () const inline
Returns
The string view to the unique full path for a table key.
Definition at line 327 of file element.h.
Referenced by scram::mef::Initializer::model().
void scram::mef::Id::id (std::string name)
Resets the element ID.
Parameters
[in] name The new valid name for the element.
Precondition
The element is not in any container keyed by its ID or name.
Exceptions
LogicError The name is empty.
ValidityError The name is malformed.
Definition at line 82 of file element.cc.
References scram::mef::GetFullPath(), and scram::mef::Element::name().
The documentation for this class was generated from the following files:
element.h
element.cc