scram::core::ProductContainer Class Reference
scram::core::ProductContainer Class Reference
A container of analysis result products with Literals.
#include <fault_tree_analysis.h>
Public Member Functions
ProductContainer (const Zbdd &products, const Pdag &graph) noexcept
The constructor also collects basic events in products.
const std::unordered_set< const mef::BasicEvent * > & product_events () const
bool empty () const
int size () const
const std::vector< int > & distribution () const
auto begin () const
Begin and end iterators over products in the container.
auto end () const
Begin and end iterators over products in the container.
Detailed Description
A container of analysis result products with Literals.
This is a wrapper of the analysis resultant ZBDD to work with Literals.
Definition at line 109 of file fault_tree_analysis.h.
Constructor & Destructor Documentation
scram::core::ProductContainer::ProductContainer (const Zbdd & products, const Pdag & graph) noexcept
The constructor also collects basic events in products.
Parameters
[in] products Sets with indices of events from calculations.
[in] graph PDAG with basic event indices and pointers.
Definition at line 86 of file fault_tree_analysis.cc.
Member Function Documentation
const std::unordered_set<const mef::BasicEvent*>& scram::core::ProductContainer::product_events () const inline
Returns
Collection of basic events that are in the products.
Definition at line 129 of file fault_tree_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
bool scram::core::ProductContainer::empty () const inline
Returns
true if no products in the container.
Definition at line 146 of file fault_tree_analysis.h.
Referenced by scram::core::Print(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
int scram::core::ProductContainer::size () const inline
Returns
The number of products in the container.
Definition at line 149 of file fault_tree_analysis.h.
Referenced by scram::core::Print(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<int>& scram::core::ProductContainer::distribution () const inline
Returns
The product distribution by order.
Definition at line 152 of file fault_tree_analysis.h.
References scram::core::Print().
Referenced by scram::core::Print(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
The documentation for this class was generated from the following files:
fault_tree_analysis.h
fault_tree_analysis.cc