scram::mef::Component Class Reference
scram::mef::Component Class Reference
Component is for logical grouping of events, gates, and other components.
#include <fault_tree.h>
Public Member Functions
Component (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs a component assuming that it exists within some fault tree.
auto gates () const
auto basic_events () const
auto house_events () const
auto parameters () const
auto ccf_groups () const
auto components () const
void Add (Gate *element)
Adds MEF constructs into this component container.
void Add (BasicEvent *element)
Adds MEF constructs into this component container.
void Add (HouseEvent *element)
Adds MEF constructs into this component container.
void Add (CcfGroup *element)
Adds MEF constructs into this component container.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Composite< Container< Component, Component, true, false >, Container< Component, BasicEvent, false, false >, Container< Component, HouseEvent, false, false >, Container< Component, Gate, false, false >, Container< Component, Parameter, false, false >, Container< Component, CcfGroup, false, false > >
auto table () const
auto table ()
const T & Get (const typename ContainerType::key_type &id) const
Retrieves an element from the container.
T & Get (const typename ContainerType::key_type &id)
Retrieves an element from the container.
Static Public Attributes
static constexpr const char * kTypeString = "component/fault tree"
Type identifier string for error messages.
Protected Member Functions
void GatherGates (std::unordered_set< Gate * > *gates)
Recursively traverses components to gather gates relevant to the whole component.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Protected Member Functions inherited from scram::mef::Composite< Container< Component, Component, true, false >, Container< Component, BasicEvent, false, false >, Container< Component, HouseEvent, false, false >, Container< Component, Gate, false, false >, Container< Component, Parameter, false, false >, Container< Component, CcfGroup, false, false > >
decltype(auto) data () const
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Detailed Description
Component is for logical grouping of events, gates, and other components.
Definition at line 36 of file fault_tree.h.
Constructor & Destructor Documentation
scram::mef::Component::Component (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Constructs a component assuming that it exists within some fault tree.
The public or private role of a component is not for the components itself, but for the events and parameters of the component. Component name is not meant to be public; however, it must be unique within the parent fault tree or component.
Parameters
[in] name The name identifier for the component.
[in] base_path The series of containers to get this container.
[in] role The default role for container members.
Exceptions
LogicError The name is empty.
ValidityError The name or reference paths are malformed.
Definition at line 27 of file fault_tree.cc.
Member Function Documentation
auto scram::mef::Component::gates () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 71 of file fault_tree.h.
Referenced by Add(), scram::mef::FaultTree::CollectTopEvents(), GatherGates(), scram::mef::Serialize(), and scram::mef::FaultTree::top_events().
auto scram::mef::Component::basic_events () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 72 of file fault_tree.h.
Referenced by GatherGates().
auto scram::mef::Component::house_events () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 73 of file fault_tree.h.
Referenced by GatherGates().
auto scram::mef::Component::parameters () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 74 of file fault_tree.h.
auto scram::mef::Component::ccf_groups () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 75 of file fault_tree.h.
Referenced by Add().
auto scram::mef::Component::components () const inline
Returns
The table ranges of component elements of specific kind with element original names as keys.
Definition at line 76 of file fault_tree.h.
Referenced by scram::mef::Serialize().
void scram::mef::Component::Add (Gate * element) inline
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
DuplicateElementError The element is already in this container.
Definition at line 89 of file fault_tree.h.
Referenced by Add(), and scram::mef::Initializer::Define().
void scram::mef::Component::Add (BasicEvent * element) inline
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
DuplicateElementError The element is already in this container.
Definition at line 90 of file fault_tree.h.
void scram::mef::Component::Add (HouseEvent * element) inline
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
DuplicateElementError The element is already in this container.
Definition at line 91 of file fault_tree.h.
References Add(), gates(), and GatherGates().
void scram::mef::Component::Add (CcfGroup * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
DuplicateElementError The element is already in this container.
Definition at line 31 of file fault_tree.cc.
References ccf_groups(), scram::mef::CcfGroup::members(), scram::mef::Element::name(), and SCRAM_THROW.
void scram::mef::Component::GatherGates (std::unordered_set< Gate * > * gates) protected
Recursively traverses components to gather gates relevant to the whole component.
Parameters
[out] gates Gates belonging to this component and its subcomponents.
Definition at line 45 of file fault_tree.cc.
References basic_events(), begin, end, gates(), house_events(), kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
Referenced by Add(), and scram::mef::FaultTree::CollectTopEvents().
The documentation for this class was generated from the following files:
fault_tree.h
fault_tree.cc