scram::core::Mocus Class Reference
scram::core::Mocus Class Reference
This class analyzes normalized, preprocessed, and indexed fault trees to generate minimal cut sets with the MOCUS algorithm.
#include <mocus.h>
Public Member Functions
Mocus (const Pdag *graph, const Settings &settings)
Prepares a PDAG for analysis with the MOCUS algorithm.
void Analyze (const Pdag *graph=nullptr) noexcept
Finds minimal cut sets from the PDAG.
const Zbdd & products () const
Detailed Description
This class analyzes normalized, preprocessed, and indexed fault trees to generate minimal cut sets with the MOCUS algorithm.
Definition at line 41 of file mocus.h.
Constructor & Destructor Documentation
scram::core::Mocus::Mocus (const Pdag * graph, const Settings & settings)
Prepares a PDAG for analysis with the MOCUS algorithm.
Parameters
[in] graph Preprocessed and normalized PDAG.
[in] settings The analysis settings.
Precondition
The passed PDAG already has variable ordering.
The PDAG is in negation normal form; that is, it contains only positive AND/OR gates.
Definition at line 34 of file mocus.cc.
References scram::core::Pdag::complement().
Member Function Documentation
void scram::core::Mocus::Analyze (const Pdag * graph = nullptr) noexcept
Finds minimal cut sets from the PDAG.
Parameters
[in] graph The optional PDAG with non-declarative substitutions.
Definition at line 39 of file mocus.cc.
References scram::core::Gate::args(), scram::core::Pdag::basic_events(), CLOCK, scram::core::Gate::coherent(), scram::DEBUG2, scram::DEBUG3, scram::DEBUG4, scram::DEBUG5, DUR, gates, scram::core::Node::index(), scram::core::Pdag::IsTrivial(), scram::core::Pdag::kVariableStartIndex, scram::core::Settings::limit_order(), LOG, scram::core::Gate::module(), scram::core::Pdag::root(), and TIMER.
const Zbdd& scram::core::Mocus::products () const inline
Returns
Generated minimal cut sets with basic event indices.
Definition at line 59 of file mocus.h.
The documentation for this class was generated from the following files:
mocus.h
mocus.cc