scram::xml::Validator Class Reference
scram::xml::Validator Class Reference
RelaxNG validator.
#include <xml.h>
Public Member Functions
Validator (const std::string &rng_file)
void validate (const Document &doc)
Validates XML DOM documents against the schema.
Detailed Description
RelaxNG validator.
Definition at line 437 of file xml.h.
Constructor & Destructor Documentation
scram::xml::Validator::Validator (const std::string & rng_file) explicit
Parameters
[in] rng_file The path to the schema file.
Exceptions
ParseError RNG file parsing has failed.
LogicError The XML library functions have failed internally.
Definition at line 47 of file xml.cc.
References SCRAM_THROW.
Member Function Documentation
void scram::xml::Validator::validate (const Document & doc) inline
Validates XML DOM documents against the schema.
Parameters
[in] doc The initialized XML DOM document.
Exceptions
ValidityError The document failed schema validation.
Definition at line 450 of file xml.h.
References scram::xml::Document::get(), and SCRAM_THROW.
Referenced by scram::xml::Document::Document(), scram::mef::Initializer::Initializer(), and scram::Project::Project().
The documentation for this class was generated from the following files:
xml.h
xml.cc