scram::mef::Histogram Class Reference
scram::mef::Histogram Class Reference
Histogram distribution.
#include <random_deviate.h>
Public Member Functions
Histogram (std::vector< Expression * > boundaries, std::vector< Expression * > weights)
Histogram distribution setup.
void Validate () const override
double value () noexceptoverride
Interval interval () noexceptoverride
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Static Public Member Functions inherited from scram::mef::RandomDeviate
static void seed (unsigned seed) noexcept
Sets the seed of the underlying random number generator.
Protected Member Functions inherited from scram::mef::RandomDeviate
std::mt19937 & rng ()
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Histogram distribution.
Definition at line 247 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::Histogram::Histogram (std::vector< Expression * > boundaries, std::vector< Expression * > weights)
Histogram distribution setup.
Parameters
[in] boundaries The bounds of intervals.
[in] weights The positive weights of intervals restricted by the upper boundaries. Therefore, the number of weights must be equal to the number of intervals.
Exceptions
ValidityError The boundaries container size is not equal to weights container size + 1.
Definition at line 173 of file random_deviate.cc.
References scram::mef::Expression::AddArg(), scram::mef::Expression::args(), begin, end, and SCRAM_THROW.
Member Function Documentation
void scram::mef::Histogram::Validate () const override virtual
Exceptions
ValidityError The boundaries are not strictly increasing, or weights are negative.
Reimplemented from scram::mef::Expression.
Definition at line 191 of file random_deviate.cc.
References SCRAM_THROW.
double scram::mef::Histogram::value () override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 203 of file random_deviate.cc.
References scram::mef::RandomDeviate::rng(), and scram::mef::Expression::value().
Interval scram::mef::Histogram::interval () inline override virtual noexcept
Returns
The domain interval for validation purposes only.
Reimplemented from scram::mef::Expression.
Definition at line 267 of file random_deviate.h.
References scram::mef::Expression::value().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc