scram::core::ProbabilityAnalyzer< Bdd > Class Template Reference
scram::core::ProbabilityAnalyzer< Bdd > Class Template Reference
Specialization of probability analyzer with Binary Decision Diagrams.
#include <probability_analysis.h>
Public Member Functions
template<class Algorithm >
ProbabilityAnalyzer (const FaultTreeAnalyzer< Algorithm > *fta, mef::MissionTime *mission_time)
Constructs probability analyzer from a fault tree analyzer with the same algorithm.
ProbabilityAnalyzer (FaultTreeAnalyzer< Bdd > *fta, mef::MissionTime *mission_time)
Reuses BDD structures from Fault tree analyzer.
~ProbabilityAnalyzer () noexcept
Deletes the PDAG and BDD only if ProbabilityAnalyzer is the owner of them.
Bdd * bdd_graph ()
double CalculateTotalProbability (const Pdag::IndexMap< double > &p_vars) noexceptfinal
Calculates the total probability with a different set of probability values than the one given upon construction.
Public Member Functions inherited from scram::core::ProbabilityAnalyzerBase
template<class Algorithm >
ProbabilityAnalyzerBase (const FaultTreeAnalyzer< Algorithm > *fta, mef::MissionTime *mission_time)
Constructs probability analyzer from a fault tree analyzer.
const Pdag * graph () const
const Zbdd & products () const
const Pdag::IndexMap< double > & p_vars () const
Public Member Functions inherited from scram::core::ProbabilityAnalysis
ProbabilityAnalysis (const FaultTreeAnalysis *fta, mef::MissionTime *mission_time)
Probability analysis with the results of qualitative analysis.
void Analyze () noexcept
Performs quantitative analysis on the supplied fault tree.
double p_total () const
const std::vector< std::pair< double, double > > & p_time () const
const Sil & sil () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::ProbabilityAnalysis
mef::MissionTime & mission_time ()
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
template<>
class scram::core::ProbabilityAnalyzer< Bdd >
Specialization of probability analyzer with Binary Decision Diagrams.
The quantitative analysis is done with BDD.
Definition at line 267 of file probability_analysis.h.
Constructor & Destructor Documentation
template<class Algorithm > scram::core::ProbabilityAnalyzer< Bdd >::ProbabilityAnalyzer (const FaultTreeAnalyzer< Algorithm > * fta, mef::MissionTime * mission_time) inline
Constructs probability analyzer from a fault tree analyzer with the same algorithm.
Template Parameters
Algorithm Fault tree analysis algorithm.
Parameters
[in] fta Fault tree analysis with results.
[in] mission_time The mission time expression of the model.
Precondition
The underlying fault tree must not have changed in any way since the fault tree analysis finished.
Definition at line 276 of file probability_analysis.h.
scram::core::ProbabilityAnalyzer< Bdd >::ProbabilityAnalyzer (FaultTreeAnalyzer< Bdd > * fta, mef::MissionTime * mission_time)
Reuses BDD structures from Fault tree analyzer.
Parameters
[in] fta Fault tree analysis with results.
[in] mission_time The mission time expression of the model.
Precondition
The underlying fault tree must not have changed in any way since the fault tree analysis finished.
BDD is fully formed and used.
Postcondition
FaultTreeAnalyzer is not corrupted by use of its BDD internals.
Definition at line 219 of file probability_analysis.cc.
References scram::core::FaultTreeAnalyzer< Algorithm >::algorithm(), scram::DEBUG2, LOG, scram::core::NonTerminal< T >::mark(), and scram::core::IntrusivePtrCast< Ite >::Ref().
scram::core::ProbabilityAnalyzer< Bdd >::~ProbabilityAnalyzer () noexcept
Deletes the PDAG and BDD only if ProbabilityAnalyzer is the owner of them.
Definition at line 228 of file probability_analysis.cc.
Member Function Documentation
Bdd* scram::core::ProbabilityAnalyzer< Bdd >::bdd_graph () inline
Returns
Binary decision diagram used for calculations.
Definition at line 300 of file probability_analysis.h.
double scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability (const Pdag::IndexMap< double > & p_vars) final virtual noexcept
Calculates the total probability with a different set of probability values than the one given upon construction.
Parameters
[in] p_vars A map of probabilities of the graph variables. The indices of the variables must map exactly to the values.
Returns
The total probability calculated with the given values.
Implements scram::core::ProbabilityAnalyzerBase.
Definition at line 233 of file probability_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::Settings::ccf_analysis(), CLOCK, scram::core::Bdd::Function::complement, scram::core::Ite::complement_edge(), scram::DEBUG2, scram::DEBUG4, DUR, scram::core::ProbabilityAnalyzerBase::graph(), scram::core::NonTerminal< T >::high(), scram::core::NonTerminal< T >::index(), LOG, scram::core::NonTerminal< T >::low(), scram::core::NonTerminal< T >::mark(), scram::core::NonTerminal< T >::module(), scram::core::Ite::p(), scram::core::ProbabilityAnalyzerBase::p_vars(), scram::core::IntrusivePtrCast< Ite >::Ref(), scram::core::Analysis::settings(), scram::core::FaultTreeAnalysis::top_event(), and scram::core::Bdd::Function::vertex.
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc