scram::core::NonTerminal< T > Class Template Reference
scram::core::NonTerminal< T > Class Template Reference
Representation of non-terminal vertices in BDD graphs.
#include <bdd.h>
Public Member Functions
NonTerminal (int index, int order, int id, const VertexPtr &high, const VertexPtr &low)
int index () const
int order () const
bool module () const
void module (bool flag)
Sets this vertex for representation of a module.
bool coherent () const
void coherent (bool flag)
Sets the flag for coherent modules.
const VertexPtr & high () const
const VertexPtr & low () const
bool mark () const
void mark (bool flag)
Marks this vertex.
Public Member Functions inherited from scram::core::Vertex< T >
Vertex (int id)
int id () const
bool terminal () const
int use_count () const
bool unique () const
Friends
int get_high_id (const NonTerminal< T > &vertex) noexcept
Default logic for getting signature high and low ids.
int get_low_id (const NonTerminal< T > &vertex) noexcept
Default logic for getting signature high and low ids.
Additional Inherited Members
Static Public Member Functions inherited from scram::core::IntrusivePtrCast< T >
static IntrusivePtr< T > Ptr (const IntrusivePtr< Vertex< T >> &vertex)
static T & Ref (const IntrusivePtr< Vertex< T >> &vertex)
Protected Member Functions inherited from scram::core::Vertex< T >
~Vertex () noexcept
Communicates the destruction via the pointer to the unique table entry if there's any.
Detailed Description
template<class T>
class scram::core::NonTerminal< T >
Representation of non-terminal vertices in BDD graphs.
This class is a base class for various BDD-specific vertices. however, as Vertex, NonTerminal is not polymorphic.
Template Parameters
T The type of the main functional BDD vertex.
Definition at line 230 of file bdd.h.
Constructor & Destructor Documentation
template<class T> scram::core::NonTerminal< T >::NonTerminal (int index, int order, int id, const VertexPtr & high, const VertexPtr & low) inline
Parameters
[in] index Index of this non-terminal vertex.
[in] order Specific ordering number for BDD graphs.
[in] id Unique identifier of the ROBDD graph. The identifier should not collide with the identifiers (0/1) of terminal nodes.
[in] high A vertex for the (1/True/then/left) branch.
[in] low A vertex for the (0/False/else/right) branch.
Definition at line 255 of file bdd.h.
Member Function Documentation
template<class T> int scram::core::NonTerminal< T >::index () const inline
Returns
The index of this vertex.
Definition at line 267 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::Apply(), scram::core::Zbdd::ApplySubstitutions(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), scram::core::Zbdd::GatherModules(), scram::core::zbdd::CutSetContainer::GatherModules(), scram::core::zbdd::CutSetContainer::GetNextGate(), and scram::core::Zbdd::Minimize().
template<class T> int scram::core::NonTerminal< T >::order () const inline
Returns
The order of the vertex.
Definition at line 270 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::Apply(), scram::core::Zbdd::ApplySubstitutions(), and scram::core::Zbdd::FindOrAddVertex().
template<class T> bool scram::core::NonTerminal< T >::module () const inline
Returns
true if this vertex represents a module gate.
Definition at line 276 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::ApplySubstitutions(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), scram::core::Zbdd::GatherModules(), scram::core::zbdd::CutSetContainer::GetNextGate(), and scram::core::Zbdd::Minimize().
template<class T> bool scram::core::NonTerminal< T >::coherent () const inline
Returns
true if the vertex represents a coherent module.
Definition at line 282 of file bdd.h.
Referenced by scram::core::Zbdd::GatherModules(), and scram::core::Zbdd::Minimize().
template<class T> void scram::core::NonTerminal< T >::coherent (bool flag) inline
Sets the flag for coherent modules.
Parameters
[in] flag true for coherent modules.
Definition at line 287 of file bdd.h.
template<class T> const VertexPtr& scram::core::NonTerminal< T >::high () const inline
Returns
(1/True/then/left) branch if-then-else vertex.
Definition at line 293 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::ApplySubstitutions(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), and scram::core::Zbdd::GatherModules().
template<class T> const VertexPtr& scram::core::NonTerminal< T >::low () const inline
Returns
(0/False/else/right) branch vertex.
Definition at line 296 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::Apply(), scram::core::Zbdd::ApplySubstitutions(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), and scram::core::Zbdd::GatherModules().
template<class T> bool scram::core::NonTerminal< T >::mark () const inline
Returns
The mark of this vertex.
Definition at line 299 of file bdd.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::ApplySubstitutions(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), and scram::core::ProbabilityAnalyzer< Bdd >::ProbabilityAnalyzer().
template<class T> void scram::core::NonTerminal< T >::mark (bool flag) inline
Marks this vertex.
Parameters
[in] flag A flag with the meaning for the user of marks.
Definition at line 304 of file bdd.h.
Friends And Related Function Documentation
template<class T> int get_high_id (const NonTerminal< T > & vertex) friend
Default logic for getting signature high and low ids.
Parameters
[in] vertex Non-terminal vertex.
Returns
Numbers that can be used to uniquely identify the arg vertex.
Definition at line 239 of file bdd.h.
template<class T> int get_low_id (const NonTerminal< T > & vertex) friend
Default logic for getting signature high and low ids.
Parameters
[in] vertex Non-terminal vertex.
Returns
Numbers that can be used to uniquely identify the arg vertex.
Definition at line 242 of file bdd.h.
The documentation for this class was generated from the following file:
bdd.h