scram::core::Bdd Class Reference
scram::core::Bdd Class Reference
Analysis of PDAGs with Binary Decision Diagrams.
#include <bdd.h>
Classes
class Consensus
Provides access to consensus calculation private facilities.
struct Function
Holder of computation resultant functions and gate representations.
Public Types
using VertexPtr = IntrusivePtr< Vertex< Ite >>
BDD vertex base.
using TerminalPtr = IntrusivePtr< Terminal< Ite >>
Terminal vertices.
Public Member Functions
Bdd (const Pdag *graph, const Settings &settings)
Constructor with the analysis target.
~Bdd () noexcept
To handle incomplete ZBDD type with unique pointers.
const Function & root () const
const std::unordered_map< int, Function > & modules () const
const std::unordered_map< int, int > & index_to_order () const
bool coherent () const
void ClearMarks (bool mark)
Helper function to clear and set vertex marks.
void Analyze (const Pdag *graph=nullptr) noexcept
Runs the Qualitative analysis with the representation of a PDAG as ROBDD.
const Zbdd & products () const
Detailed Description
Analysis of PDAGs with Binary Decision Diagrams.
This binary decision diagram data structure represents Reduced Ordered BDD with attributed edges.
Note
The low/else edge is chosen to have the attribute for an ITE vertex. There is only one terminal vertex of value 1/True.
Definition at line 690 of file bdd.h.
Constructor & Destructor Documentation
scram::core::Bdd::Bdd (const Pdag * graph, const Settings & settings)
Constructor with the analysis target.
Reduced Ordered BDD is produced from a PDAG.
Parameters
[in] graph Preprocessed and partially normalized PDAG.
[in] settings The analysis settings.
Precondition
The PDAG has variable ordering.
Note
BDD construction may take considerable time.
Definition at line 41 of file bdd.cc.
References scram::core::Gate::args(), begin, ClearMarks(), scram::core::Bdd::Function::complement, scram::core::Pdag::complement(), scram::core::Gate::constant(), scram::DEBUG3, scram::DEBUG4, gates, scram::core::Node::index(), scram::core::Pdag::IsTrivial(), LOG, scram::core::Node::order(), scram::core::Pdag::root(), scram::core::CacheTable< V >::size(), TIMER, scram::core::Bdd::Function::vertex, and ~Bdd().
Member Function Documentation
const Function& scram::core::Bdd::root () const inline
Returns
The root function of the ROBDD.
Definition at line 744 of file bdd.h.
const std::unordered_map<int, Function>& scram::core::Bdd::modules () const inline
Returns
Mapping of PDAG modules and BDD graph vertices.
Definition at line 747 of file bdd.h.
Referenced by scram::core::Zbdd::Zbdd().
const std::unordered_map<int, int>& scram::core::Bdd::index_to_order () const inline
Returns
Mapping of variable indices to their orders.
Definition at line 750 of file bdd.h.
bool scram::core::Bdd::coherent () const inline
Returns
true if the BDD has been constructed from a coherent PDAG.
Definition at line 755 of file bdd.h.
void scram::core::Bdd::ClearMarks (bool mark) inline
Helper function to clear and set vertex marks.
Parameters
[in] mark Desired mark for BDD vertices.
Note
Marks will propagate to modules as well.
Warning
If the graph is discontinuously and partially marked, this function will not help with the mess.
Definition at line 765 of file bdd.h.
References ClearMarks().
Referenced by Analyze(), Bdd(), and ClearMarks().
void scram::core::Bdd::Analyze (const Pdag * graph = nullptr) noexcept
Runs the Qualitative analysis with the representation of a PDAG as ROBDD.
Parameters
[in] graph The optional PDAG with non-declarative substitutions.
Definition at line 84 of file bdd.cc.
References scram::core::Gate::args(), ClearMarks(), scram::core::Gate::coherent(), scram::core::Bdd::Function::complement, scram::core::Ite::complement_edge(), scram::core::Gate::constant(), scram::core::CacheTable< V >::emplace(), scram::core::WeakIntrusivePtr< T >::expired(), gates, scram::core::NonTerminal< T >::high(), scram::core::Node::index(), scram::core::NonTerminal< T >::index(), scram::core::WeakIntrusivePtr< T >::lock(), scram::core::NonTerminal< T >::low(), scram::core::NonTerminal< T >::mark(), scram::core::NonTerminal< T >::module(), scram::core::Gate::module(), scram::core::Node::order(), scram::core::NonTerminal< T >::order(), scram::core::NodeParentManager::parents(), scram::core::IntrusivePtrCast< Ite >::Ptr(), scram::core::IntrusivePtrCast< Ite >::Ref(), ext::linear_map< Key, Value, ErasePolicy, Sequence >::size(), scram::core::Bdd::Function::swap(), scram::core::Gate::type(), and scram::core::Bdd::Function::vertex.
const Zbdd& scram::core::Bdd::products () const inline
Returns
Products generated by the analysis.
Precondition
Analysis is done.
Definition at line 776 of file bdd.h.
References gates.
The documentation for this class was generated from the following files:
bdd.h
bdd.cc