scram::mef::Initializer Class Reference
scram::mef::Initializer Class Reference
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
#include <initializer.h>
Classes
struct Extractor
struct Extractor< T,-1 >
Specialization of Extractor to extract all expressions into arg vector.
Public Member Functions
Initializer (const std::vector< std::string > &xml_files, core::Settings settings, bool allow_extern=false, xml::Validator *extra_validator=nullptr)
Reads input files with the structure of analysis constructs.
std::unique_ptr< Model > model ()&&
template<>
Gate * Register (const xml::Element &gate_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
BasicEvent * Register (const xml::Element &event_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
HouseEvent * Register (const xml::Element &event_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
Parameter * Register (const xml::Element &param_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
CcfGroup * Register (const xml::Element &ccf_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
Sequence * Register (const xml::Element &xml_node, const std::string &, RoleSpecifier)
Specializations for element registrations.
template<>
void Define (const xml::Element &gate_node, Gate *gate)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &event_node, BasicEvent *basic_event)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &param_node, Parameter *parameter)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &ccf_node, CcfGroup *ccf_group)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &xml_node, Sequence *sequence)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &et_node, EventTree *event_tree)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &xml_node, InitiatingEvent *initiating_event)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &rule_node, Rule *rule)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &xml_node, Alignment *alignment)
Specializations for elements defined after registration.
template<>
void Define (const xml::Element &xml_node, Substitution *substitution)
Specializations for elements defined after registration.
Detailed Description
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
The initialization phase includes validation and proper setup of the constructs for future use or analysis.
Definition at line 60 of file initializer.h.
Constructor & Destructor Documentation
scram::mef::Initializer::Initializer (const std::vector< std::string > & xml_files, core::Settings settings, bool allow_extern = false, xml::Validator * extra_validator = nullptr)
Reads input files with the structure of analysis constructs.
Initializes the analysis model from the given input files. Puts all events into their appropriate containers in the model.
Parameters
[in] xml_files The MEF XML input files.
[in] settings Analysis settings.
[in] allow_extern Allow external libraries in the input.
[in] extra_validator Additional XML validator to be run after the MEF validator.
Exceptions
IOError Input contains duplicate files.
IOError One of the input files is not accessible.
xml::Error The xml files contain errors or malformed.
xml::ValidityError The xml files are not valid for schema.
mef::ValidityError The input model contains errors.
Warning
Processing external libraries from XML input is UNSAFE. It allows loading and executing arbitrary code during analysis. Enable this feature for trusted input files and libraries only.
Definition at line 158 of file initializer.cc.
References BLOG, CLOCK, scram::DEBUG1, scram::DEBUG2, scram::DEBUG3, DUR, scram::xml::Element::line(), LOG, SCRAM_THROW, scram::xml::Validator::validate(), and scram::WARNING.
Member Function Documentation
std::unique_ptr<Model> scram::mef::Initializer::model () inline
Returns
The model built from the input files.
Definition at line 86 of file initializer.h.
References scram::mef::Id::full_path().
Referenced by Register().
The documentation for this class was generated from the following files:
initializer.h
initializer.cc