scram::mef::Ite Class Reference
scram::mef::Ite Class Reference
If-Then-Else ternary expression.
#include <conditional.h>
Public Member Functions
Ite (Expression *condition, Expression *then_arm, Expression *else_arm)
Interval interval () noexceptoverride
template<typename F >
double Compute (F &&eval) noexcept
Computes the if-then-else expression with the given evaluator.
Public Member Functions inherited from scram::mef::ExpressionFormula< Ite >
double value () noexceptfinal
Computes the expression with argument expression default values.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
virtual void Validate () const
Validates the expression.
virtual bool IsDeviate () noexcept
Determines if the value of the expression contains deviate expressions.
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
If-Then-Else ternary expression.
Definition at line 30 of file conditional.h.
Constructor & Destructor Documentation
scram::mef::Ite::Ite (Expression * condition, Expression * then_arm, Expression * else_arm) inline
Parameters
[in] condition The Boolean expression to be tested.
[in] then_arm The expression if the Boolean is true.
[in] else_arm The expression if the Boolean is false.
Definition at line 35 of file conditional.h.
References interval().
Member Function Documentation
Interval scram::mef::Ite::interval () override virtual noexcept
Returns
The domain interval for validation purposes only.
Reimplemented from scram::mef::Expression.
Definition at line 27 of file conditional.cc.
References scram::mef::Expression::args().
Referenced by Ite().
The documentation for this class was generated from the following files:
conditional.h
conditional.cc