scram::core::SetNode Class Reference
scram::core::SetNode Class Reference
Representation of non-terminal nodes in ZBDD.
#include <zbdd.h>
Public Member Functions
bool minimal () const
void minimal (bool flag)
Sets the indication of a minimized ZBDD.
int max_set_order () const
void max_set_order (int order)
Registers the order of the largest set in the ZBDD represented by this vertex.
std::int64_t count () const
void count (std::int64_t number)
Stores numerical value for later retrieval.
Public Member Functions inherited from scram::core::NonTerminal< SetNode >
NonTerminal (int index, int order, int id, const VertexPtr &high, const VertexPtr &low)
int index () const
int order () const
bool module () const
void module (bool flag)
Sets this vertex for representation of a module.
bool coherent () const
void coherent (bool flag)
Sets the flag for coherent modules.
const VertexPtr & high () const
const VertexPtr & low () const
bool mark () const
void mark (bool flag)
Marks this vertex.
Public Member Functions inherited from scram::core::Vertex< SetNode >
Vertex (int id)
int id () const
bool terminal () const
int use_count () const
bool unique () const
Additional Inherited Members
Static Public Member Functions inherited from scram::core::IntrusivePtrCast< SetNode >
static IntrusivePtr< SetNode > Ptr (const IntrusivePtr< Vertex< SetNode >> &vertex)
static SetNode & Ref (const IntrusivePtr< Vertex< SetNode >> &vertex)
Protected Member Functions inherited from scram::core::Vertex< SetNode >
~Vertex () noexcept
Communicates the destruction via the pointer to the unique table entry if there's any.
Detailed Description
Representation of non-terminal nodes in ZBDD.
Complement variables are represented with negative indices. The order of the complement is higher than the order of the variable.
Definition at line 44 of file zbdd.h.
Member Function Documentation
bool scram::core::SetNode::minimal () const inline
Returns
true if the ZBDD is minimized.
Definition at line 49 of file zbdd.h.
Referenced by scram::core::Zbdd::Analyze(), scram::core::Zbdd::ApplySubstitutions(), scram::core::Zbdd::JoinModule(), scram::core::Zbdd::Minimize(), and scram::core::Zbdd::Zbdd().
void scram::core::SetNode::minimal (bool flag) inline
Sets the indication of a minimized ZBDD.
Parameters
[in] flag A flag for minimized ZBDD.
Definition at line 54 of file zbdd.h.
int scram::core::SetNode::max_set_order () const inline
Returns
The registered order of the largest set in the ZBDD.
Definition at line 57 of file zbdd.h.
Referenced by scram::core::Zbdd::Analyze(), scram::core::Zbdd::Apply(), scram::core::Zbdd::EliminateComplements(), scram::core::zbdd::CutSetContainer::ExpandGate(), scram::core::Zbdd::FindOrAddVertex(), and scram::core::zbdd::CutSetContainer::Merge().
void scram::core::SetNode::max_set_order (int order) inline
Registers the order of the largest set in the ZBDD represented by this vertex.
Parameters
[in] order The order/size of the largest set.
Definition at line 63 of file zbdd.h.
References scram::core::NonTerminal< SetNode >::order().
std::int64_t scram::core::SetNode::count () const inline
Returns
Whatever count is stored in this node.
Definition at line 66 of file zbdd.h.
Referenced by scram::core::Zbdd::ApplySubstitutions().
void scram::core::SetNode::count (std::int64_t number) inline
Stores numerical value for later retrieval.
This can be a helper functionality for counting the number of sets or nodes.
Parameters
[in] number A number with a meaning for the caller.
Note
This field is provided for ZBDD processing techniques that use mutually exclusive meta-data about the node in different stages of ZBDD processing. Usually, the data is not needed after the technique is done. In contrast to providing separate fields or using hash tables for each technique metric, this general-purpose field saves space and time.
Definition at line 81 of file zbdd.h.
The documentation for this class was generated from the following file:
zbdd.h