scram::core::Settings Class Reference
scram::core::Settings Class Reference
Builder for analysis settings.
#include <settings.h>
Public Member Functions
Algorithm algorithm () const
Settings & algorithm (Algorithm value) noexcept
Sets the algorithm for Qualitative analysis.
Settings & algorithm (std::string_view value)
Provides a convenient wrapper for algorithm setting from a string.
Approximation approximation () const
bool prime_implicants () const
Settings & prime_implicants (bool flag)
Sets a flag to calculate prime implicants instead of minimal cut sets.
int limit_order () const
Settings & limit_order (int order)
Sets the limit order for products.
double cut_off () const
Settings & cut_off (double prob)
Sets the cut-off probability for products to be considered for analysis.
int num_trials () const
Settings & num_trials (int n)
Sets the number of trials for Monte Carlo simulations.
int num_quantiles () const
Settings & num_quantiles (int n)
Sets the number of quantiles for distributions.
int num_bins () const
Settings & num_bins (int n)
Sets the number of bins for histograms.
int seed () const
Settings & seed (int s)
Sets the seed for the pseudo-random number generator.
double mission_time () const
Settings & mission_time (double time)
Sets the system mission time.
double time_step () const
Settings & time_step (double time)
Sets the time step for probability analyses.
bool probability_analysis () const
Settings & probability_analysis (bool flag)
Sets the flag for probability analysis.
bool safety_integrity_levels () const
Settings & safety_integrity_levels (bool flag)
Sets the flag for calculation of the SIL metrics.
bool importance_analysis () const
Settings & importance_analysis (bool flag)
Sets the flag for importance analysis.
bool uncertainty_analysis () const
Settings & uncertainty_analysis (bool flag)
Sets the flag for uncertainty analysis.
bool ccf_analysis () const
Settings & ccf_analysis (bool flag)
Sets the flag for CCF analysis.
Settings & approximation (Approximation value)
Sets the approximation for quantitative analysis.
Settings & approximation (std::string_view value)
Sets the approximation for quantitative analysis.
Public Attributes
bool preprocessor = false
Stop analysis after preprocessor.
bool print = false
Print analysis results in a terminal friendly way.
Detailed Description
Builder for analysis settings.
Analysis facilities are guaranteed not to throw or fail with an instance of this class.
Warning
Some settings with defaults and constraints may have side-effects on other settings.
The order of building the settings matters.
Definition at line 49 of file settings.h.
Member Function Documentation
Algorithm scram::core::Settings::algorithm () const inline
Returns
The Qualitative analysis algorithm.
Definition at line 52 of file settings.h.
Referenced by algorithm(), and scram::Project::Project().
Settings & scram::core::Settings::algorithm (Algorithm value) noexcept
Sets the algorithm for Qualitative analysis.
Appropriate defaults are given to other settings relevant to the algorithm.
MOCUS and ZBDD based analyses run with the Rare-Event approximation by default. Whereas, BDD based analyses run with exact quantitative analysis.
Parameters
[in] value The algorithm kind.
Returns
Reference to this object.
Definition at line 31 of file settings.cc.
Settings & scram::core::Settings::algorithm (std::string_view value)
Provides a convenient wrapper for algorithm setting from a string.
Parameters
[in] value The string representation of the algorithm.
Exceptions
SettingsError The algorithm is not recognized.
Returns
Reference to this object.
Definition at line 46 of file settings.cc.
References algorithm(), end, scram::core::kAlgorithmToString, and SCRAM_THROW.
Approximation scram::core::Settings::approximation () const inline
Returns
The quantitative analysis approximation.
Definition at line 77 of file settings.h.
Referenced by approximation(), prime_implicants(), and scram::Project::Project().
Settings & scram::core::Settings::approximation (Approximation value)
Sets the approximation for quantitative analysis.
Parameters
[in] value Approximation kind to be applied.
Returns
Reference to this object.
Exceptions
SettingsError The approximation is not recognized or inappropriate for analysis.
Definition at line 57 of file settings.cc.
References SCRAM_THROW.
Settings & scram::core::Settings::approximation (std::string_view value)
Sets the approximation for quantitative analysis.
Parameters
[in] value Approximation kind to be applied.
Returns
Reference to this object.
Exceptions
SettingsError The approximation is not recognized or inappropriate for analysis.
Definition at line 65 of file settings.cc.
References approximation(), end, scram::core::kApproximationToString, and SCRAM_THROW.
bool scram::core::Settings::prime_implicants () const inline
Returns
true if prime implicants are to be calculated instead of minimal cut sets.
Definition at line 94 of file settings.h.
Referenced by scram::core::Zbdd::FindOrAddVertex(), scram::core::Zbdd::Minimize(), scram::Project::Project(), and scram::core::Zbdd::Zbdd().
Settings & scram::core::Settings::prime_implicants (bool flag)
Sets a flag to calculate prime implicants instead of minimal cut sets.
Prime implicants can only be calculated with BDD-based algorithms.
The request for prime implicants cancels the request for inapplicable quantitative analysis approximations.
Parameters
[in] flag True for the request.
Returns
Reference to this object.
Exceptions
SettingsError The request is not relevant to the algorithm.
Definition at line 76 of file settings.cc.
References approximation(), and SCRAM_THROW.
int scram::core::Settings::limit_order () const inline
Returns
The limit on the size of products.
Definition at line 110 of file settings.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::FaultTreeAnalysis::Analyze(), scram::core::Zbdd::Analyze(), scram::core::Zbdd::ApplySubstitutions(), scram::core::zbdd::CutSetContainer::ConvertGate(), scram::core::Zbdd::EliminateComplements(), scram::core::Zbdd::EliminateConstantModules(), scram::core::zbdd::CutSetContainer::ExpandGate(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Zbdd::GatherModules(), scram::core::zbdd::CutSetContainer::Merge(), scram::Project::Project(), and scram::core::Zbdd::Zbdd().
Settings & scram::core::Settings::limit_order (int order)
Sets the limit order for products.
Parameters
[in] order A non-negative number for the limit order.
Returns
Reference to this object.
Exceptions
SettingsError The number is less than 0.
Definition at line 87 of file settings.cc.
References SCRAM_THROW.
double scram::core::Settings::cut_off () const inline
Returns
The minimum required probability for products.
Definition at line 122 of file settings.h.
Referenced by scram::Project::Project().
Settings & scram::core::Settings::cut_off (double prob)
Sets the cut-off probability for products to be considered for analysis.
Parameters
[in] prob The minimum probability for products.
Returns
Reference to this object.
Exceptions
SettingsError The probability is not in the [0, 1] range.
Definition at line 97 of file settings.cc.
References SCRAM_THROW.
int scram::core::Settings::num_trials () const inline
Returns
The number of trials for Monte-Carlo simulations.
Definition at line 135 of file settings.h.
Referenced by scram::Project::Project(), and scram::core::UncertaintyAnalysis::SampleExpressions().
Settings & scram::core::Settings::num_trials (int n)
Sets the number of trials for Monte Carlo simulations.
Parameters
[in] n A natural number for the number of trials.
Returns
Reference to this object.
Exceptions
SettingsError The number is less than 1.
Definition at line 107 of file settings.cc.
References SCRAM_THROW.
int scram::core::Settings::num_quantiles () const inline
Returns
The number of quantiles for distributions.
Definition at line 147 of file settings.h.
Referenced by scram::Project::Project(), and scram::core::UncertaintyAnalysis::SampleExpressions().
Settings & scram::core::Settings::num_quantiles (int n)
Sets the number of quantiles for distributions.
Parameters
[in] n A natural number for the number of quantiles.
Returns
Reference to this object.
Exceptions
SettingsError The number is less than 1.
Definition at line 116 of file settings.cc.
References SCRAM_THROW.
int scram::core::Settings::num_bins () const inline
Returns
The number of bins for histograms.
Definition at line 159 of file settings.h.
Referenced by scram::Project::Project().
Settings & scram::core::Settings::num_bins (int n)
Sets the number of bins for histograms.
Parameters
[in] n A natural number for the number of bins.
Returns
Reference to this object.
Exceptions
SettingsError The number is less than 1.
Definition at line 125 of file settings.cc.
References SCRAM_THROW.
int scram::core::Settings::seed () const inline
Returns
The seed of the pseudo-random number generator.
Definition at line 171 of file settings.h.
Referenced by scram::core::RiskAnalysis::Analyze(), and scram::Project::Project().
Settings & scram::core::Settings::seed (int s)
Sets the seed for the pseudo-random number generator.
Parameters
[in] s A positive number.
Returns
Reference to this object.
Exceptions
SettingsError The number is negative.
Definition at line 134 of file settings.cc.
References SCRAM_THROW.
double scram::core::Settings::mission_time () const inline
Returns
The length time of the system under risk.
Definition at line 183 of file settings.h.
Referenced by scram::core::RiskAnalysis::Analyze(), scram::Project::Project(), and scram::mef::Initializer::Register().
Settings & scram::core::Settings::mission_time (double time)
Sets the system mission time.
Parameters
[in] time A positive number in hours by default.
Returns
Reference to this object.
Exceptions
SettingsError The time value is negative.
Definition at line 143 of file settings.cc.
References SCRAM_THROW.
double scram::core::Settings::time_step () const inline
Returns
The time step in hours for probability analyses. 0 if the time step doesn't apply.
Definition at line 196 of file settings.h.
Referenced by scram::core::McubCalculator::Calculate(), and scram::Project::Project().
Settings & scram::core::Settings::time_step (double time)
Sets the time step for probability analyses.
0 value signifies that the time step doesn't apply.
Parameters
[in] time The time in hours to partition the mission time.
Returns
Reference to this object.
Exceptions
SettingsError The time value is negative.
SettingsError The time step is being disabled (value 0) while the SIL metrics are requested.
Definition at line 152 of file settings.cc.
References SCRAM_THROW.
bool scram::core::Settings::probability_analysis () const inline
Returns
true if probability analysis is requested.
Definition at line 211 of file settings.h.
Referenced by scram::mef::Initializer::Define(), scram::Project::Project(), and scram::Reporter::Report().
Settings& scram::core::Settings::probability_analysis (bool flag) inline
Sets the flag for probability analysis.
If another analysis requires probability analysis, it won't be possible to turn off probability analysis before the parent analysis.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 221 of file settings.h.
bool scram::core::Settings::safety_integrity_levels () const inline
Returns
true if the SIL metrics are requested.
Definition at line 230 of file settings.h.
Referenced by scram::Project::Project(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
Settings & scram::core::Settings::safety_integrity_levels (bool flag)
Sets the flag for calculation of the SIL metrics.
This requires that time-step is set.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Exceptions
SettingsError The flag is True, but no time-step is set.
Definition at line 164 of file settings.cc.
References SCRAM_THROW.
bool scram::core::Settings::importance_analysis () const inline
Returns
true if importance analysis is requested.
Definition at line 243 of file settings.h.
Referenced by scram::Project::Project().
Settings& scram::core::Settings::importance_analysis (bool flag) inline
Sets the flag for importance analysis.
Importance analysis is performed together with probability analysis. Appropriate flags are turned on.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 253 of file settings.h.
bool scram::core::Settings::uncertainty_analysis () const inline
Returns
true if uncertainty analysis is requested.
Definition at line 261 of file settings.h.
Referenced by scram::Project::Project().
Settings& scram::core::Settings::uncertainty_analysis (bool flag) inline
Sets the flag for uncertainty analysis.
Uncertainty analysis implies probability analysis, so the probability analysis is turned on implicitly.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 270 of file settings.h.
bool scram::core::Settings::ccf_analysis () const inline
Returns
true if CCF groups must be incorporated into analysis.
Definition at line 278 of file settings.h.
Referenced by scram::core::FaultTreeAnalysis::Analyze(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), and scram::Project::Project().
Settings& scram::core::Settings::ccf_analysis (bool flag) inline
Sets the flag for CCF analysis.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 285 of file settings.h.
The documentation for this class was generated from the following files:
settings.h
settings.cc