scram::mef::Expression Class Reference
scram::mef::Expression Class Reference abstract
Abstract base class for all sorts of expressions to describe events.
#include <expression.h>
Public Member Functions
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
virtual void Validate () const
Validates the expression.
virtual double value () noexcept=0
virtual Interval interval () noexcept
virtual bool IsDeviate () noexcept
Determines if the value of the expression contains deviate expressions.
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Protected Member Functions
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Abstract base class for all sorts of expressions to describe events.
This class also acts like a connector for parameter nodes and may create cycles. Expressions are not expected to be shared except for parameters. In addition, expressions are not expected to be changed after validation phases.
Definition at line 66 of file expression.h.
Constructor & Destructor Documentation
scram::mef::Expression::Expression (std::vector< Expression * > args = {}) explicit
Constructor for use by derived classes to register their arguments.
Parameters
[in] args Arguments of this expression.
Definition at line 31 of file expression.cc.
Member Function Documentation
const std::vector<Expression*>& scram::mef::Expression::args () const inline
Returns
A set of arguments of the expression.
Definition at line 77 of file expression.h.
Referenced by scram::mef::Ite::Compute(), scram::mef::Mean::Compute(), scram::mef::ExternExpression< R, Args >::Compute(), scram::mef::NaryExpression< T, 2 >::Compute(), scram::mef::NaryExpression< T,-1 >::Compute(), scram::mef::ExternExpression< R, Args >::ExternExpression(), scram::mef::cycle::GetConnectors(), scram::mef::cycle::GetNodes(), scram::mef::Histogram::Histogram(), scram::mef::Ite::interval(), scram::mef::Mean::interval(), scram::mef::NaryExpression< T, 2 >::interval(), scram::mef::NaryExpression< T,-1 >::interval(), scram::mef::Mean::Mean(), scram::mef::NaryExpression< T,-1 >::NaryExpression(), and scram::mef::Serialize().
virtual void scram::mef::Expression::Validate () const inline virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
DomainError The argument value domains are invalid.
ValidityError The arguments are invalid for setup.
Reimplemented in scram::mef::Histogram, scram::mef::NaryExpression< T,-1 >, scram::mef::BetaDeviate, scram::mef::GammaDeviate, scram::mef::NaryExpression< T, 2 >, scram::mef::NaryExpression< T, 1 >, scram::mef::PeriodicTest, scram::mef::LognormalDeviate, scram::mef::Weibull, scram::mef::NormalDeviate, scram::mef::UniformDeviate, scram::mef::Glm, and scram::mef::Exponential.
Definition at line 84 of file expression.h.
References value().
Referenced by scram::mef::LognormalDeviate::value().
virtual double scram::mef::Expression::value () pure virtual noexcept
Returns
The mean value of this expression.
Implemented in scram::mef::Histogram, scram::mef::BetaDeviate, scram::mef::GammaDeviate, scram::mef::PeriodicTest, scram::mef::ExpressionFormula< T >, scram::mef::ExpressionFormula< Glm >, scram::mef::ExpressionFormula< NaryExpression< T, 2 > >, scram::mef::ExpressionFormula< Switch >, scram::mef::ExpressionFormula< Ite >, scram::mef::ExpressionFormula< ExternExpression< R, Args... > >, scram::mef::ExpressionFormula< Mean >, scram::mef::ExpressionFormula< Exponential >, scram::mef::ExpressionFormula< Weibull >, scram::mef::ExpressionFormula< NaryExpression< T,-1 > >, scram::mef::ExpressionFormula< NaryExpression< T, 1 > >, scram::mef::LognormalDeviate, scram::mef::Parameter, scram::mef::NormalDeviate, scram::mef::TestFunctionalEvent, scram::mef::UniformDeviate, scram::mef::MissionTime, scram::mef::TestInitiatingEvent, and scram::mef::ConstantExpression.
Referenced by scram::mef::CcfGroup::ApplyModel(), scram::mef::EnsureNonNegative(), scram::mef::EnsurePositive(), scram::mef::EnsureProbability(), scram::mef::EnsureWithin(), interval(), scram::mef::NormalDeviate::interval(), scram::mef::GammaDeviate::interval(), scram::mef::BetaDeviate::interval(), scram::mef::Histogram::interval(), scram::mef::UniformDeviate::Validate(), Validate(), scram::mef::NormalDeviate::Validate(), scram::mef::GammaDeviate::Validate(), scram::mef::BetaDeviate::Validate(), scram::mef::LognormalDeviate::value(), scram::mef::ExpressionFormula< NaryExpression< T, 1 > >::value(), scram::mef::Histogram::value(), and scram::mef::InstructionVisitor::Visit().
virtual Interval scram::mef::Expression::interval () inline virtual noexcept
Returns
The domain interval for validation purposes only.
Reimplemented in scram::mef::Histogram, scram::mef::NaryExpression< T,-1 >, scram::mef::BetaDeviate, scram::mef::GammaDeviate, scram::mef::NaryExpression< T, 2 >, scram::mef::NaryExpression< T, 1 >, scram::mef::PeriodicTest, scram::mef::LognormalDeviate, scram::mef::Parameter, scram::mef::Weibull, scram::mef::NormalDeviate, scram::mef::Mean, scram::mef::UniformDeviate, scram::mef::Glm, scram::mef::MissionTime, scram::mef::Switch, scram::mef::TestEvent, scram::mef::Exponential, and scram::mef::Ite.
Definition at line 90 of file expression.h.
References IsDeviate(), Reset(), Sample(), and value().
Referenced by scram::mef::NaryExpression< T,-1 >::Compute(), scram::mef::detail::EnsureMultivariateArgs(), scram::mef::EnsureNonNegative(), scram::mef::EnsurePositive(), scram::mef::EnsureProbability(), scram::mef::EnsureWithin(), scram::mef::Switch::interval(), scram::mef::LognormalDeviate::value(), scram::mef::GammaDeviate::value(), and scram::mef::BetaDeviate::value().
bool scram::mef::Expression::IsDeviate () virtual noexcept
Determines if the value of the expression contains deviate expressions.
The default logic is to check arguments with uncertainties for sampling. Derived expression classes must decide if they don't have arguments, or if they are random deviates.
Returns
true if the expression's value deviates from its mean.
false if the expression's value does not need sampling.
Warning
Improper registration of arguments may yield silent failure.
Reimplemented in scram::mef::MissionTime, scram::mef::RandomDeviate, scram::mef::TestEvent, and scram::mef::ConstantExpression.
Definition at line 50 of file expression.cc.
References IsDeviate().
Referenced by interval(), and IsDeviate().
double scram::mef::Expression::Sample () noexcept
Returns
A sampled value of this expression.
Definition at line 34 of file expression.cc.
Referenced by interval(), scram::mef::PeriodicTest::interval(), and scram::mef::ExpressionFormula< NaryExpression< T, 1 > >::value().
void scram::mef::Expression::Reset () noexcept
This routine resets the sampling to get new values.
All the arguments are called to reset themselves. If this expression was not sampled, its arguments are not going to get any calls.
Definition at line 42 of file expression.cc.
Referenced by interval().
void scram::mef::Expression::AddArg (Expression * arg) inline protected
Registers an additional argument expression.
Parameters
[in] arg An argument expression used by this expression.
Definition at line 121 of file expression.h.
Referenced by scram::mef::Parameter::expression(), scram::mef::Histogram::Histogram(), and scram::mef::Switch::Switch().
The documentation for this class was generated from the following files:
expression.h
expression.cc