scram::mef::NormalDeviate Class Reference
scram::mef::NormalDeviate Class Reference
Normal distribution.
#include <random_deviate.h>
Public Member Functions
NormalDeviate (Expression *mean, Expression *sigma)
Setup for normal distribution.
void Validate () const override
double value () noexceptoverride
Interval interval () noexceptoverride
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Static Public Member Functions inherited from scram::mef::RandomDeviate
static void seed (unsigned seed) noexcept
Sets the seed of the underlying random number generator.
Protected Member Functions inherited from scram::mef::RandomDeviate
std::mt19937 & rng ()
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Normal distribution.
Definition at line 88 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::NormalDeviate::NormalDeviate (Expression * mean, Expression * sigma)
Setup for normal distribution.
Parameters
[in] mean The mean of the distribution.
[in] sigma The standard deviation of the distribution.
Definition at line 56 of file random_deviate.cc.
Member Function Documentation
void scram::mef::NormalDeviate::Validate () const override virtual
Exceptions
DomainError The sigma is negative or zero.
Reimplemented from scram::mef::Expression.
Definition at line 59 of file random_deviate.cc.
References scram::mef::RandomDeviate::rng(), SCRAM_THROW, and scram::mef::Expression::value().
double scram::mef::NormalDeviate::value () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 99 of file random_deviate.h.
Interval scram::mef::NormalDeviate::interval () inline override virtual noexcept
Returns
~99.9% confidence interval.
Reimplemented from scram::mef::Expression.
Definition at line 101 of file random_deviate.h.
References scram::mef::Expression::value().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc