scram::core::UncertaintyAnalysis Class Reference
scram::core::UncertaintyAnalysis Class Reference abstract
Uncertainty analysis and statistics for top event or gate probabilities with probability distributions of basic events.
#include <uncertainty_analysis.h>
Public Member Functions
UncertaintyAnalysis (const ProbabilityAnalysis *prob_analysis)
Uncertainty analysis on the fault tree processed by probability analysis.
void Analyze () noexcept
Performs quantitative analysis on the total probability.
double mean () const
double sigma () const
double error_factor () const
const std::pair< double, double > & confidence_interval () const
const std::vector< std::pair< double, double > > & distribution () const
const std::vector< double > & quantiles () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Protected Member Functions
std::vector< std::pair< int, mef::Expression & > > GatherDeviateExpressions (const Pdag *graph) noexcept
Gathers deviate expressions of variables.
void SampleExpressions (const std::vector< std::pair< int, mef::Expression & >> &deviate_expressions, Pdag::IndexMap< double > *p_vars) noexcept
Samples uncertain probabilities.
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Uncertainty analysis and statistics for top event or gate probabilities with probability distributions of basic events.
Definition at line 40 of file uncertainty_analysis.h.
Constructor & Destructor Documentation
scram::core::UncertaintyAnalysis::UncertaintyAnalysis (const ProbabilityAnalysis * prob_analysis) explicit
Uncertainty analysis on the fault tree processed by probability analysis.
Parameters
[in] prob_analysis Completed probability analysis.
Definition at line 38 of file uncertainty_analysis.cc.
Member Function Documentation
void scram::core::UncertaintyAnalysis::Analyze () noexcept
Performs quantitative analysis on the total probability.
Note
Undefined behavior if analysis called two or more times.
Definition at line 45 of file uncertainty_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::Analysis::analysis_time(), CLOCK, scram::DEBUG3, DUR, LOG, and TIMER.
double scram::core::UncertaintyAnalysis::mean () const inline
Returns
Mean of the final distribution.
Definition at line 57 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
double scram::core::UncertaintyAnalysis::sigma () const inline
Returns
Standard deviation of the final distribution.
Definition at line 60 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
double scram::core::UncertaintyAnalysis::error_factor () const inline
Returns
Error factor for 95% confidence level.
Definition at line 63 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::pair<double, double>& scram::core::UncertaintyAnalysis::confidence_interval () const inline
Returns
95% confidence interval of the mean.
Definition at line 66 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<std::pair<double, double> >& scram::core::UncertaintyAnalysis::distribution () const inline
Returns
The distribution histogram.
Definition at line 71 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<double>& scram::core::UncertaintyAnalysis::quantiles () const inline
Returns
Quantiles of the distribution.
Definition at line 76 of file uncertainty_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
std::vector< std::pair< int, mef::Expression & > > scram::core::UncertaintyAnalysis::GatherDeviateExpressions (const Pdag * graph) protected noexcept
Gathers deviate expressions of variables.
Parameters
[in] graph PDAG with the variables.
Returns
The gathered deviate expressions with variable indices.
Definition at line 62 of file uncertainty_analysis.cc.
References scram::core::Pdag::kVariableStartIndex.
void scram::core::UncertaintyAnalysis::SampleExpressions (const std::vector< std::pair< int, mef::Expression & >> & deviate_expressions, Pdag::IndexMap< double > * p_vars) protected noexcept
Samples uncertain probabilities.
Parameters
[in] deviate_expressions A collection of deviate expressions.
[in,out] p_vars Indices to probabilities mapping with values.
Definition at line 73 of file uncertainty_analysis.cc.
References scram::core::Settings::num_quantiles(), scram::core::Settings::num_trials(), and scram::core::Analysis::settings().
The documentation for this class was generated from the following files:
uncertainty_analysis.h
uncertainty_analysis.cc