scram::core::Gate Class Reference
scram::core::Gate Class Reference
An indexed gate for use in a PDAG.
#include <pdag.h>
Public Types
template<class T >
using ArgMap = ext::linear_map< int, std::shared_ptr< T >, ext::MoveEraser >
An associative container type to store the gate arguments.
using ArgSet = boost::container::flat_set< int >
An ordered set of gate argument indices.
template<class T >
using Arg = std::pair< int, std::shared_ptr< T >>
An argument entry type in the gate's argument containers.
template<class T >
using ConstArg = std::pair< int, const T & >
An argument entry type in the gate's argument containers.
Public Types inherited from scram::core::NodeParentManager
using Parent = std::pair< int, GateWeakPtr >
Parent index and ptr.
using ParentMap = ext::linear_map< int, GateWeakPtr, ext::MoveEraser >
A map type of parent gate positive indices and weak pointers to them.
Public Member Functions
Gate (Connective type, Pdag *graph) noexcept
Creates an indexed gate with its unique index.
~Gate () noexcept
Destructs parent information from the arguments.
GatePtr Clone () noexcept
Clones arguments and parameters.
Connective type () const
void type (Connective type)
Changes the logic of the gate.
int min_number () const
void min_number (int number)
Sets the min number for this gate.
bool constant () const
const ArgSet & args () const
template<class T >
const ArgMap< T > & args ()
Generic accessor to the gate argument containers.
template<class T >
auto args () const
Provides const access to gate arguments w/o exposing the shared pointers.
bool mark () const
Marks are used for linear traversal of graphs.
void mark (bool flag)
Sets the mark of this gate.
int descendant () const
void descendant (int index)
Assigns a descendant index of this gate.
int ancestor ()
void ancestor (int index)
Assigns an ancestor index of this gate.
int min_time () const override
void min_time (int time)
Sets the queried minimum visit time of the sub-graph.
int max_time () const override
void max_time (int time)
Sets the queried maximum visit time of the sub-graph.
bool coherent () const
void coherent (bool flag)
Sets a coherence flag for the graph rooted by this gate.
bool module () const
void module (bool flag)
Sets this gate's module flag.
int GetArgSign (const NodePtr &arg) const noexcept
Helper function to use the sign of the argument.
NodePtr GetArg (int index) const noexcept
Helper function for algorithms to get nodes from argument indices.
template<class T >
void AddArg (int index, const std::shared_ptr< T > &arg) noexcept
Adds an argument node to this gate.
template<class T >
void AddArg (const std::shared_ptr< T > &arg, bool complement=false) noexcept
Wrapper to add gate arguments with index retrieval from the arg.
template<class T >
void AddArg (const Arg< T > &arg) noexcept
Wrapper to add arguments from the containers.
void TransferArg (int index, const GatePtr &recipient) noexcept
Transfers this gate's argument to another gate.
void ShareArg (int index, const GatePtr &recipient) noexcept
Shares this gate's argument with another gate.
void NegateArgs () noexcept
Makes all arguments complements of themselves.
void NegateArg (int existing_arg) noexcept
Replaces an argument with the complement of it.
void NegateNonCoherentGateArgs () noexcept
Turns all non-coherent arguments of type gate (NOT, NAND, etc.) into complement arguments.
void CoalesceGate (const GatePtr &arg_gate) noexcept
Adds arguments of an argument gate to this gate.
void JoinNullGate (int index) noexcept
Swaps a single argument of a NULL type argument gate.
void ProcessConstantArg (const NodePtr &arg, bool state) noexcept
Changes the state of a gate or removes a constant argument.
void EraseArg (int index) noexcept
Removes an argument from the arguments container.
void EraseArgs () noexcept
Clears all the arguments of this gate.
void MakeConstant (bool state) noexcept
Sets the logic of this gate to pass-through and clears all its arguments except for a Boolean constant.
template<>
void AddArg (int index, const ConstantPtr &arg) noexcept
Convenient wrapper to dispatch appropriate constant arg handler.
template<>
void AddArg (int index, const ConstantPtr &arg) noexcept
Specialization to handle Boolean constants in arguments.
Public Member Functions inherited from scram::core::Node
Node (Pdag *graph) noexcept
Creates a unique graph node as a member of a PDAG.
virtual ~Node ()=0
Abstract class.
Pdag & graph ()
int index () const
int order () const
void order (int val)
Sets the order number for this node.
int opti_value () const
void opti_value (int val)
Sets the optimization value for failure propagation.
bool Visit (int time)
Registers the visit time for this node upon graph traversal.
int EnterTime () const
int ExitTime () const
int LastVisit () const
bool Revisited () const
bool Visited () const
void ClearVisits ()
Clears all the visit information. Resets the visit times to 0s.
int pos_count () const
int neg_count () const
void AddCount (bool positive)
Increases the count of this node.
void ResetCount ()
Resets positive and negative counts of this node.
Public Member Functions inherited from scram::core::NodeParentManager
const ParentMap & parents () const
Detailed Description
An indexed gate for use in a PDAG.
Initially this gate can represent any type of gate or logic; however, this gate can be only of OR and AND type at the end of all simplifications and processing. This gate class helps process the fault tree before any complex analysis is done.
Definition at line 282 of file pdag.h.
Member Typedef Documentation
template<class T > using scram::core::Gate::Arg = std::pair<int, std::shared_ptr<T>>
An argument entry type in the gate's argument containers.
The entry contains the positive or negative index (indicating a complement) and the pointer to the argument node.
The constant version is to simulate transitive const so that the reference count of the argument cannot be changed.
Template Parameters
T The type of the argument node.
Definition at line 295 of file pdag.h.
template<class T > using scram::core::Gate::ConstArg = std::pair<int, const T&>
An argument entry type in the gate's argument containers.
The entry contains the positive or negative index (indicating a complement) and the pointer to the argument node.
The constant version is to simulate transitive const so that the reference count of the argument cannot be changed.
Template Parameters
T The type of the argument node.
Definition at line 297 of file pdag.h.
template<class T > using scram::core::Gate::ArgMap = ext::linear_map<int, std::shared_ptr<T>, ext::MoveEraser>
An associative container type to store the gate arguments.
This container type maps the index of the argument to the pointer to it.
Template Parameters
T The type of the argument node.
Definition at line 305 of file pdag.h.
Constructor & Destructor Documentation
scram::core::Gate::Gate (Connective type, Pdag * graph) noexcept
Creates an indexed gate with its unique index.
It is assumed that smart pointers are used to manage the graph, and one shared pointer exists for this gate to manage parent-child hierarchy.
Parameters
[in] type The type of this gate.
[in,out] graph The host PDAG.
Definition at line 59 of file pdag.cc.
Member Function Documentation
GatePtr scram::core::Gate::Clone () noexcept
Clones arguments and parameters.
The semantics of the gate is cloned, not the gate data like index and parents.
Returns
Shared pointer to a newly created gate.
Warning
This function does not destroy modules. If cloning destroys modules, module(false) member function must be called.
Definition at line 79 of file pdag.cc.
References BLOG, scram::DEBUG5, scram::core::Node::graph(), and scram::core::Node::index().
Connective scram::core::Gate::type () const inline
Returns
Type of this gate.
Definition at line 337 of file pdag.h.
Referenced by scram::core::Bdd::Analyze(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Preprocessor::GateSet::insert(), and scram::core::Zbdd::Zbdd().
void scram::core::Gate::type (Connective type)
Changes the logic of the gate.
Depending on the original and new type of the gate, the graph or gate properties may be changed or recorded.
Parameters
[in] type A new type for this gate.
Precondition
The new logic is compatible with the existing arguments and preserves the gate invariants.
The previous type is not equal to the new one.
Todo:
Find the inefficient resets.
Definition at line 71 of file pdag.cc.
int scram::core::Gate::min_number () const inline
Returns
Min number.
Precondition
The min number is relevant to the gate logic.
Definition at line 353 of file pdag.h.
Referenced by scram::core::Preprocessor::GateSet::insert().
void scram::core::Gate::min_number (int number) inline
Sets the min number for this gate.
This function is used for K/N gates.
Parameters
[in] number The min number of ATLEAST gate.
Precondition
The min number is appropriate for the gate logic and arguments.
Definition at line 361 of file pdag.h.
bool scram::core::Gate::constant () const inline
Returns
true if this gate has become constant.
Definition at line 364 of file pdag.h.
Referenced by scram::core::Bdd::Analyze(), scram::core::Bdd::Bdd(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Preprocessor::GateSet::insert(), scram::core::pdag::TopologicalOrder(), and scram::core::Zbdd::Zbdd().
const ArgSet& scram::core::Gate::args () const inline
Returns
The ordered set of argument indices of this gate.
Definition at line 367 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Analyze(), scram::core::Bdd::Bdd(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Preprocessor::GatherCommonNodes(), scram::core::Preprocessor::GatherModules(), scram::core::Preprocessor::GateSet::insert(), and scram::core::Zbdd::Zbdd().
template<class T > const ArgMap<T>& scram::core::Gate::args () inline
Generic accessor to the gate argument containers.
Template Parameters
T The type of the argument nodes.
Returns
The map container of the gate arguments with the given type.
Definition at line 375 of file pdag.h.
template<class T > auto scram::core::Gate::args () const inline
Provides const access to gate arguments w/o exposing the shared pointers.
The arguments are provided by reference.
Template Parameters
The type of the arguments.
Returns
Forward-iterable range with ConstArg value type.
Definition at line 393 of file pdag.h.
bool scram::core::Gate::mark () const inline
Marks are used for linear traversal of graphs.
This can be an alternative to visit information provided by the base Node class.
Returns
The mark of this gate.
Definition at line 405 of file pdag.h.
Referenced by scram::core::Preprocessor::GatherModules(), and scram::core::Preprocessor::GateSet::insert().
void scram::core::Gate::mark (bool flag) inline
Sets the mark of this gate.
Parameters
[in] flag Marking with the meaning for the marker.
Precondition
The marks are assigned in a top-down traversal.
The marks are continuous.
Definition at line 413 of file pdag.h.
int scram::core::Gate::descendant () const inline
Returns
Pre-assigned index of one of gate's descendants.
Definition at line 416 of file pdag.h.
Referenced by scram::core::Preprocessor::DecompositionProcessor::operator()().
void scram::core::Gate::descendant (int index) inline
Assigns a descendant index of this gate.
Parameters
[in] index Index of the descendant.
Definition at line 421 of file pdag.h.
int scram::core::Gate::ancestor () inline
Returns
Pre-assigned index of one of the gate's ancestors.
Definition at line 424 of file pdag.h.
void scram::core::Gate::ancestor (int index) inline
Assigns an ancestor index of this gate.
Parameters
[in] index Index of the ancestor.
Definition at line 429 of file pdag.h.
int scram::core::Gate::min_time () const inline override virtual
Returns
The minimum time of visits of the gate's sub-graph.
0 if no time assignment was performed.
Reimplemented from scram::core::Node.
Definition at line 433 of file pdag.h.
void scram::core::Gate::min_time (int time) inline
Sets the queried minimum visit time of the sub-graph.
Parameters
[in] time The positive min time of this gate's sub-graph.
Definition at line 438 of file pdag.h.
int scram::core::Gate::max_time () const inline override virtual
Returns
The maximum time of the visits of the gate's sub-graph.
0 if no time assignment was performed.
Reimplemented from scram::core::Node.
Definition at line 445 of file pdag.h.
void scram::core::Gate::max_time (int time) inline
Sets the queried maximum visit time of the sub-graph.
Parameters
[in] time The positive max time of this gate's sub-graph.
Definition at line 450 of file pdag.h.
bool scram::core::Gate::coherent () const inline
Returns
true if the whole graph of this gate is marked coherent.
Definition at line 456 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::FindOrAddVertex(), and scram::core::Zbdd::Zbdd().
void scram::core::Gate::coherent (bool flag) inline
Sets a coherence flag for the graph rooted by this gate.
Parameters
[in] flag true if the whole graph is coherent.
Definition at line 461 of file pdag.h.
bool scram::core::Gate::module () const inline
Returns
true if this gate is set to be a module.
Definition at line 464 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Analyze(), scram::core::Zbdd::FindOrAddVertex(), and scram::core::Zbdd::Zbdd().
void scram::core::Gate::module (bool flag) inline
Sets this gate's module flag.
Parameters
[in] flag true for modular gates.
Precondition
The gate has already been marked with an opposite flag.
Definition at line 471 of file pdag.h.
int scram::core::Gate::GetArgSign (const NodePtr & arg) const inline noexcept
Helper function to use the sign of the argument.
Parameters
[in] arg One of the arguments of this gate.
Returns
1 if the argument is positive.
-1 if the argument is negative (complement).
Warning
The function assumes that the argument exists. If it doesn't, the return value is invalid.
Definition at line 485 of file pdag.h.
NodePtr scram::core::Gate::GetArg (int index) const inline noexcept
Helper function for algorithms to get nodes from argument indices.
Parameters
[in] index Positive or negative index of the existing argument.
Returns
Pointer to the argument node of this gate.
Warning
The function assumes that the argument exists. If it doesn't, the behavior is undefined.
Never try to use dynamic casts to find the type of the node. There are other gate's helper functions that will avoid any need for the RTTI or other hacks.
Definition at line 502 of file pdag.h.
template<class T > void scram::core::Gate::AddArg (int index, const std::shared_ptr< T > & arg) inline noexcept
Adds an argument node to this gate.
Before adding the argument, the existing arguments are checked for complements and duplicates. If there is a complement, the gate may change its state (erasing its arguments) or type.
The duplicates are handled according to the logic of the gate. The caller must be aware of possible changes due to the logic of the gate.
Template Parameters
T The type of the argument node.
Parameters
[in] index A positive or negative index of an argument.
[in] arg A pointer to the argument node.
Warning
The function does not indicate invalid state. For example, a second argument for NOT or NULL type gates is not going to be reported in any way.
This function does not indicate error for future additions in case the state is nulled or becomes unity.
Duplicate arguments may change the type and state of the gate. Depending on the logic of the gate, new gates may be introduced instead of the existing arguments.
Complex logic gates like ATLEAST and XOR are handled specially if the argument is duplicate. The caller must be very cautious of the side effects of the manipulations.
Definition at line 545 of file pdag.h.
void scram::core::Gate::TransferArg (int index, const GatePtr & recipient) noexcept
Transfers this gate's argument to another gate.
Parameters
[in] index Positive or negative index of the argument.
[in,out] recipient A new parent for the argument.
Precondition
No constant arguments are present.
Definition at line 169 of file pdag.cc.
References scram::core::Node::index().
void scram::core::Gate::ShareArg (int index, const GatePtr & recipient) noexcept
Shares this gate's argument with another gate.
Parameters
[in] index Positive or negative index of the argument.
[in,out] recipient Another parent for the argument.
Precondition
No constant arguments are present.
Definition at line 188 of file pdag.cc.
void scram::core::Gate::NegateArgs () noexcept
Makes all arguments complements of themselves.
This is a helper function to propagate a complement gate and apply the De Morgan's Law.
Precondition
No constant arguments are present.
Todo:
Consider in place inversion.
Definition at line 199 of file pdag.cc.
void scram::core::Gate::NegateArg (int existing_arg) noexcept
Replaces an argument with the complement of it.
This is a helper function to propagate a complement gate and apply the De Morgan's Law.
Parameters
[in] existing_arg Positive or negative index of the argument.
Precondition
No constant arguments are present.
Definition at line 213 of file pdag.cc.
void scram::core::Gate::NegateNonCoherentGateArgs () inline noexcept
Turns all non-coherent arguments of type gate (NOT, NAND, etc.) into complement arguments.
This is a helper function for gate normalization to efficiently normalize non-coherent gates.
Definition at line 610 of file pdag.h.
void scram::core::Gate::CoalesceGate (const GatePtr & arg_gate) noexcept
Adds arguments of an argument gate to this gate.
This is a helper function for gate coalescing. The argument gate of the same logic is removed from the arguments list. The sign of the argument gate is expected to be positive.
Parameters
[in] arg_gate The gate which arguments to be added to this gate.
Precondition
No constant arguments are present.
Warning
This function does not test if the parent and argument logics are correct for coalescing.
Definition at line 230 of file pdag.cc.
References scram::core::Node::index().
void scram::core::Gate::JoinNullGate (int index) noexcept
Swaps a single argument of a NULL type argument gate.
This is separate from other coalescing functions because this function takes into account the sign of the argument.
Parameters
[in] index Positive or negative index of the argument gate.
Definition at line 252 of file pdag.cc.
References scram::core::Node::index().
void scram::core::Gate::ProcessConstantArg (const NodePtr & arg, bool state) noexcept
Changes the state of a gate or removes a constant argument.
The function determines its actions depending on the type of the gate and state of an argument.
Parameters
[in] arg The pointer the argument of this gate.
[in] state False or True constant state of the argument.
Note
This is a helper function that propagates constants.
This function takes into account the sign of the index to properly assess the Boolean constant argument.
This function may change the state of the gate.
This function may change type and parameters of the gate.
Definition at line 279 of file pdag.cc.
void scram::core::Gate::EraseArg (int index) noexcept
Removes an argument from the arguments container.
The passed argument index must be in this gate's arguments container and initialized.
Parameters
[in] index The positive or negative index of the existing argument.
Warning
The parent gate may become empty or one-argument gate, which must be handled by the caller.
Definition at line 287 of file pdag.cc.
References scram::core::Node::index().
void scram::core::Gate::MakeConstant (bool state) noexcept
Sets the logic of this gate to pass-through and clears all its arguments except for a Boolean constant.
This function is expected to be used only once.
Parameters
[in] state The value for the Boolean constant.
Definition at line 322 of file pdag.cc.
References scram::core::Pdag::constant(), scram::DEBUG5, scram::core::Node::graph(), scram::core::Node::index(), and LOG.
template<> void scram::core::Gate::AddArg (int index, const ConstantPtr & arg) noexcept
Specialization to handle Boolean constants in arguments.
Adds an argument node to this gate. Before adding the argument, the existing arguments are checked for complements and duplicates. If there is a complement, the gate may change its state (erasing its arguments) or type.
The duplicates are handled according to the logic of the gate. The caller must be aware of possible changes due to the logic of the gate.
Template Parameters
T The type of the argument node.
Parameters
[in] index A positive or negative index of an argument.
[in] arg A pointer to the argument node.
Warning
The function does not indicate invalid state. For example, a second argument for NOT or NULL type gates is not going to be reported in any way.
This function does not indicate error for future additions in case the state is nulled or becomes unity.
Duplicate arguments may change the type and state of the gate. Depending on the logic of the gate, new gates may be introduced instead of the existing arguments.
Complex logic gates like ATLEAST and XOR are handled specially if the argument is duplicate. The caller must be very cautious of the side effects of the manipulations.
The documentation for this class was generated from the following files:
pdag.h
pdag.cc