scram::mef::Element Class Reference
scram::mef::Element Class Reference
The MEF Element with attributes and a label.
#include <element.h>
Public Types
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Public Member Functions
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Protected Member Functions
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Detailed Description
The MEF Element with attributes and a label.
This is a base/mixin class for most of the MEF constructs.
Note
The class is not polymorphic.
Definition at line 135 of file element.h.
Member Typedef Documentation
using scram::mef::Element::AttributeMap = ext::linear_set<Attribute, AttributeKey>
Unique attribute map keyed with the attribute names.
Note
Elements are expected to have very few attributes, complex containers may be overkill.
Using a multi-index or other tables incurs a huge memory overhead in common usage (up to 400B / attribute).
Definition at line 151 of file element.h.
Constructor & Destructor Documentation
scram::mef::Element::Element (std::string name) explicit
Constructs an element with an original name.
The name is expected to conform to identifier requirements described in the MEF documentation and additions.
Parameters
[in] name The local identifier name.
Exceptions
LogicError The name is required and empty.
ValidityError The name is malformed.
Definition at line 25 of file element.cc.
References name().
Member Function Documentation
const std::string& scram::mef::Element::name () const inline
Returns
The original name.
Definition at line 164 of file element.h.
Referenced by scram::mef::Component::Add(), scram::mef::CcfGroup::AddDistribution(), scram::mef::CcfGroup::AddFactor(), scram::mef::CcfGroup::AddMember(), scram::core::EventTreeAnalysis::Analyze(), scram::core::RiskAnalysis::Analyze(), scram::mef::CcfEvent::CcfEvent(), scram::mef::Initializer::Define(), Element(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::ExternLibrary::ExternLibrary(), scram::mef::Fork::Fork(), scram::mef::Component::GatherGates(), GetAttribute(), scram::mef::Model::GetEvent(), scram::mef::Model::GetOptionalName(), scram::mef::cycle::GetUniqueName(), scram::mef::Model::HasDefaultName(), scram::mef::Id::id(), scram::mef::Model::Model(), scram::mef::Phase::Phase(), RemoveAttribute(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::mef::Serialize(), scram::mef::Model::SetOptionalName(), scram::mef::Id::unique_name(), scram::mef::Alignment::Validate(), scram::mef::Substitution::Validate(), scram::mef::BasicEvent::Validate(), and scram::mef::CcfGroup::Validate().
std::string_view scram::mef::Element::name_view () const inline
Returns
The string view to the name for table keys.
Definition at line 167 of file element.h.
Referenced by attributes().
const std::string& scram::mef::Element::label () const inline
Returns
The empty or preset label.
Empty string if the label has not been set.
Definition at line 171 of file element.h.
Referenced by scram::mef::Serialize().
void scram::mef::Element::label (std::string label) inline
Sets the element label.
Parameters
[in] label The extra description for the element.
Definition at line 176 of file element.h.
const AttributeMap& scram::mef::Element::attributes () const inline
Returns
The current set of element attributes (non-inherited!).
Note
The element attributes override its inherited attributes. However, the inherited attributes are not copied into the map. The precedence is followed upon lookup.
Definition at line 183 of file element.h.
References name_view().
Referenced by scram::mef::Serialize().
void scram::mef::Element::AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
Parameters
[in] attr An attribute of this element.
Exceptions
ValidityError The attribute is duplicate.
Warning
Pointers or references to existing attributes may get invalidated.
Definition at line 35 of file element.cc.
References ext::linear_set< Value, KeyFromValue, Sequence >::insert(), scram::mef::Attribute::name(), and SCRAM_THROW.
void scram::mef::Element::SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
If an attribute with the same name exits, it gets overwritten.
Parameters
[in] attr An attribute of this element.
Warning
Pointers or references to existing attributes may get invalidated.
Definition at line 42 of file element.cc.
References ext::linear_set< Value, KeyFromValue, Sequence >::insert().
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const Attribute * scram::mef::Element::GetAttribute (std::string_view name) const noexcept
Parameters
[in] name The name of the attribute.
Returns
The attribute with the given name. nullptr if no attribute is found.
Warning
Attribute addresses are not stable. Do not store the returned pointer.
Note
Attributes can be inherited from parent containers.
Definition at line 48 of file element.cc.
References scram::mef::ContainerElement::container(), ext::linear_set< Value, KeyFromValue, Sequence >::end(), ext::linear_set< Value, KeyFromValue, Sequence >::find(), GetAttribute(), and name().
Referenced by GetAttribute().
std::optional< Attribute > scram::mef::Element::RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Parameters
[in] name The identifying name of the attribute.
Returns
The removed attribute if any.
Postcondition
No inherited attributes are affected.
Definition at line 57 of file element.cc.
References ext::linear_set< Value, KeyFromValue, Sequence >::end(), ext::linear_set< Value, KeyFromValue, Sequence >::erase(), ext::linear_set< Value, KeyFromValue, Sequence >::find(), and name().
void scram::mef::Element::name (std::string name) protected
Resets the element name.
Parameters
[in] name The local identifier name.
Exceptions
LogicError The name is required and empty.
ValidityError The name is malformed.
Definition at line 27 of file element.cc.
References SCRAM_THROW.
The documentation for this class was generated from the following files:
element.h
element.cc