scram::core::ProbabilityAnalysis Class Reference
scram::core::ProbabilityAnalysis Class Reference abstract
Main quantitative analysis class.
#include <probability_analysis.h>
Public Member Functions
ProbabilityAnalysis (const FaultTreeAnalysis *fta, mef::MissionTime *mission_time)
Probability analysis with the results of qualitative analysis.
void Analyze () noexcept
Performs quantitative analysis on the supplied fault tree.
double p_total () const
const std::vector< std::pair< double, double > > & p_time () const
const Sil & sil () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Protected Member Functions
mef::MissionTime & mission_time ()
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Main quantitative analysis class.
Definition at line 57 of file probability_analysis.h.
Constructor & Destructor Documentation
scram::core::ProbabilityAnalysis::ProbabilityAnalysis (const FaultTreeAnalysis * fta, mef::MissionTime * mission_time)
Probability analysis with the results of qualitative analysis.
Parameters
[in] fta Fault tree analysis with results.
[in] mission_time The mission time expression of the model.
Precondition
The underlying fault tree must not have changed in any way since the fault tree analysis finished.
Definition at line 34 of file probability_analysis.cc.
Member Function Documentation
void scram::core::ProbabilityAnalysis::Analyze () noexcept
Performs quantitative analysis on the supplied fault tree.
Precondition
Analysis is called only once.
Postcondition
The mission time expression has its original value.
Todo:
Use Boost math integration instead.
Definition at line 38 of file probability_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::Analysis::AddWarning(), CLOCK, scram::DEBUG3, DUR, LOG, p_time(), and scram::core::Analysis::settings().
double scram::core::ProbabilityAnalysis::p_total () const inline
Returns
The total probability calculated by the analysis.
Precondition
The analysis is done.
Definition at line 82 of file probability_analysis.h.
Referenced by scram::core::ImportanceAnalyzerBase::prob_analyzer(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<std::pair<double, double> >& scram::core::ProbabilityAnalysis::p_time () const inline
Returns
The probability values over the mission time in time steps. The empty container implies no calculation has been done.
Precondition
The analysis is done.
Definition at line 88 of file probability_analysis.h.
Referenced by Analyze(), scram::core::McubCalculator::Calculate(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const Sil& scram::core::ProbabilityAnalysis::sil () const inline
Returns
The Safety Integrity Level calculation results.
Precondition
The analysis is done with a request for the SIL.
Definition at line 95 of file probability_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
mef::MissionTime& scram::core::ProbabilityAnalysis::mission_time () inline protected
Returns
The mission time expression of the model.
Definition at line 102 of file probability_analysis.h.
Referenced by scram::core::McubCalculator::Calculate().
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc