scram::core::Analysis Class Reference
scram::core::Analysis Class Reference abstract
Base abstract class for all analysis with settings.
#include <analysis.h>
Public Member Functions
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Protected Member Functions
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Base abstract class for all analysis with settings.
Definition at line 34 of file analysis.h.
Constructor & Destructor Documentation
scram::core::Analysis::Analysis (Settings settings) explicit
Parameters
[in] settings Analysis settings for all calculations.
Definition at line 25 of file analysis.cc.
References ~Analysis().
scram::core::Analysis::~Analysis () pure virtual default
Abstract class.
Pure virtual destructor.
Referenced by Analysis().
Member Function Documentation
const Settings& scram::core::Analysis::settings () const inline
Returns
Analysis settings.
Definition at line 42 of file analysis.h.
Referenced by scram::core::ProbabilityAnalysis::Analyze(), scram::core::RiskAnalysis::Analyze(), scram::core::FaultTreeAnalysis::Analyze(), scram::core::McubCalculator::Calculate(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), scram::Reporter::Report(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::core::UncertaintyAnalysis::SampleExpressions().
const std::string& scram::core::Analysis::warnings () const inline
Returns
Warnings generated upon analysis.
Definition at line 45 of file analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
double scram::core::Analysis::analysis_time () const inline
Returns
Time taken by the analysis.
Definition at line 48 of file analysis.h.
Referenced by scram::core::UncertaintyAnalysis::Analyze(), and scram::core::FaultTreeAnalysis::Analyze().
Settings& scram::core::Analysis::settings () inline protected
Returns
Modifiable analysis settings.
Definition at line 52 of file analysis.h.
void scram::core::Analysis::AddWarning (std::string msg) inline protected
Appends a warning message to the analysis warnings.
Warnings are separated by spaces.
Parameters
[in] msg Informative message without special characters.
Definition at line 58 of file analysis.h.
Referenced by scram::core::ProbabilityAnalysis::Analyze(), and scram::core::FaultTreeAnalysis::Analyze().
void scram::core::Analysis::AddAnalysisTime (double time) inline protected
Adds time to the total analysis time.
Parameters
[in] time Additional time spent on analysis.
Definition at line 66 of file analysis.h.
Referenced by scram::core::UncertaintyAnalysis::Analyze(), scram::core::ImportanceAnalysis::Analyze(), scram::core::ProbabilityAnalysis::Analyze(), scram::core::FaultTreeAnalysis::Analyze(), and scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability().
The documentation for this class was generated from the following files:
analysis.h
analysis.cc