scram::core::FaultTreeAnalysis Class Reference
scram::core::FaultTreeAnalysis Class Reference abstract
Fault tree analysis functionality.
#include <fault_tree_analysis.h>
Public Member Functions
FaultTreeAnalysis (const mef::Gate &root, const Settings &settings, const mef::Model *model=nullptr)
Traverses a valid fault tree from the root gate to collect databases of events, gates, and other members of the fault tree.
const mef::Gate & top_event () const
void Analyze () noexcept
Analyzes the fault tree and performs computations.
const ProductContainer & products () const
Public Member Functions inherited from scram::core::Analysis
Analysis (Settings settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Protected Member Functions
const Pdag * graph () const
Protected Member Functions inherited from scram::core::Analysis
Settings & settings ()
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Fault tree analysis functionality.
The analysis must be done on a validated and fully initialized fault trees. After initialization of the analysis, the fault tree under analysis should not change; otherwise, the success of the analysis is not guaranteed, and the results may be invalid. After the requested analysis is done, the fault tree can be changed without restrictions. However, other analyses may rely on unchanged fault tree to use the results of this fault tree analysis.
To conduct a new analysis on the changed fault tree, a new FaultTreeAnalysis object must be created. In general, rerunning the same analysis twice will mess up the analysis and corrupt the previous results.
Warning
Run analysis only once. One analysis per FaultTreeAnalysis object.
Definition at line 193 of file fault_tree_analysis.h.
Constructor & Destructor Documentation
scram::core::FaultTreeAnalysis::FaultTreeAnalysis (const mef::Gate & root, const Settings & settings, const mef::Model * model = nullptr)
Traverses a valid fault tree from the root gate to collect databases of events, gates, and other members of the fault tree.
The passed fault tree must be pre-validated without cycles, and its events must be fully initialized.
Parameters
[in] root The top event of the fault tree to analyze.
[in] settings Analysis settings for all calculations.
[in] model The Model containing substitutions if any.
Note
It is assumed that analysis is done only once.
Warning
If the fault tree structure is changed, this analysis does not incorporate the changed structure. Moreover, the analysis results may get corrupted.
Definition at line 115 of file fault_tree_analysis.cc.
Member Function Documentation
const mef::Gate& scram::core::FaultTreeAnalysis::top_event () const inline
Returns
The top gate that is passed to the analysis.
Definition at line 216 of file fault_tree_analysis.h.
Referenced by scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability().
void scram::core::FaultTreeAnalysis::Analyze () noexcept
Analyzes the fault tree and performs computations.
This function must be called only after initializing the fault tree with or without its probabilities.
Note
This function is expected to be called only once.
Warning
If the original fault tree is invalid, this function will not throw or indicate any errors. The behavior is undefined for invalid fault trees.
If the fault tree structure has changed since the construction of the analysis, the analysis will be invalid or fail.
Definition at line 120 of file fault_tree_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::Analysis::AddWarning(), scram::core::Analysis::analysis_time(), scram::core::Zbdd::base(), scram::core::Settings::ccf_analysis(), CLOCK, scram::DEBUG2, DUR, scram::core::Zbdd::empty(), graph(), scram::core::Settings::limit_order(), LOG, scram::core::Settings::preprocessor, scram::core::Print(), scram::core::Settings::print, products(), scram::core::Analysis::settings(), and scram::core::Zbdd::size().
const ProductContainer& scram::core::FaultTreeAnalysis::products () const inline
Returns
A collection of Boolean products as the analysis results.
Precondition
The analysis is done.
Definition at line 236 of file fault_tree_analysis.h.
Referenced by Analyze(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const Pdag* scram::core::FaultTreeAnalysis::graph () const inline protected
Returns
Pointer to the PDAG representing the fault tree.
Definition at line 243 of file fault_tree_analysis.h.
Referenced by Analyze().
The documentation for this class was generated from the following files:
fault_tree_analysis.h
fault_tree_analysis.cc