scram::mef::Formula::ArgSet Class Reference
scram::mef::Formula::ArgSet Class Reference
The set of formula arguments.
#include <event.h>
Public Member Functions
ArgSet ()=default
Default constructor of an empty argument set.
void Add (ArgEvent event, bool complement=false)
Adds an event into the arguments set.
void Add (Arg arg)
Overload to add formula argument with a structure.
void Remove (ArgEvent event)
Removes an event from the formula.
std::size_t size () const
bool empty () const
ArgSet (std::initializer_list< Arg > init_list)
Constructors from initializer lists and iterator ranges of args.
ArgSet (std::initializer_list< ArgEvent > init_list)
Constructors from initializer lists and iterator ranges of args.
template<typename Iterator >
ArgSet (Iterator first1, Iterator last1)
Constructors from initializer lists and iterator ranges of args.
const std::vector< Arg > & data () const
std::vector< Arg > & data ()
Detailed Description
The set of formula arguments.
Definition at line 238 of file event.h.
Member Function Documentation
void scram::mef::Formula::ArgSet::Add (ArgEvent event, bool complement = false)
Adds an event into the arguments set.
Parameters
[in] event An argument event.
[in] complement Indicate the negation of the argument event.
Exceptions
DuplicateElementError The argument event is duplicate.
Definition at line 52 of file event.cc.
References scram::mef::Formula::Arg::event, scram::mef::Id::id(), SCRAM_THROW, and scram::mef::Usage::usage().
Referenced by scram::core::EventTreeAnalysis::Analyze(), scram::mef::Initializer::Define(), and scram::core::EventTreeAnalysis::EventTreeAnalysis().
void scram::mef::Formula::ArgSet::Remove (ArgEvent event)
Removes an event from the formula.
Parameters
[in] event The argument event of this formula.
Exceptions
LogicError The argument is not in the set.
Definition at line 65 of file event.cc.
References scram::mef::Formula::Arg::event, and SCRAM_THROW.
const std::vector<Arg>& scram::mef::Formula::ArgSet::data () const inline
Returns
The underlying container with the data.
Definition at line 278 of file event.h.
Referenced by scram::mef::Formula::Formula(), and scram::mef::Formula::Swap().
std::vector<Arg>& scram::mef::Formula::ArgSet::data () inline
Returns
The underlying container with the data.
Definition at line 279 of file event.h.
std::size_t scram::mef::Formula::ArgSet::size () const inline
Returns
The number of arguments in the set.
Definition at line 283 of file event.h.
Referenced by scram::mef::Formula::Swap().
bool scram::mef::Formula::ArgSet::empty () const inline
Returns
true if the set is empty.
Definition at line 286 of file event.h.
Referenced by scram::mef::Initializer::Define(), and scram::mef::Formula::Swap().
The documentation for this class was generated from the following files:
event.h
event.cc