scram::mef::LognormalDeviate Class Reference
scram::mef::LognormalDeviate Class Reference
Log-normal distribution.
#include <random_deviate.h>
Public Member Functions
LognormalDeviate (Expression *mean, Expression *ef, Expression *level)
The log-normal deviate parametrization with its expected value and error factor of certain confidence level.
LognormalDeviate (Expression *mu, Expression *sigma)
The parametrization with underlying normal distribution parameters.
void Validate () const override
Validates the expression.
double value () noexceptoverride
Interval interval () noexceptoverride
The high is 99.9 percentile estimate.
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Static Public Member Functions inherited from scram::mef::RandomDeviate
static void seed (unsigned seed) noexcept
Sets the seed of the underlying random number generator.
Protected Member Functions inherited from scram::mef::RandomDeviate
std::mt19937 & rng ()
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Log-normal distribution.
Definition at line 115 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::LognormalDeviate::LognormalDeviate (Expression * mean, Expression * ef, Expression * level)
The log-normal deviate parametrization with its expected value and error factor of certain confidence level.
Parameters
[in] mean The mean of the log-normal distribution not the mean of underlying normal distribution, which is parameter mu. mu is the location parameter, sigma is the scale factor. E(x) = exp(mu + sigma^2 / 2)
[in] ef The error factor of the log-normal distribution. EF = exp(z_alpha * sigma)
[in] level The confidence level.
Definition at line 70 of file random_deviate.cc.
scram::mef::LognormalDeviate::LognormalDeviate (Expression * mu, Expression * sigma)
The parametrization with underlying normal distribution parameters.
Parameters
[in] mu The mean of the normal distribution.
[in] sigma The standard deviation of the normal distribution.
Definition at line 75 of file random_deviate.cc.
References scram::mef::RandomDeviate::rng(), and SCRAM_THROW.
Member Function Documentation
void scram::mef::LognormalDeviate::Validate () const inline override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
DomainError The argument value domains are invalid.
ValidityError The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 137 of file random_deviate.h.
double scram::mef::LognormalDeviate::value () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 138 of file random_deviate.h.
References scram::mef::Expression::interval(), scram::mef::Expression::Validate(), and scram::mef::Expression::value().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc