scram::Reporter Class Reference
scram::Reporter Class Reference
Facilities to report analysis results.
#include <reporter.h>
Public Member Functions
void Report (const core::RiskAnalysis &risk_an, std::FILE *out, bool indent=true)
Reports the results of risk analysis on a model.
void Report (const core::RiskAnalysis &risk_an, const std::string &file, bool indent=true)
A convenience function to generate the report into a file.
Detailed Description
Facilities to report analysis results.
Definition at line 40 of file reporter.h.
Member Function Documentation
void scram::Reporter::Report (const core::RiskAnalysis & risk_an, std::FILE * out, bool indent = true)
Reports the results of risk analysis on a model.
The XML report is formed as a single document.
Parameters
[in] risk_an Risk analysis with results.
[out] out The report destination stream.
[in] indent The flag to indent output for readability.
Precondition
The output destination is used only by this reporter. There is going to be no appending to the stream after the report.
Exceptions
IOError The write operation has failed.
Definition at line 71 of file reporter.cc.
References scram::xml::StreamElement::AddChild(), scram::DEBUG1, scram::core::RiskAnalysis::event_tree_results(), scram::core::Settings::probability_analysis(), scram::core::RiskAnalysis::results(), scram::xml::Stream::root(), scram::core::Analysis::settings(), and TIMER.
Referenced by Report().
void scram::Reporter::Report (const core::RiskAnalysis & risk_an, const std::string & file, bool indent = true)
A convenience function to generate the report into a file.
This function overwrites the file.
Parameters
[in] risk_an Risk analysis with results.
[out] file The output destination.
[in] indent The flag to indent output for readability.
Exceptions
IOError The output file is not accessible, or the write operation has failed.
Definition at line 104 of file reporter.cc.
References Report(), and SCRAM_THROW.
The documentation for this class was generated from the following files:
reporter.h
reporter.cc