scram::mef::Fork Class Reference
scram::mef::Fork Class Reference
Functional event forks.
#include <event_tree.h>
Public Member Functions
Fork (const FunctionalEvent &functional_event, std::vector< Path > paths)
const FunctionalEvent & functional_event () const
const std::vector< Path > & paths () const
std::vector< Path > & paths ()
Detailed Description
Functional event forks.
Definition at line 140 of file event_tree.h.
Constructor & Destructor Documentation
scram::mef::Fork::Fork (const FunctionalEvent & functional_event, std::vector< Path > paths)
Parameters
[in] functional_event The source functional event.
[in] paths The fork paths with functional event states.
Exceptions
ValidityError The path states are duplicated.
Definition at line 35 of file event_tree.cc.
References scram::mef::Element::name(), and SCRAM_THROW.
Member Function Documentation
const FunctionalEvent& scram::mef::Fork::functional_event () const inline
Returns
The functional event of the fork.
Definition at line 149 of file event_tree.h.
Referenced by scram::core::EventTreeAnalysis::Analyze().
const std::vector<Path>& scram::mef::Fork::paths () const inline
Returns
The fork paths with functional event states.
Definition at line 153 of file event_tree.h.
Referenced by scram::core::EventTreeAnalysis::Analyze(), and scram::mef::cycle::ContinueConnector().
std::vector<Path>& scram::mef::Fork::paths () inline
Returns
The fork paths with functional event states.
Definition at line 154 of file event_tree.h.
The documentation for this class was generated from the following files:
event_tree.h
event_tree.cc