scram::core::Pdag Class Reference
scram::core::Pdag Class Reference
PDAG is a propositional directed acyclic graph.
#include <pdag.h>
Classes
class NodeIndexGenerator
Generator of unique indices for graph nodes.
class NullGateRegistrar
Registers pass-through or Null logic gates belonging to the graph.
struct Substitution
Non-declarative substitutions.
Public Types
enum NodeMark {
kGateMark, kVisit, kCount, kOptiValue,
kDescendant, kAncestor, kOrder
}
Various kinds of marks applied to the nodes.
template<typename T >
using IndexMap = ext::index_map< kVariableStartIndex, T >
Sequential mapping of Variable indices to other data of type T.
Public Member Functions
Pdag () noexcept
Constructs a graph with no root gate ready for general purpose (test) Boolean formulas.
Pdag (const mef::Gate &root, bool ccf=false, const mef::Model *model=nullptr) noexcept
Constructs a PDAG starting from the top gate of a fault tree.
const std::vector< Substitution > & substitutions () const
bool coherent () const
void coherent (bool flag)
bool normal () const
void normal (bool flag)
const GatePtr & root ()
const Gate & root () const
void root (const GatePtr &gate)
Sets the root gate.
const ConstantPtr & constant () const
bool HasConstants () const
bool HasNullGates () const
bool IsTrivial () const
bool IsTrivial () noexcept
Attempts to make the graph trivial if possible.
const IndexMap< const mef::BasicEvent * > & basic_events () const
void Print ()
Prints the PDAG in the Aralia format.
void Log () noexcept
Writes PDAG properties into logs.
void RemoveNullGates () noexcept
Removes gates of Null logic with a single argument (maybe constant).
template<NodeMark Mark>
void Clear () noexcept
Clears marks from graph nodes.
template<NodeMark Mark>
void Clear (const GatePtr &gate) noexcept
Determines the proper "clear" state for the graph node mark, and set the clear mark to nodes starting from the given gate.
bool complement () const
bool & complement ()
Static Public Attributes
static const int kVariableStartIndex = 2
The shift value for mapping.
Detailed Description
PDAG is a propositional directed acyclic graph.
This class provides a simpler representation of a fault tree that takes into account the indices of events instead of IDs and pointers. This graph can also be called an indexed fault tree.
This class is designed to help preprocessing and other graph transformation functions.
Precondition
There are no shared pointers to any other graph gate except for the root gate of the graph upon graph transformations. Extra reference count will prevent automatic deletion of the node and management of the structure of the graph. Moreover, the graph may become a multi-root graph, which is not the assumption of all the other preprocessing and analysis algorithms.
Definition at line 781 of file pdag.h.
Member Enumeration Documentation
enum scram::core::Pdag::NodeMark
Various kinds of marks applied to the nodes.
Enumerator
kGateMark
General graph traversal (dirty upon traversal end!).
kVisit
General visit times for graph nodes.
Definition at line 820 of file pdag.h.
Constructor & Destructor Documentation
scram::core::Pdag::Pdag () noexcept
Constructs a graph with no root gate ready for general purpose (test) Boolean formulas.
Definition at line 449 of file pdag.cc.
scram::core::Pdag::Pdag (const mef::Gate & root, bool ccf = false, const mef::Model * model = nullptr) explicit noexcept
Constructs a PDAG starting from the top gate of a fault tree.
Upon construction, features of the fault tree are recorded to help preprocessing and analysis functions.
Parameters
[in] root The top gate of the fault tree.
[in] ccf Incorporation of CCF gates and events for CCF groups.
[in] model The Model containing substitutions if any.
Precondition
No new Variable nodes are introduced after the construction.
Postcondition
All declarative substitutions are applied, and all non-declarative substitutions are collected for application.
The PDAG is stable as long as the argument fault tree and its underlying containers are stable. If the fault tree has been manipulated (event addition, etc.), its PDAG representation is not guaranteed to be the same.
The index assignment for variables is special: index in [kVariableStartIndex, num of vars + kVariableStartIndex). This indexing technique helps preprocessing and analysis algorithms optimize their work with basic events.
All Gate indices >= (num of vars + kVariableStartIndex).
Definition at line 457 of file pdag.cc.
References scram::DEBUG2, and TIMER.
Member Function Documentation
const std::vector<Substitution>& scram::core::Pdag::substitutions () const inline
Returns
Non-declarative substitutions to be applied by analysis.
Definition at line 865 of file pdag.h.
bool scram::core::Pdag::coherent () const inline
Returns
true if the fault tree is coherent.
Definition at line 870 of file pdag.h.
void scram::core::Pdag::coherent (bool flag) inline
Parameters
[in] flag true if fault tree doesn't contain non-coherent gates.
Todo:
Implement automatic tracking/marking of coherence.
Definition at line 875 of file pdag.h.
bool scram::core::Pdag::normal () const inline
Returns
true if all gates of the fault tree are normalized AND/OR.
Definition at line 878 of file pdag.h.
void scram::core::Pdag::normal (bool flag) inline
Parameters
[in] flag true if the graph has been normalized.
Todo:
Consider processing and tracking internally.
Definition at line 883 of file pdag.h.
const GatePtr& scram::core::Pdag::root () inline
Returns
The shared pointer to current root gate of the graph. nullptr iff the graph has been constructed root-less.
Definition at line 887 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Bdd(), and scram::core::operator<<().
const Gate& scram::core::Pdag::root () const inline
Returns
The current root gate of the graph.
Precondition
The graph has been constructed with a root gate.
Definition at line 892 of file pdag.h.
void scram::core::Pdag::root (const GatePtr & gate) inline
Sets the root gate.
This function is helpful for transformations.
Parameters
[in] gate Replacement root gate.
Definition at line 898 of file pdag.h.
bool scram::core::Pdag::complement () const inline
Returns
true if graph = ~root.
Definition at line 906 of file pdag.h.
Referenced by scram::core::Bdd::Bdd(), and scram::core::Mocus::Mocus().
bool& scram::core::Pdag::complement () inline
Returns
true if graph = ~root.
Definition at line 907 of file pdag.h.
const ConstantPtr& scram::core::Pdag::constant () const inline
Returns
The single Boolean constant for the whole graph.
Todo:
Consider limiting access to transform functions and gates.
Definition at line 913 of file pdag.h.
Referenced by scram::core::Gate::MakeConstant(), and scram::core::operator<<().
bool scram::core::Pdag::HasConstants () const inline
Returns
true if the graph contains pass-through gates with a constant.
Definition at line 916 of file pdag.h.
bool scram::core::Pdag::HasNullGates () const inline
Returns
true if the graph has at least one pass-through logic gate.
Definition at line 919 of file pdag.h.
bool scram::core::Pdag::IsTrivial () const inline
Returns
true if the graph represents a trivial Boolean function; that is, graph = Constant or graph = Variable. The only gate is the root pass-through to the simple arg.
Note
The root gate may be swapped with a new one.
Definition at line 926 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Bdd(), and scram::core::pdag::Transform().
bool scram::core::Pdag::IsTrivial () noexcept
Attempts to make the graph trivial if possible.
Returns
true if the graph is trivial or made trivial.
Todo:
Enable the code by decoupling the order assignment!
Todo:
Decouple the order assignment!
Definition at line 759 of file pdag.cc.
References begin, BLOG, scram::DEBUG3, scram::DEBUG4, and LOG.
const IndexMap<const mef::BasicEvent*>& scram::core::Pdag::basic_events () const inline
Returns
Original basic event as initialized in this indexed fault tree. The Variable indices map directly to the original basic events.
Precondition
No new Variable nodes are introduced after the construction.
Definition at line 941 of file pdag.h.
References scram::core::Print().
Referenced by scram::core::Mocus::Analyze().
void scram::core::Pdag::Print ()
Prints the PDAG in the Aralia format.
This is a helper for logging and debugging. The output is the standard error.
Warning
Node visits are used.
Definition at line 486 of file pdag.cc.
void scram::core::Pdag::Log () noexcept
Writes PDAG properties into logs.
Precondition
The graph is valid and well formed.
Logging cutoff level is Debug 4 or higher.
Postcondition
Gate marks are clear.
Warning
Gate marks are manipulated.
Definition at line 890 of file pdag.cc.
References BLOG, scram::DEBUG4, scram::DEBUG5, LOG, and scram::Logger::report_level().
void scram::core::Pdag::RemoveNullGates () noexcept
Removes gates of Null logic with a single argument (maybe constant).
That one child arg is transferred to the parent gate, and the original argument gate is removed from the parent gate.
All Boolean constants from the PDAG are removed according to the Boolean logic of the gates upon passing these args to parent gates.
Postcondition
If there's still a Null logic gate, then it's the root of the graph with a single variable/constant, and no further processing is required.
If there's still a constant, it belongs to the root gate, and the whole graph is constant, so no further processing is required.
Warning
Gate marks will get cleared by this function.
Definition at line 795 of file pdag.cc.
References BLOG, scram::DEBUG5, gate_types, gates, num_modules, scram::core::TraverseGates(), and variables.
template<NodeMark Mark> void scram::core::Pdag::Clear () inline noexcept
Clears marks from graph nodes.
Template Parameters
Mark The kind of the mark.
Definition at line 986 of file pdag.h.
References gates, and variables.
template<Pdag::NodeMark Mark> void scram::core::Pdag::Clear (const GatePtr & gate) noexcept
Determines the proper "clear" state for the graph node mark, and set the clear mark to nodes starting from the given gate.
Template Parameters
Mark The kind of the mark.
Parameters
[in,out] gate The root gate to start the traversal and cleaning.
Precondition
The gate marks are usable for traversal (clear, continuous, etc.).
Definition at line 1177 of file pdag.h.
References scram::core::operator<<(), scram::core::TraverseGates(), and scram::core::TraverseNodes().
Member Data Documentation
const int scram::core::Pdag::kVariableStartIndex = 2 static
The shift value for mapping.
Definition at line 783 of file pdag.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::ImportanceAnalysis::Analyze(), and scram::core::UncertaintyAnalysis::GatherDeviateExpressions().
The documentation for this class was generated from the following files:
pdag.h
pdag.cc