scram::mef::Role Class Reference
scram::mef::Role Class Reference
Mixin class that manages private or public roles for elements as needed.
#include <element.h>
Public Member Functions
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Detailed Description
Mixin class that manages private or public roles for elements as needed.
Public is the default assumption. It is expected to be set only once and never change.
Definition at line 265 of file element.h.
Constructor & Destructor Documentation
scram::mef::Role::Role (RoleSpecifier role = RoleSpecifier::kPublic, std::string base_path = "") explicit
Sets the role of an element upon creation.
The base reference path must be formatted according to the MEF documentation and additions.
Parameters
[in] role A role specifier of the element.
[in] base_path The series of containers to get this event.
Exceptions
ValidityError The base path string is malformed.
ValidityError Private element at model/global scope.
Definition at line 67 of file element.cc.
References SCRAM_THROW.
Member Function Documentation
RoleSpecifier scram::mef::Role::role () const inline
Returns
The assigned role of the element.
Definition at line 280 of file element.h.
Referenced by scram::mef::Initializer::Define(), scram::mef::Id::id(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), and scram::mef::Serialize().
const std::string& scram::mef::Role::base_path () const inline
Returns
The base path containing ancestor container names.
Definition at line 283 of file element.h.
Referenced by scram::mef::Initializer::Define(), and scram::mef::Initializer::Extractor< T,-1 >::operator()().
The documentation for this class was generated from the following files:
element.h
element.cc