scram::Logger Class Reference
scram::Logger Class Reference
This is a general purpose logger; however, its main usage is asserted to be for debugging.
#include <logger.h>
Public Member Functions
~Logger () noexcept
Flashes all the logs into the standard error upon destruction.
std::ostringstream & Get (LogLevel level)
Returns a string stream by reference that is flushed to stderr by the Logger class destructor.
Static Public Member Functions
static LogLevel report_level ()
static void report_level (LogLevel level)
Sets the reporting level cut-off.
Detailed Description
This is a general purpose logger; however, its main usage is asserted to be for debugging.
All messages are directed to the standard error in a thread-safe way. This class may be expanded and modified in future to include more levels, prefixes, and logging types if it deems necessary.
Warning
Do not place any state-changing expressions with the LOG macro as they may not run if the report level excludes the specified level.
Do not place leading spaces, newline, or tabs in messages because it will mess up the level-dependent printing.
Definition at line 100 of file logger.h.
Member Function Documentation
static LogLevel scram::Logger::report_level () inline static
Returns
Reference to the cut-off level for reporting.
Definition at line 106 of file logger.h.
Referenced by scram::core::Pdag::Log(), and main().
static void scram::Logger::report_level (LogLevel level) inline static
Sets the reporting level cut-off.
Parameters
[in] level The maximum level of logging.
Definition at line 111 of file logger.h.
References Get().
std::ostringstream & scram::Logger::Get (LogLevel level)
Returns a string stream by reference that is flushed to stderr by the Logger class destructor.
Parameters
[in] level The log level for the information.
Returns
Formatted output stringstream with the log level information.
Definition at line 40 of file logger.cc.
References scram::INFO.
Referenced by report_level().
The documentation for this class was generated from the following files:
logger.h
logger.cc