scram::mef::PeriodicTest Class Reference
scram::mef::PeriodicTest Class Reference
Periodic test with 3 phases: deploy, test, functioning.
#include <exponential.h>
Public Member Functions
PeriodicTest (Expression *lambda, Expression *tau, Expression *theta, Expression *time)
Periodic tests with tests and repairs instantaneous and always successful.
PeriodicTest (Expression *lambda, Expression *mu, Expression *tau, Expression *theta, Expression *time)
Periodic tests with tests instantaneous and always successful.
PeriodicTest (Expression *lambda, Expression *lambda_test, Expression *mu, Expression *tau, Expression *theta, Expression *gamma, Expression *test_duration, Expression *available_at_test, Expression *sigma, Expression *omega, Expression *time)
Fully parametrized periodic-test description.
void Validate () const override
Validates the expression.
double value () noexceptoverride
Interval interval () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
virtual bool IsDeviate () noexcept
Determines if the value of the expression contains deviate expressions.
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
Periodic test with 3 phases: deploy, test, functioning.
Definition at line 121 of file exponential.h.
Constructor & Destructor Documentation
scram::mef::PeriodicTest::PeriodicTest (Expression * lambda, Expression * tau, Expression * theta, Expression * time)
Periodic tests with tests and repairs instantaneous and always successful.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
Definition at line 113 of file exponential.cc.
scram::mef::PeriodicTest::PeriodicTest (Expression * lambda, Expression * mu, Expression * tau, Expression * theta, Expression * time)
Periodic tests with tests instantaneous and always successful.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
[in] mu The repair rate (hourly).
Definition at line 118 of file exponential.cc.
scram::mef::PeriodicTest::PeriodicTest (Expression * lambda, Expression * lambda_test, Expression * mu, Expression * tau, Expression * theta, Expression * gamma, Expression * test_duration, Expression * available_at_test, Expression * sigma, Expression * omega, Expression * time)
Fully parametrized periodic-test description.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
[in] mu The repair rate (hourly).
[in] lambda_test The component failure rate while under test.
[in] gamma The failure probability due to or at test start.
[in] test_duration The duration of the test phase.
[in] available_at_test Indicator of component availability at test.
[in] sigma The probability of failure detection upon test.
[in] omega The probability of failure at restart after repair/test.
Definition at line 123 of file exponential.cc.
References scram::mef::EnsureNonNegative(), scram::mef::EnsurePositive(), scram::mef::EnsureProbability(), and SCRAM_THROW.
Member Function Documentation
void scram::mef::PeriodicTest::Validate () const inline override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
DomainError The argument value domains are invalid.
ValidityError The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 155 of file exponential.h.
double scram::mef::PeriodicTest::value () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 156 of file exponential.h.
Interval scram::mef::PeriodicTest::interval () inline override virtual noexcept
Returns
The domain interval for validation purposes only.
Reimplemented from scram::mef::Expression.
Definition at line 157 of file exponential.h.
References scram::mef::Exponential::Compute(), scram::mef::Expression::Sample(), scram::mef::Exponential::Validate(), and scram::mef::ExpressionFormula< Exponential >::value().
The documentation for this class was generated from the following files:
exponential.h
exponential.cc