scram::core::Terminal< T > Class Template Reference
scram::core::Terminal< T > Class Template Reference
Representation of terminal vertices in BDD graphs.
#include <bdd.h>
Public Member Functions
Terminal (bool value)
bool value () const
Public Member Functions inherited from scram::core::Vertex< T >
Vertex (int id)
int id () const
bool terminal () const
int use_count () const
bool unique () const
Additional Inherited Members
Static Public Member Functions inherited from scram::core::IntrusivePtrCast< T, Terminal< T > >
static IntrusivePtr< Terminal< T > > Ptr (const IntrusivePtr< Vertex< T >> &vertex)
static Terminal< T > & Ref (const IntrusivePtr< Vertex< T >> &vertex)
Protected Member Functions inherited from scram::core::Vertex< T >
~Vertex () noexcept
Communicates the destruction via the pointer to the unique table entry if there's any.
Detailed Description
template<class T>
class scram::core::Terminal< T >
Representation of terminal vertices in BDD graphs.
It is expected that in reduced BDD graphs, there are at most two terminal vertices of value 1 or 0. If the BDD graph has attributed edges, only single terminal vertex is expected with value 1.
Template Parameters
T The type of the main functional BDD vertex.
Definition at line 130 of file bdd.h.
Constructor & Destructor Documentation
template<class T > scram::core::Terminal< T >::Terminal (bool value) inline explicit
Parameters
[in] value True or False (1 or 0) terminal.
Definition at line 214 of file bdd.h.
Member Function Documentation
template<class T > bool scram::core::Terminal< T >::value () const inline
Returns
The value of the terminal vertex.
Note
The value serves as an id for this terminal vertex. Non-terminal if-then-else vertices should never have identifications of value 0 or 1.
Definition at line 221 of file bdd.h.
References scram::core::Vertex< T >::id().
Referenced by scram::core::Zbdd::Apply(), scram::core::Zbdd::ApplySubstitutions(), scram::core::Zbdd::EliminateConstantModules(), scram::core::Zbdd::GatherModules(), and scram::core::Zbdd::Minimize().
The documentation for this class was generated from the following file:
bdd.h