scram::core::McubCalculator Class Reference
scram::core::McubCalculator Class Reference
Quantitative calculator of probability values with the Min-Cut-Upper Bound approximation.
#include <probability_analysis.h>
Public Member Functions
double Calculate (const Zbdd &cut_sets, const Pdag::IndexMap< double > &p_vars) noexcept
Calculates probabilities using the minimal cut set upper bound (MCUB) approximation.
Detailed Description
Quantitative calculator of probability values with the Min-Cut-Upper Bound approximation.
Definition at line 169 of file probability_analysis.h.
Member Function Documentation
double scram::core::McubCalculator::Calculate (const Zbdd & cut_sets, const Pdag::IndexMap< double > & p_vars) noexcept
Calculates probabilities using the minimal cut set upper bound (MCUB) approximation.
Parameters
[in] cut_sets A collection of sets of indices of basic events.
[in] p_vars Probabilities of events mapped by the variable indices.
Returns
The total probability with the MCUB approximation.
Definition at line 179 of file probability_analysis.cc.
References scram::core::CutSetProbabilityCalculator::Calculate(), scram::core::ProbabilityAnalysis::mission_time(), scram::core::ProbabilityAnalysis::p_time(), scram::core::Analysis::settings(), scram::core::Settings::time_step(), and scram::mef::MissionTime::value().
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc