scram::mef::Substitution Class Reference
scram::mef::Substitution Class Reference
The general representation for Delete Terms, Recovery Rules, and Exchange Events.
#include <substitution.h>
Public Types
enum Type { kDeleteTerms, kRecoveryRule, kExchangeEvent }
The "traditional" substitution types.
using Target = std::variant< BasicEvent *, bool >
The target type.
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Public Member Functions
const Formula & hypothesis () const
void hypothesis (std::unique_ptr< Formula > formula)
Sets the substitution hypothesis formula.
const Target & target () const
void target (Target target_event)
Sets the target of the substitution.
const std::vector< BasicEvent * > & source () const
bool declarative () const
void Add (BasicEvent *source_event)
Adds a source event to the substitution container.
void Validate () const
Checks if the substitution is setup correctly.
std::optional< Type > type () const
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Static Public Attributes
static constexpr const char * kTypeString = "substitution"
Type string for error messages.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Detailed Description
The general representation for Delete Terms, Recovery Rules, and Exchange Events.
Definition at line 35 of file substitution.h.
Member Function Documentation
const Formula& scram::mef::Substitution::hypothesis () const inline
Returns
The formula hypothesis of the substitution.
Precondition
The required hypothesis formula has been set.
Definition at line 50 of file substitution.h.
Referenced by scram::mef::Initializer::Define().
void scram::mef::Substitution::hypothesis (std::unique_ptr< Formula > formula) inline
Sets the substitution hypothesis formula.
Parameters
[in] formula Simple Boolean formula built over basic events only.
Definition at line 58 of file substitution.h.
const Target& scram::mef::Substitution::target () const inline
Returns
The target of the substitution.
Precondition
The target has been set.
Definition at line 66 of file substitution.h.
Referenced by scram::mef::Initializer::Define().
void scram::mef::Substitution::target (Target target_event) inline
Sets the target of the substitution.
Parameters
[in] target_event Basic event or Boolean constant.
Definition at line 71 of file substitution.h.
const std::vector<BasicEvent*>& scram::mef::Substitution::source () const inline
Returns
The source events of the substitution.
Definition at line 74 of file substitution.h.
Referenced by scram::mef::Initializer::Define().
bool scram::mef::Substitution::declarative () const inline
Returns
true if the substitution is declarative.
Definition at line 77 of file substitution.h.
References Add(), type(), and Validate().
Referenced by Validate().
void scram::mef::Substitution::Add (BasicEvent * source_event)
Adds a source event to the substitution container.
Parameters
[in] source_event The event to be replaced by the target event.
Exceptions
DuplicateElementError The source event is duplicate.
Definition at line 28 of file substitution.cc.
References scram::mef::Id::id(), and SCRAM_THROW.
Referenced by declarative(), and scram::mef::Initializer::Define().
void scram::mef::Substitution::Validate () const
Checks if the substitution is setup correctly.
Precondition
The substitution has its hypothesis and target.
Exceptions
ValidityError Problems with the substitution setup.
Note
Non-declarative substitutions need to be validated further for idempotency across substitutions before analysis.
Definition at line 38 of file substitution.cc.
References declarative(), scram::mef::kAtleast, scram::mef::kConnectiveToString, scram::mef::kNull, kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
Referenced by declarative(), and scram::mef::Initializer::Define().
std::optional< Substitution::Type > scram::mef::Substitution::type () const
Returns
The equivalent "traditional" substitution type if any.
Precondition
The hypothesis, target, and source are all defined and valid.
Definition at line 92 of file substitution.cc.
References scram::mef::kAtleast, and scram::mef::kNull.
Referenced by declarative(), and scram::mef::Initializer::Define().
The documentation for this class was generated from the following files:
substitution.h
substitution.cc