scram::mef::Alignment Class Reference
scram::mef::Alignment Class Reference
Alignment configuration for the whole model per analysis.
#include <alignment.h>
Public Member Functions
auto phases () const
void Validate ()
Ensures that all phases add up to be valid for the alignment.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Container< Alignment, Phase >
void Add (Pointer element)
Adds a unique element into the container, ensuring no duplicated entries.
Pointer Remove (Phase *element)
Removes MEF elements from the container.
auto table () const
auto table ()
const Phase & Get (const key_type &id) const
Retrieves an element from the container.
Phase & Get (const key_type &id)
Retrieves an element from the container.
Static Public Attributes
static constexpr const char * kTypeString = "alignment"
Type string for error messages.
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Public Types inherited from scram::mef::Container< Alignment, Phase >
using ElementType = Phase
The MEF Element type.
using Pointer = std::conditional_t< true, std::unique_ptr< Phase >, Phase * >
The pointer type (owning or not) to store in the table.
using TableType = std::conditional_t< std::is_base_of_v< Id, Phase >, IdTable< Pointer >, ElementTable< Pointer >>
The table indexed by id or name.
using key_type = typename TableType::key_type
The key type of the table.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Protected Member Functions inherited from scram::mef::Container< Alignment, Phase >
const TableType & data () const
Detailed Description
Alignment configuration for the whole model per analysis.
Definition at line 62 of file alignment.h.
Member Function Documentation
auto scram::mef::Alignment::phases () const inline
Returns
The table range of phases in the alignment.
Definition at line 70 of file alignment.h.
References scram::mef::Container< Self, T, Ownership, ById >::table().
void scram::mef::Alignment::Validate ()
Ensures that all phases add up to be valid for the alignment.
Exceptions
ValidityError Phases are incomplete (e.g., don't sum to 1).
Definition at line 36 of file alignment.cc.
References scram::mef::Phase::kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::Initializer::Define().
The documentation for this class was generated from the following files:
alignment.h
alignment.cc