scram::mef::Attribute Class Reference
scram::mef::Attribute Class Reference
MEF Element Attributes.
#include <element.h>
Public Member Functions
Attribute (std::string name, std::string value, std::string type="")
const std::string & name () const
void name (std::string name)
const std::string & value () const
void value (std::string value)
const std::string & type () const
void type (std::string type)
Detailed Description
MEF Element Attributes.
Attributes carry extra (arbitrary) data for the elements. The interpretation of the attribute data is tool-dependent or up-to-the-user.
Note
Attribute values are all free-form strings. The strings are not sanitized or normalized to be meaningful. If not careful, it is possible to end-up with values that XML schema validators won't accept (e.g., special chars).
Definition at line 79 of file element.h.
Constructor & Destructor Documentation
scram::mef::Attribute::Attribute (std::string name, std::string value, std::string type = "") inline
Parameters
[in] name The name for the attribute.
[in] value The value for the attribute.
[in] type The optional type of the attribute value.
Exceptions
LogicError if any required values are empty.
Definition at line 86 of file element.h.
References name(), type(), and value().
Member Function Documentation
const std::string& scram::mef::Attribute::name () const inline
Returns
The name of the attribute.
Definition at line 93 of file element.h.
Referenced by scram::mef::Element::AddAttribute(), and Attribute().
void scram::mef::Attribute::name (std::string name) inline
Parameters
[in] name The name for the attribute.
Exceptions
LogicError The name is empty.
Definition at line 98 of file element.h.
References SCRAM_THROW.
const std::string& scram::mef::Attribute::value () const inline
Returns
The value of the attribute.
Definition at line 105 of file element.h.
Referenced by Attribute().
void scram::mef::Attribute::value (std::string value) inline
Parameters
[in] value The value for the attribute.
Exceptions
LogicError The value is empty.
Definition at line 110 of file element.h.
References SCRAM_THROW.
const std::string& scram::mef::Attribute::type () const inline
Returns
The type of the attribute value. Empty string if the type is not set.
Definition at line 118 of file element.h.
Referenced by Attribute().
void scram::mef::Attribute::type (std::string type) inline
Parameters
[in] type The value type. Empty string to remove the type.
Definition at line 122 of file element.h.
The documentation for this class was generated from the following file:
element.h