scram::Project Class Reference
scram::Project Class Reference
This class processes project configuration files for analysis.
#include <project.h>
Public Member Functions
Project (const std::string &project_file)
A constructor with project configurations for analysis.
const std::vector< std::string > & input_files () const
const core::Settings & settings () const
Detailed Description
This class processes project configuration files for analysis.
The class contains all the setup and state to initialize general analysis.
Definition at line 37 of file project.h.
Constructor & Destructor Documentation
scram::Project::Project (const std::string & project_file) explicit
A constructor with project configurations for analysis.
Reads and validates the configurations.
All relative paths in the configuration are resolved with respect to the location of the original configuration file.
Parameters
[in] project_file The path to the project file with configurations.
Exceptions
VersionError The version required by the file is incompatible.
ValidityError The configurations have problems.
SettingsError Settings values contain errors.
IOError The file is not accessible.
Definition at line 61 of file project.cc.
References scram::core::Settings::algorithm(), scram::core::Settings::approximation(), scram::xml::Element::attribute(), scram::core::Settings::ccf_analysis(), scram::xml::Element::child(), scram::xml::Element::children(), scram::core::Settings::cut_off(), scram::xml::Element::filename(), scram::core::Settings::importance_analysis(), input_files(), scram::core::Settings::limit_order(), scram::xml::Element::line(), scram::core::Settings::mission_time(), scram::xml::Element::name(), scram::core::Settings::num_bins(), scram::core::Settings::num_quantiles(), scram::core::Settings::num_trials(), scram::core::Settings::prime_implicants(), scram::core::Settings::probability_analysis(), scram::xml::Document::root(), scram::core::Settings::safety_integrity_levels(), SCRAM_THROW, SCRAM_VERSION_MAJOR, SCRAM_VERSION_MICRO, SCRAM_VERSION_MINOR, scram::core::Settings::seed(), scram::core::Settings::time_step(), scram::core::Settings::uncertainty_analysis(), and scram::xml::Validator::validate().
Member Function Documentation
const std::vector<std::string>& scram::Project::input_files () const inline
Returns
normalized, absolute paths to input files for analysis.
Definition at line 54 of file project.h.
Referenced by Project().
const core::Settings& scram::Project::settings () const inline
Returns
the settings for analysis.
Definition at line 57 of file project.h.
The documentation for this class was generated from the following files:
project.h
project.cc