scram::mef::Composite< Ts > Class Template Reference
scram::mef::Composite< Ts > Class Template Reference
The composition of multiple mef::Containers.
#include <element.h>
Public Member Functions
template<class T >
auto table () const
template<class T >
auto table ()
template<class T , class ContainerType = typename detail::container_of<T, Ts...>::type>
const T & Get (const typename ContainerType::key_type &id) const
Retrieves an element from the container.
template<class T , class ContainerType = typename detail::container_of<T, Ts...>::type>
T & Get (const typename ContainerType::key_type &id)
Retrieves an element from the container.
Protected Member Functions
template<class T >
decltype(auto) data () const
Detailed Description
template<typename... Ts>
class scram::mef::Composite< Ts >
The composition of multiple mef::Containers.
Template Parameters
Ts Container types.
Definition at line 583 of file element.h.
Member Function Documentation
template<typename... Ts> template<class T > auto scram::mef::Composite< Ts >::table () const inline
Template Parameters
T The mef::Element type in the composite container.
Returns
The table as an associative range of type T elements.
Definition at line 593 of file element.h.
Referenced by scram::core::RiskAnalysis::Analyze(), and scram::mef::Initializer::Define().
template<typename... Ts> template<class T > auto scram::mef::Composite< Ts >::table () inline
Template Parameters
T The mef::Element type in the composite container.
Returns
The table as an associative range of type T elements.
Definition at line 598 of file element.h.
template<typename... Ts> template<class T , class ContainerType = typename detail::container_of<T, Ts...>::type> const T& scram::mef::Composite< Ts >::Get (const typename ContainerType::key_type & id) const inline
Retrieves an element from the container.
Template Parameters
T The mef::Element type in the composite container.
Parameters
[in] id The valid ID/name string of the element.
Returns
The reference to the element.
Exceptions
UndefinedElement The element is not found.
Definition at line 616 of file element.h.
Referenced by scram::mef::Initializer::Define().
template<typename... Ts> template<class T , class ContainerType = typename detail::container_of<T, Ts...>::type> T& scram::mef::Composite< Ts >::Get (const typename ContainerType::key_type & id) inline
Retrieves an element from the container.
Template Parameters
T The mef::Element type in the composite container.
Parameters
[in] id The valid ID/name string of the element.
Returns
The reference to the element.
Exceptions
UndefinedElement The element is not found.
Definition at line 621 of file element.h.
template<typename... Ts> template<class T > decltype(auto) scram::mef::Composite< Ts >::data () const inline protected
Returns
The data table with elements of specific type.
Definition at line 629 of file element.h.
The documentation for this class was generated from the following file:
element.h