scram::xml::Document Class Reference
scram::xml::Document Class Reference
XML DOM tree document.
#include <xml.h>
Public Member Functions
Document (const std::string &file_path, Validator *validator=nullptr)
Parses XML input document.
Element root () const
const xmlDoc * get () const
xmlDoc * get ()
Detailed Description
XML DOM tree document.
Definition at line 401 of file xml.h.
Constructor & Destructor Documentation
scram::xml::Document::Document (const std::string & file_path, Validator * validator = nullptr) explicit
Parses XML input document.
All XInclude directives are processed into the final document.
Parameters
[in] file_path The path to the document file.
[in] validator Optional validator against the RNG schema.
Returns
The initialized document.
Exceptions
IOError The file is not available.
ParseError There are XML parsing failures.
XIncludeError XInclude resolution has failed.
ValidityError The XML file is not valid.
Definition at line 27 of file xml.cc.
References scram::xml::kParserOptions, SCRAM_THROW, and scram::xml::Validator::validate().
Member Function Documentation
Element scram::xml::Document::root () const inline
Returns
The root element of the document.
Precondition
The document has a root node.
Definition at line 421 of file xml.h.
Referenced by scram::mef::Initializer::Define(), scram::Project::Project(), and scram::mef::Initializer::Register().
const xmlDoc* scram::xml::Document::get () const inline
Returns
The underlying data document.
Definition at line 428 of file xml.h.
Referenced by scram::xml::Validator::validate().
xmlDoc* scram::xml::Document::get () inline
Returns
The underlying data document.
Definition at line 429 of file xml.h.
The documentation for this class was generated from the following files:
xml.h
xml.cc