scram::mef::Formula Class Reference
scram::mef::Formula Class Reference
Boolean formula with connectives and arguments.
#include <event.h>
Classes
struct Arg
Formula argument with a complement flag.
class ArgSet
The set of formula arguments.
Public Types
using ArgEvent = std::variant< Gate *, BasicEvent *, HouseEvent * >
Argument events of a formula.
Public Member Functions
Formula (Connective connective, ArgSet args, std::optional< int > min_number={}, std::optional< int > max_number={})
Connective connective () const
std::optional< int > min_number () const
std::optional< int > max_number () const
const std::vector< Arg > & args () const
void Swap (ArgEvent current, ArgEvent other)
Swaps an argument event with another one.
Formula (const Formula &)=default
Copy semantics only.
Formula & operator= (const Formula &)=default
Copy semantics only.
Detailed Description
Boolean formula with connectives and arguments.
Formulas are not expected to be shared.
Definition at line 226 of file event.h.
Constructor & Destructor Documentation
scram::mef::Formula::Formula (Connective connective, ArgSet args, std::optional< int > min_number = {}, std::optional< int > max_number = {})
Parameters
[in] connective The logical connective for this Boolean formula.
[in] args The arguments of the formula.
[in] min_number The min number relevant to the connective.
[in] max_number The max number relevant to the connective.
Exceptions
ValidityError Invalid arguments or setup for the connective.
LogicError Invalid nesting of complement or constant args.
LogicError Negative values for min or max number.
Definition at line 73 of file event.cc.
References scram::mef::Formula::ArgSet::data(), and scram::mef::kConnectiveToString.
Member Function Documentation
Connective scram::mef::Formula::connective () const inline
Returns
The connective of this formula.
Definition at line 311 of file event.h.
Referenced by scram::core::EventTreeAnalysis::EventTreeAnalysis(), and scram::mef::Serialize().
std::optional< int > scram::mef::Formula::min_number () const
Returns
The min number for "atleast"/"cardinality" connective.
Definition at line 92 of file event.cc.
References scram::mef::kAtleast, and scram::mef::kCardinality.
Referenced by scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::Serialize(), and Swap().
std::optional< int > scram::mef::Formula::max_number () const
Returns
The max number of "cardinality" connective.
Definition at line 98 of file event.cc.
References scram::mef::kCardinality.
Referenced by scram::core::EventTreeAnalysis::EventTreeAnalysis(), and Swap().
const std::vector<Arg>& scram::mef::Formula::args () const inline
Returns
The arguments of this formula.
Definition at line 320 of file event.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::cycle::GetNodes(), and scram::mef::Serialize().
void scram::mef::Formula::Swap (ArgEvent current, ArgEvent other)
Swaps an argument event with another one.
Parameters
[in] current The current argument event in this formula.
[in] other The replacement argument event.
Postcondition
Strong exception safety guarantees.
The complement flag is preserved.
The position is preserved.
Exceptions
DuplicateElementError The replacement argument is duplicate.
LogicError The current argument does not belong to this formula.
LogicError The replacement would result in invalid setup.
Definition at line 104 of file event.cc.
References scram::mef::Formula::Arg::complement, scram::mef::Formula::ArgSet::data(), scram::mef::Formula::ArgSet::empty(), scram::mef::Formula::Arg::event, scram::mef::Id::id(), scram::mef::kAtleast, scram::mef::kCardinality, scram::mef::kConnectiveToString, scram::mef::HouseEvent::kFalse, scram::mef::kIff, scram::mef::kImply, scram::mef::kNand, scram::mef::kNor, scram::mef::kNot, scram::mef::kNull, scram::mef::kXor, max_number(), min_number(), SCRAM_THROW, scram::mef::Formula::ArgSet::size(), and scram::mef::Usage::usage().
The documentation for this class was generated from the following files:
event.h
event.cc