scram::mef::CcfGroup Class Reference
scram::mef::CcfGroup Class Reference abstract
Abstract base class for all common cause failure models.
#include <ccf_group.h>
Public Member Functions
const std::vector< BasicEvent * > & members () const
void AddMember (BasicEvent *basic_event)
Adds a basic event into this CCF group.
void AddDistribution (Expression *distr)
Adds the distribution that describes the probability of basic events in this CCF group.
void AddFactor (Expression *factor, std::optional< int > level={})
Adds a CCF factor for the specified model.
void Validate () const
Validates the setup for the CCF model and group.
void ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Public Member Functions inherited from scram::mef::Id
Id (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs an element with an original name.
const std::string & id () const
std::string_view id_view () const
std::string_view full_path () const
void id (std::string name)
Resets the element ID.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
std::string_view name_view () const
const std::string & label () const
void label (std::string label)
Sets the element label.
const AttributeMap & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map of this element.
void SetAttribute (Attribute attr) noexcept
Sets an attribute to the attribute map.
const Attribute * GetAttribute (std::string_view name) const noexcept
std::optional< Attribute > RemoveAttribute (std::string_view name) noexcept
Removes an attribute of this element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Static Public Attributes
static constexpr const char * kTypeString = "CCF group"
Type string for error messages.
Protected Types
using ExpressionMap = std::vector< std::pair< int, Expression * >>
Mapping expressions and their application levels.
Protected Member Functions
Expression * distribution () const
const ExpressionMap & factors () const
template<class T , typename... Ts>
Expression * Register (Ts &&...args)
Registers a new expression for ownership by the group.
template<class T >
Expression * Register (std::initializer_list< Expression * > args)
Registers a new expression for ownership by the group.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Protected Member Functions inherited from scram::mef::ContainerElement
const Element * container () const
Additional Inherited Members
Public Types inherited from scram::mef::Element
using AttributeMap = ext::linear_set< Attribute, AttributeKey >
Unique attribute map keyed with the attribute names.
Static Public Member Functions inherited from scram::mef::Id
static const std::string & unique_name (const Element &element)
Produces unique name for the model element within the same type.
static const std::string & unique_name (const Id &element)
Produces unique name for the model element within the same type.
Detailed Description
Abstract base class for all common cause failure models.
Definition at line 80 of file ccf_group.h.
Member Function Documentation
const std::vector<BasicEvent*>& scram::mef::CcfGroup::members () const inline
Returns
Members of the CCF group with original names as keys.
Definition at line 90 of file ccf_group.h.
References scram::mef::BasicEvent::Validate().
Referenced by scram::mef::Component::Add(), ApplyModel(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::mef::CcfGroup::AddMember (BasicEvent * basic_event)
Adds a basic event into this CCF group.
This function asserts that each basic event has unique string id.
Parameters
[in] basic_event A member basic event.
Exceptions
DuplicateElementError The basic event is already in the group.
LogicError The probability distribution or factors for this CCF group are already defined. No more members are accepted.
Definition at line 54 of file ccf_group.cc.
References scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::Initializer::Extractor< T,-1 >::operator()().
void scram::mef::CcfGroup::AddDistribution (Expression * distr)
Adds the distribution that describes the probability of basic events in this CCF group.
All basic events should be added as members before defining their probabilities. No more basic events can be added after this function.
Parameters
[in] distr The probability distribution of this group.
Exceptions
ValidityError Not enough members.
LogicError The distribution has already been defined.
Definition at line 69 of file ccf_group.cc.
References scram::mef::BasicEvent::kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::Initializer::Define().
void scram::mef::CcfGroup::AddFactor (Expression * factor, std::optional< int > level = {})
Adds a CCF factor for the specified model.
All basic events should be added as members before defining the CCF factors. No more basic events can be added after this function.
Parameters
[in] factor A factor for the CCF model.
[in] level The level of the passed factor.
Exceptions
ValidityError The level is invalid.
ValidityError The factor for the level already exists.
LogicError The level is not positive, or the CCF group members are undefined.
Definition at line 82 of file ccf_group.cc.
References scram::mef::BasicEvent::kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::Initializer::Extractor< T,-1 >::operator()().
void scram::mef::CcfGroup::Validate () const
Validates the setup for the CCF model and group.
Checks if the provided distribution is between 0 and 1.
This check must be performed before validating basic events that are members of this CCF group to give more precise error messages.
Exceptions
DomainError The numeric values are invalid.
ValidityError There is an issue with the setup.
LogicError The primary distribution, event, factors are not set.
Definition at line 117 of file ccf_group.cc.
References scram::mef::EnsureProbability(), scram::mef::BasicEvent::kTypeString, scram::mef::Element::name(), and SCRAM_THROW.
void scram::mef::CcfGroup::ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Precondition
The CCF is validated.
Definition at line 139 of file ccf_group.cc.
References distribution(), factors(), scram::mef::ConstantExpression::kOne, members(), SCRAM_THROW, and scram::mef::Expression::value().
Expression* scram::mef::CcfGroup::distribution () const inline protected
Returns
The probability distribution of the events.
Definition at line 153 of file ccf_group.h.
Referenced by ApplyModel().
const ExpressionMap& scram::mef::CcfGroup::factors () const inline protected
Returns
CCF factors of the model.
Definition at line 156 of file ccf_group.h.
Referenced by ApplyModel().
The documentation for this class was generated from the following files:
ccf_group.h
ccf_group.cc