scram::mef::Usage Class Reference
scram::mef::Usage Class Reference
Mixin class for providing usage marks for elements.
#include <element.h>
Public Member Functions
bool usage () const
void usage (bool usage)
Detailed Description
Mixin class for providing usage marks for elements.
Definition at line 668 of file element.h.
Member Function Documentation
bool scram::mef::Usage::usage () const inline
Returns
true if the element is used in the model or analysis.
Definition at line 671 of file element.h.
Referenced by scram::mef::Formula::ArgSet::Add(), scram::mef::Initializer::Define(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), and scram::mef::Formula::Swap().
void scram::mef::Usage::usage (bool usage) inline
Parameters
[in] usage The usage state of the element in a model.
Definition at line 674 of file element.h.
References usage().
Referenced by usage().
The documentation for this class was generated from the following file:
element.h