scram::mef::MissionTime Class Reference
scram::mef::MissionTime Class Reference
The special parameter for system mission time.
#include <parameter.h>
Public Member Functions
MissionTime (double time=0, Units unit=kHours)
Units unit () const
void value (double time)
Changes the mission time value.
double value () noexceptoverride
Interval interval () noexceptoverride
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< Expression * > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< Expression * > & args () const
virtual void Validate () const
Validates the expression.
double Sample () noexcept
void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (Expression *arg)
Registers an additional argument expression.
Detailed Description
The special parameter for system mission time.
Definition at line 52 of file parameter.h.
Constructor & Destructor Documentation
scram::mef::MissionTime::MissionTime (double time = 0, Units unit = kHours) explicit
Parameters
[in] time The mission time.
[in] unit The unit of the given time argument.
Exceptions
LogicError The time value is negative.
Definition at line 27 of file parameter.cc.
References value().
Member Function Documentation
Units scram::mef::MissionTime::unit () const inline
Returns
The unit of the system mission time.
Definition at line 61 of file parameter.h.
References value().
void scram::mef::MissionTime::value (double time)
Changes the mission time value.
Parameters
[in] time The mission time in hours.
Exceptions
LogicError The time value is negative.
Definition at line 29 of file parameter.cc.
References SCRAM_THROW.
Referenced by scram::core::RiskAnalysis::Analyze(), and scram::core::McubCalculator::Calculate().
double scram::mef::MissionTime::value () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 70 of file parameter.h.
Referenced by MissionTime(), and unit().
Interval scram::mef::MissionTime::interval () inline override virtual noexcept
Returns
The domain interval for validation purposes only.
Reimplemented from scram::mef::Expression.
Definition at line 71 of file parameter.h.
bool scram::mef::MissionTime::IsDeviate () inline override virtual noexcept
Determines if the value of the expression contains deviate expressions.
The default logic is to check arguments with uncertainties for sampling. Derived expression classes must decide if they don't have arguments, or if they are random deviates.
Returns
true if the expression's value deviates from its mean.
false if the expression's value does not need sampling.
Warning
Improper registration of arguments may yield silent failure.
Reimplemented from scram::mef::Expression.
Definition at line 72 of file parameter.h.
The documentation for this class was generated from the following files:
parameter.h
parameter.cc