ext::linear_set< Value, KeyFromValue, Sequence > Class Template Reference
ext::linear_set< Value, KeyFromValue, Sequence > Class Template Reference
An adaptor set with lookup complexity O(N) based on sequence (contiguous structure by default).
#include <linear_set.h>
Public Types
using key_from_value = KeyFromValue
Public typedefs similar to standard sets.
using value_type = Value
Public typedefs similar to standard sets.
using key_type = std::decay_t< decltype(key_from_value()(*static_cast< value_type * >(nullptr)))>
Public typedefs similar to standard sets.
using container_type = Sequence< value_type >
Public typedefs similar to standard sets.
using pointer = typename container_type::pointer
Iterator-related typedefs redeclared from the underlying container type.
using const_pointer = typename container_type::const_pointer
Iterator-related typedefs redeclared from the underlying container type.
using reference = typename container_type::reference
Iterator-related typedefs redeclared from the underlying container type.
using const_reference = typename container_type::const_reference
Iterator-related typedefs redeclared from the underlying container type.
using iterator = typename container_type::iterator
Iterator-related typedefs redeclared from the underlying container type.
using const_iterator = typename container_type::const_iterator
Iterator-related typedefs redeclared from the underlying container type.
using reverse_iterator = typename container_type::reverse_iterator
Iterator-related typedefs redeclared from the underlying container type.
using const_reverse_iterator = typename container_type::const_reverse_iterator
Iterator-related typedefs redeclared from the underlying container type.
using size_type = typename container_type::size_type
Iterator-related typedefs redeclared from the underlying container type.
using difference_type = typename container_type::difference_type
Iterator-related typedefs redeclared from the underlying container type.
Public Member Functions
key_from_value key_extractor () const
size_type count (const key_type &key) const
Determines if an entry in the set.
template<typename Iterator >
void insert (Iterator first1, Iterator last1)
Inserts a range of elements.
template<typename... Ts>
std::pair< iterator, bool > emplace (Ts &&...args)
Attempts to build and insert an entry.
size_type erase (const key_type &key)
Erases the entry with a key.
void swap (linear_set &other) noexcept
Swaps data with another linear set.
size_type size () const
bool empty () const
void clear () noexcept
Erases all entries in the set.
void reserve (size_type n)
Prepares the linear set for a specified number of entries.
size_type capacity () const
iterator begin ()
iterator end ()
linear_set ()=default
Standard constructors (copy and move are implicit).
linear_set (std::initializer_list< value_type > init_list)
Standard constructors (copy and move are implicit).
template<typename Iterator >
linear_set (Iterator first1, Iterator last1)
Standard constructors (copy and move are implicit).
const_iterator find (const key_type &key) const
Finds an entry in the set by key.
iterator find (const key_type &key)
Finds an entry in the set by key.
std::pair< iterator, bool > insert (const value_type &value)
Inserts a value into the set if the equal value is not in the set.
std::pair< iterator, bool > insert (value_type &&value)
Inserts a value into the set if the equal value is not in the set.
iterator erase (const_iterator pos)
Erases the entry pointed by an iterator.
iterator erase (iterator pos)
Erases the entry pointed by an iterator.
container_type & data ()
const container_type & data () const
const_iterator cbegin () const
const_iterator begin () const
const_iterator cend () const
const_iterator end () const
reverse_iterator rbegin ()
Corresponding reverse iterators.
reverse_iterator rend ()
Corresponding reverse iterators.
const_reverse_iterator crbegin () const
Corresponding reverse iterators.
const_reverse_iterator rbegin () const
Corresponding reverse iterators.
const_reverse_iterator crend () const
Corresponding reverse iterators.
const_reverse_iterator rend () const
Corresponding reverse iterators.
Friends
void swap (linear_set &lhs, linear_set &rhs) noexcept
Friend swap definition for convenience sake.
bool operator== (const linear_set &lhs, const linear_set &rhs)
Non-member equality test operators.
bool operator!= (const linear_set &lhs, const linear_set &rhs)
Non-member equality test operators.
Detailed Description
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector>
class ext::linear_set< Value, KeyFromValue, Sequence >
An adaptor set with lookup complexity O(N) based on sequence (contiguous structure by default).
This set is designed for a small number of elements. Consider this class a convenient wrapper around std::vector<Value>.
Since this set is based on the vector by default, the order of insertions is preserved, and it provides random access iterators.
Unlike STL sets, this set is designed like boost::multi_index or Python sets; that is, there is key retrieval (indexation) policy for values. Therefore, this set also acts like a map.
The major differences from the standard library sets:
0. Values are not const.
Iterators, references, pointers can be invalidated by modifier functions (insert, erase, reserve, etc.). This is the inherited behavior from std::vector.
Some API may be extra or missing.
Key extraction is not stored as member data. Instead, it is treated as a policy.
The performance of the set critically depends on the number of entries, the size of the value, and the cost of comparing values for equality. The advantage of the linear_set comes from cache-friendliness, and fewer CPU front-end and back-end stalls.
Template Parameters
Value The type of the values.
KeyFromValue The key extraction functor.
Sequence The underlying container type.
Definition at line 76 of file linear_set.h.
Member Function Documentation
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> key_from_value ext::linear_set< Value, KeyFromValue, Sequence >::key_extractor () const inline
Returns
Value-to-key converter.
Definition at line 142 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const_iterator ext::linear_set< Value, KeyFromValue, Sequence >::find (const key_type & key) const inline
Finds an entry in the set by key.
Parameters
[in] key The key of the entry.
Returns
Iterator pointing to the entry, or end() if not found.
Definition at line 151 of file linear_set.h.
Referenced by ext::linear_set< Attribute, AttributeKey >::count(), ext::linear_set< Attribute, AttributeKey >::erase(), scram::mef::Element::GetAttribute(), and scram::mef::Element::RemoveAttribute().
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> iterator ext::linear_set< Value, KeyFromValue, Sequence >::find (const key_type & key) inline
Finds an entry in the set by key.
Parameters
[in] key The key of the entry.
Returns
Iterator pointing to the entry, or end() if not found.
Definition at line 158 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> size_type ext::linear_set< Value, KeyFromValue, Sequence >::count (const key_type & key) const inline
Determines if an entry in the set.
Parameters
[in] key The key of the entry.
Returns
1 if there's an entry, 0 otherwise.
Definition at line 172 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> std::pair<iterator, bool> ext::linear_set< Value, KeyFromValue, Sequence >::insert (const value_type & value) inline
Inserts a value into the set if the equal value is not in the set.
Parameters
[in] value The new value to be inserted.
Returns
A pair of an iterator and insertion flag. The iterator points to possibly inserted entry, and the flag indicates whether the entry is actually inserted.
Definition at line 185 of file linear_set.h.
Referenced by scram::mef::Element::AddAttribute(), ext::linear_set< Attribute, AttributeKey >::emplace(), ext::linear_set< Attribute, AttributeKey >::linear_set(), and scram::mef::Element::SetAttribute().
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> std::pair<iterator, bool> ext::linear_set< Value, KeyFromValue, Sequence >::insert (value_type && value) inline
Inserts a value into the set if the equal value is not in the set.
Parameters
[in] value The new value to be inserted.
Returns
A pair of an iterator and insertion flag. The iterator points to possibly inserted entry, and the flag indicates whether the entry is actually inserted.
Definition at line 193 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> template<typename Iterator > void ext::linear_set< Value, KeyFromValue, Sequence >::insert (Iterator first1, Iterator last1) inline
Inserts a range of elements.
The range is not assumed to be unique.
Template Parameters
Iterator Iterator to the container with values.
Parameters
[in] first1 The beginning of the range.
[in] last1 The end of the range.
Definition at line 210 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> template<typename... Ts> std::pair<iterator, bool> ext::linear_set< Value, KeyFromValue, Sequence >::emplace (Ts &&... args) inline
Attempts to build and insert an entry.
Parameters
[in] args Arguments for the construction of the entry.
Returns
An iterator pointing to the entry, and a flag indicating if the insertion actually happened.
Definition at line 224 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> iterator ext::linear_set< Value, KeyFromValue, Sequence >::erase (const_iterator pos) inline
Erases the entry pointed by an iterator.
Parameters
[in] pos An iterator pointing to the entry.
Returns
An iterator pointing after the entry.
Definition at line 235 of file linear_set.h.
Referenced by ext::linear_set< Attribute, AttributeKey >::erase(), and scram::mef::Element::RemoveAttribute().
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> iterator ext::linear_set< Value, KeyFromValue, Sequence >::erase (iterator pos) inline
Erases the entry pointed by an iterator.
Parameters
[in] pos An iterator pointing to the entry.
Returns
An iterator pointing after the entry.
Definition at line 236 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> size_type ext::linear_set< Value, KeyFromValue, Sequence >::erase (const key_type & key) inline
Erases the entry with a key.
Parameters
[in] key The key of the entry.
Returns
1 if the existing entry has been removed, 0 if there's no entry with the given key.
Definition at line 245 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> void ext::linear_set< Value, KeyFromValue, Sequence >::swap (linear_set< Value, KeyFromValue, Sequence > & other) inline noexcept
Swaps data with another linear set.
Parameters
[in] other Another linear set.
Definition at line 256 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> size_type ext::linear_set< Value, KeyFromValue, Sequence >::size () const inline
Returns
The number of entries in the set.
Definition at line 259 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> bool ext::linear_set< Value, KeyFromValue, Sequence >::empty () const inline
Returns
true if there are no entries.
Definition at line 262 of file linear_set.h.
Referenced by scram::mef::Serialize().
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> void ext::linear_set< Value, KeyFromValue, Sequence >::reserve (size_type n) inline
Prepares the linear set for a specified number of entries.
Parameters
[in] n The number of expected entries.
Definition at line 270 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> size_type ext::linear_set< Value, KeyFromValue, Sequence >::capacity () const inline
Returns
The capacity of the underlying container.
Definition at line 273 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> container_type& ext::linear_set< Value, KeyFromValue, Sequence >::data () inline
Returns
The underlying data container. The container elements are ordered exactly as inserted.
Definition at line 278 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const container_type& ext::linear_set< Value, KeyFromValue, Sequence >::data () const inline
Returns
The underlying data container. The container elements are ordered exactly as inserted.
Definition at line 279 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> iterator ext::linear_set< Value, KeyFromValue, Sequence >::begin () inline
Returns
A read/write iterator pointing to the first entry.
Definition at line 283 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> iterator ext::linear_set< Value, KeyFromValue, Sequence >::end () inline
Returns
A read/write iterator pointing one past the last entry.
Definition at line 285 of file linear_set.h.
Referenced by scram::mef::Element::GetAttribute(), and scram::mef::Element::RemoveAttribute().
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const_iterator ext::linear_set< Value, KeyFromValue, Sequence >::cbegin () const inline
Returns
A read-only iterator pointing to the first entry.
Definition at line 290 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const_iterator ext::linear_set< Value, KeyFromValue, Sequence >::begin () const inline
Returns
A read-only iterator pointing to the first entry.
Definition at line 291 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const_iterator ext::linear_set< Value, KeyFromValue, Sequence >::cend () const inline
Returns
A read-only iterator pointing one past the last entry.
Definition at line 297 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> const_iterator ext::linear_set< Value, KeyFromValue, Sequence >::end () const inline
Returns
A read-only iterator pointing one past the last entry.
Definition at line 298 of file linear_set.h.
Friends And Related Function Documentation
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> bool operator== (const linear_set< Value, KeyFromValue, Sequence > & lhs, const linear_set< Value, KeyFromValue, Sequence > & rhs) friend
Non-member equality test operators.
The complexity is O(N^2).
Parameters
[in] lhs First set.
[in] rhs Second set.
Note
The order of elements is not relevant. If the order matters for equality, compare the underlying data containers directly.
Definition at line 88 of file linear_set.h.
template<typename Value, typename KeyFromValue = identity, template< typename... > class Sequence = std::vector> bool operator!= (const linear_set< Value, KeyFromValue, Sequence > & lhs, const linear_set< Value, KeyFromValue, Sequence > & rhs) friend
Non-member equality test operators.
The complexity is O(N^2).
Parameters
[in] lhs First set.
[in] rhs Second set.
Note
The order of elements is not relevant. If the order matters for equality, compare the underlying data containers directly.
Definition at line 95 of file linear_set.h.
The documentation for this class was generated from the following file:
linear_set.h