scram::xml::StreamElement Class Reference
scram::xml::StreamElement Class Reference
Writer of data formed as an XML element to a stream.
#include <xml_stream.h>
Public Member Functions
StreamElement (const char *name, detail::Indenter *indenter, detail::FileStream *out)
Constructs a root streamer for the XML element data ready to accept attributes, elements, text.
~StreamElement () noexcept
Puts the closing tag.
template<typename T >
StreamElement & SetAttribute (const char *name, T &&value)
Sets the attributes for the element.
template<typename T >
StreamElement & AddText (T &&text)
Adds text to the element.
StreamElement AddChild (const char *name)
Adds a child element to the element.
Detailed Description
Writer of data formed as an XML element to a stream.
This class relies on the RAII to put the closing tags. It is designed for stack-based use so that its destructor gets called at scope exit. One element at a time must be operated. The output will be malformed if two child elements at the same scope are being streamed. To prevent this from happening, the parent element is put into an inactive state while its child element is alive.
Precondition
All strings are UTF-8 encoded.
Note
The stream is not designed to mix XML text and elements due to the absence of the use case or need.
Warning
The names of elements and attributes are NOT validated to be proper XML NCName. It is up to the caller to sanitize the names (<, >, &, ", ', :, etc.).
The API works with C strings, but this class does not manage the string lifetime. It doesn't own any strings. The provider of the strings must make sure the lifetime of the string is long enough for streaming. It is the most common case that strings are literals, so there's no need to worry about dynamic lifetime.
Definition at line 183 of file xml_stream.h.
Constructor & Destructor Documentation
scram::xml::StreamElement::StreamElement (const char * name, detail::Indenter * indenter, detail::FileStream * out) inline
Constructs a root streamer for the XML element data ready to accept attributes, elements, text.
Parameters
[in] name Non-empty string name for the element.
[in] indenter The indentation provider.
[in,out] out The destination stream.
Exceptions
StreamError Invalid setup for the element.
Definition at line 193 of file xml_stream.h.
scram::xml::StreamElement::~StreamElement () inline noexcept
Puts the closing tag.
Precondition
No child element is alive.
Warning
The output will be malformed if the child outlives the parent. It can happen if the destructor is called explicitly, or if the objects are allocated on the heap with different lifetimes.
Definition at line 206 of file xml_stream.h.
Member Function Documentation
template<typename T > StreamElement& scram::xml::StreamElement::SetAttribute (const char * name, T && value) inline
Sets the attributes for the element.
Template Parameters
T Streamable type supporting operator<<.
Parameters
[in] name Non-empty name for the attribute.
[in] value The value of the attribute.
Returns
The reference to this element.
Postcondition
&, <, " chars are escaped in the value text.
Exceptions
StreamError Invalid setup for the attribute.
Definition at line 236 of file xml_stream.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ImportanceAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >(), and scram::mef::Serialize().
template<typename T > StreamElement& scram::xml::StreamElement::AddText (T && text) inline
Adds text to the element.
Template Parameters
T Streamable type supporting operator<<.
Parameters
[in] text Non-empty text.
Returns
The reference to this element.
Postcondition
No more elements or attributes can be added.
More text can be added.
&, <, " chars are escaped in the text.
Exceptions
StreamError Invalid setup or state for text addition.
Definition at line 264 of file xml_stream.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >(), and scram::mef::Serialize().
StreamElement scram::xml::StreamElement::AddChild (const char * name) inline
Adds a child element to the element.
Parameters
[in] name Non-empty name for the child element.
Returns
A streamer for child element.
Precondition
The child element will be destroyed before the parent.
Postcondition
The parent element is inactive while the child element is alive.
Exceptions
StreamError Invalid setup or state for element addition.
Definition at line 292 of file xml_stream.h.
Referenced by scram::Reporter::Report(), scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ImportanceAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >(), and scram::mef::Serialize().
The documentation for this class was generated from the following file:
xml_stream.h