scram::core::Zbdd Class Reference
scram::core::Zbdd Class Reference
Zero-Suppressed Binary Decision Diagrams for set manipulations.
#include <zbdd.h>
Classes
class const_iterator
Iterator over products in a ZBDD container.
Public Types
using VertexPtr = IntrusivePtr< Vertex< SetNode >>
ZBDD vertex base.
using TerminalPtr = IntrusivePtr< Terminal< SetNode >>
Terminal vertex.
Public Member Functions
Zbdd (Bdd *bdd, const Settings &settings) noexcept
Converts Reduced Ordered BDD into Zero-Suppressed BDD.
Zbdd (const Pdag *graph, const Settings &settings) noexcept
Constructor with the analysis target.
void Analyze (const Pdag *graph=nullptr) noexcept
Runs the analysis with the representation of a PDAG as ZBDD.
const Zbdd & products () const
std::size_t size () const
bool empty () const
bool base () const
auto begin () const
auto end () const
Protected Member Functions
Zbdd (const Settings &settings, bool coherent=false, int module_index=0) noexcept
The common constructor to initialize member variables.
const VertexPtr & root () const
void root (const VertexPtr &vertex)
Sets a new root vertex for ZBDD.
const Settings & settings () const
const std::map< int, std::unique_ptr< Zbdd > > & modules () const
void Log () noexcept
Logs properties of the Zbdd.
SetNodePtr FindOrAddVertex (int index, const VertexPtr &high, const VertexPtr &low, int order, bool module=false, bool coherent=false) noexcept
Finds or adds a unique SetNode in the ZBDD.
SetNodePtr FindOrAddVertex (const Gate &gate, const VertexPtr &high, const VertexPtr &low) noexcept
Find or adds a ZBDD SetNode vertex using information from gates.
template<Connective Type>
VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
VertexPtr Apply (Connective type, const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
template<Connective Type>
VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Applies Boolean operation to ZBDD graph non-terminal vertices.
VertexPtr EliminateComplements (const VertexPtr &vertex, std::unordered_map< int, VertexPtr > *wide_results) noexcept
Removes complements of variables from products.
void EliminateConstantModules () noexcept
Removes constant modules from products.
VertexPtr Minimize (const VertexPtr &vertex) noexcept
Removes subsets in ZBDD.
int GatherModules (const VertexPtr &vertex, int current_order, std::map< int, std::pair< bool, int >> *modules) noexcept
Traverses ZBDD to find modules and adjusted cut-offs.
void ApplySubstitutions (const std::vector< Pdag::Substitution > &substitutions) noexcept
Applies non-declarative substitutions at the end of analysis.
void ClearTables () noexcept
Clears all memoization tables.
void Freeze () noexcept
Freezes the graph.
void JoinModule (int index, std::unique_ptr< Zbdd > container) noexcept
Joins a ZBDD representing a module gate.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND connective for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND connective for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR connective for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR connective for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
Protected Attributes
const TerminalPtr kBase_
Terminal Base (Unity/1) set.
const TerminalPtr kEmpty_
Terminal Empty (Null/0) set.
Detailed Description
Zero-Suppressed Binary Decision Diagrams for set manipulations.
Definition at line 130 of file zbdd.h.
Constructor & Destructor Documentation
scram::core::Zbdd::Zbdd (Bdd * bdd, const Settings & settings) noexcept
Converts Reduced Ordered BDD into Zero-Suppressed BDD.
Parameters
[in] bdd ROBDD with the ITE vertices.
[in] settings Settings for analysis.
Precondition
BDD has attributed edges with only one terminal (1/True).
Postcondition
The input BDD structure is not changed.
Note
The input BDD is not passed as a constant because ZBDD needs BDD facilities to calculate prime implicants. However, ZBDD guarantees to preserve the original BDD structure.
Definition at line 62 of file zbdd.cc.
References CHECK_ZBDD.
Referenced by Zbdd().
scram::core::Zbdd::Zbdd (const Pdag * graph, const Settings & settings) noexcept
Constructor with the analysis target.
ZBDD is directly produced from a PDAG.
Parameters
[in] graph Preprocessed and fully normalized PDAG.
[in] settings The analysis settings.
Precondition
The passed PDAG already has variable ordering.
Note
The construction may take considerable time.
Definition at line 67 of file zbdd.cc.
References scram::core::Gate::args(), begin(), CHECK_ZBDD, scram::core::Gate::constant(), FindOrAddVertex(), scram::core::Node::index(), kBase_, kEmpty_, and scram::core::Node::order().
scram::core::Zbdd::Zbdd (const Settings & settings, bool coherent = false, int module_index = 0) explicit protected noexcept
The common constructor to initialize member variables.
Parameters
[in] settings Settings that control analysis complexity.
[in] coherent A flag for coherent modular functions.
[in] module_index The index of a module if known.
Definition at line 104 of file zbdd.cc.
References CLOCK, scram::core::Gate::coherent(), scram::core::Bdd::Function::complement, scram::core::Gate::constant(), scram::DEBUG2, scram::DEBUG3, scram::DEBUG4, DUR, EliminateComplements(), EliminateConstantModules(), gates, GatherModules(), scram::core::Node::index(), JoinModule(), scram::core::Settings::limit_order(), LOG, Log(), scram::core::SetNode::minimal(), Minimize(), scram::core::Gate::module(), scram::core::Bdd::modules(), scram::core::Settings::prime_implicants(), scram::core::IntrusivePtrCast< SetNode >::Ref(), settings(), scram::core::Gate::type(), scram::core::Bdd::Function::vertex, and Zbdd().
Member Function Documentation
void scram::core::Zbdd::Analyze (const Pdag * graph = nullptr) noexcept
Runs the analysis with the representation of a PDAG as ZBDD.
Parameters
[in] graph The optional PDAG with non-declarative substitutions.
Postcondition
Substitutions destroy all the modules.
Definition at line 87 of file zbdd.cc.
References ApplySubstitutions(), CLOCK, scram::DEBUG3, DUR, Freeze(), scram::core::Settings::limit_order(), LOG, scram::core::SetNode::max_set_order(), scram::core::SetNode::minimal(), Minimize(), and scram::core::IntrusivePtrCast< SetNode >::Ref().
Referenced by scram::core::FaultTreeAnalyzer< Algorithm >::algorithm().
const Zbdd& scram::core::Zbdd::products () const inline
Returns
Products generated by the analysis.
Definition at line 347 of file zbdd.h.
auto scram::core::Zbdd::begin () const inline
Returns
Iterators over sets in the ZBDD.
Definition at line 351 of file zbdd.h.
Referenced by Zbdd().
auto scram::core::Zbdd::end () const inline
Returns
Iterators over sets in the ZBDD.
Definition at line 352 of file zbdd.h.
std::size_t scram::core::Zbdd::size () const inline
Returns
The number of products in the ZBDD.
Note
This is not cheap. The complexity is O(N) on the number of sets in ZBDD.
Definition at line 359 of file zbdd.h.
References begin, and end.
Referenced by scram::core::FaultTreeAnalysis::Analyze().
bool scram::core::Zbdd::empty () const inline
Returns
true for ZBDD with no products.
Definition at line 362 of file zbdd.h.
References begin, and end.
Referenced by scram::core::FaultTreeAnalysis::Analyze().
bool scram::core::Zbdd::base () const inline
Returns
true if the ZBDD represents a base/unity set.
Definition at line 365 of file zbdd.h.
References scram::core::NonTerminal< SetNode >::coherent().
Referenced by scram::core::FaultTreeAnalysis::Analyze().
const VertexPtr& scram::core::Zbdd::root () const inline protected
Returns
Current root vertex of the ZBDD.
Definition at line 377 of file zbdd.h.
Referenced by scram::core::zbdd::CutSetContainer::EliminateComplements(), scram::core::zbdd::CutSetContainer::ExtractIntermediateCutSets(), scram::core::zbdd::CutSetContainer::GatherModules(), scram::core::zbdd::CutSetContainer::GetNextGate(), scram::core::zbdd::CutSetContainer::Merge(), and scram::core::zbdd::CutSetContainer::Minimize().
void scram::core::Zbdd::root (const VertexPtr & vertex) inline protected
Sets a new root vertex for ZBDD.
Parameters
[in] vertex A vertex already registered in this ZBDD.
Definition at line 382 of file zbdd.h.
const Settings& scram::core::Zbdd::settings () const inline protected
Returns
Analysis setting with this ZBDD.
Definition at line 385 of file zbdd.h.
Referenced by scram::core::zbdd::CutSetContainer::ConvertGate(), scram::core::zbdd::CutSetContainer::ExpandGate(), scram::core::zbdd::CutSetContainer::ExtractIntermediateCutSets(), scram::core::zbdd::CutSetContainer::Merge(), and Zbdd().
const std::map<int, std::unique_ptr<Zbdd> >& scram::core::Zbdd::modules () const inline protected
Returns
A set of registered and fully processed modules;
Definition at line 388 of file zbdd.h.
References scram::core::NonTerminal< SetNode >::coherent(), scram::core::NonTerminal< SetNode >::high(), scram::core::NonTerminal< SetNode >::index(), scram::core::NonTerminal< SetNode >::low(), scram::core::NonTerminal< SetNode >::module(), and scram::core::NonTerminal< SetNode >::order().
Referenced by ApplySubstitutions(), GatherModules(), and scram::core::zbdd::CutSetContainer::GatherModules().
SetNodePtr scram::core::Zbdd::FindOrAddVertex (int index, const VertexPtr & high, const VertexPtr & low, int order, bool module = false, bool coherent = false) protected noexcept
Finds or adds a unique SetNode in the ZBDD.
All vertices in the ZBDD must be created with this function. Otherwise, the ZBDD may not be reduced, and vertices will miss crucial meta-information about the ZBDD.
Parameters
[in] index Positive or negative index of the node.
[in] high The high vertex.
[in] low The low vertex.
[in] order The order for the vertex variable.
[in] module The indication of a proxy for a modular ZBDD.
[in] coherent The indication of a coherent proxy.
Returns
Set node with the given parameters.
Warning
This function is not aware of reduction rules.
Definition at line 198 of file zbdd.cc.
References scram::core::SetNode::max_set_order(), and scram::core::IntrusivePtrCast< SetNode >::Ref().
Referenced by ApplySubstitutions(), scram::core::zbdd::CutSetContainer::ConvertGate(), FindOrAddVertex(), Minimize(), and Zbdd().
SetNodePtr scram::core::Zbdd::FindOrAddVertex (const Gate & gate, const VertexPtr & high, const VertexPtr & low) protected noexcept
Find or adds a ZBDD SetNode vertex using information from gates.
Parameters
[in] gate Gate with index, order, and other information.
[in] high The new high vertex.
[in] low The new low vertex.
Returns
SetNode for a replacement.
Warning
This function is not aware of reduction rules.
Definition at line 228 of file zbdd.cc.
References Apply(), scram::core::Gate::args(), ClearTables(), scram::core::Gate::coherent(), scram::core::Bdd::Function::complement, scram::core::Gate::constant(), FindOrAddVertex(), gates, scram::core::Node::index(), kBase_, kEmpty_, scram::core::Settings::limit_order(), scram::core::SetNode::max_set_order(), scram::core::Gate::module(), scram::core::Node::order(), scram::core::NonTerminal< T >::order(), scram::core::NodeParentManager::parents(), scram::core::Settings::prime_implicants(), scram::core::IntrusivePtrCast< Ite >::Ptr(), scram::core::IntrusivePtrCast< SetNode >::Ref(), scram::core::IntrusivePtrCast< T, Terminal< T > >::Ref(), ext::linear_map< Key, Value, ErasePolicy, Sequence >::size(), scram::core::Gate::type(), and scram::core::Bdd::Function::vertex.
template<Connective Type> VertexPtr scram::core::Zbdd::Apply (const VertexPtr & arg_one, const VertexPtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to two vertices representing sets.
This is the main function for the operation.
Template Parameters
Type The connective enum.
Parameters
[in] arg_one First argument ZBDD set.
[in] arg_two Second argument ZBDD set.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Postcondition
The limit on the set order is guaranteed.
Referenced by scram::core::zbdd::CutSetContainer::ConvertGate(), and FindOrAddVertex().
Zbdd::VertexPtr scram::core::Zbdd::Apply (Connective type, const VertexPtr & arg_one, const VertexPtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to two vertices representing sets.
This is a convenience function if the connective type cannot be determined at compile time.
Parameters
[in] type The connective or type of the gate.
[in] arg_one First argument ZBDD set.
[in] arg_two Second argument ZBDD set.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Precondition
The connective is either AND or OR.
Postcondition
The limit on the set order is guaranteed.
Definition at line 537 of file zbdd.cc.
template<Connective Type> VertexPtr scram::core::Zbdd::Apply (const SetNodePtr & arg_one, const SetNodePtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to ZBDD graph non-terminal vertices.
Template Parameters
Type The connective enum.
Parameters
[in] arg_one First argument set vertex.
[in] arg_two Second argument set vertex.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Precondition
Argument vertices are ordered.
Zbdd::VertexPtr scram::core::Zbdd::EliminateComplements (const VertexPtr & vertex, std::unordered_map< int, VertexPtr > * wide_results) protected noexcept
Removes complements of variables from products.
This procedure only needs to be performed for non-coherent graphs with minimal cut sets as output.
Parameters
[in] vertex The variable vertex in the ZBDD.
[in,out] wide_results Memoisation of the processed vertices.
Returns
Processed vertex.
Postcondition
Sub-modules are not processed.
Complements of modules are not eliminated.
Definition at line 546 of file zbdd.cc.
References scram::core::Settings::limit_order(), scram::core::SetNode::max_set_order(), Minimize(), scram::core::IntrusivePtrCast< SetNode >::Ptr(), and scram::core::IntrusivePtrCast< SetNode >::Ref().
Referenced by scram::core::zbdd::CutSetContainer::EliminateComplements(), and Zbdd().
void scram::core::Zbdd::EliminateConstantModules () protected noexcept
Removes constant modules from products.
Constant modules are likely to happen after complement elimination. This procedure is inherently bottom-up, so the caller must make sure that the modules have already been pre-processed.
Precondition
All modules have been processed.
Definition at line 574 of file zbdd.cc.
References scram::DEBUG4, scram::core::Settings::limit_order(), LOG, Minimize(), scram::core::IntrusivePtrCast< SetNode >::Ptr(), and scram::core::Terminal< T >::value().
Referenced by scram::core::zbdd::CutSetContainer::EliminateConstantModules(), and Zbdd().
Zbdd::VertexPtr scram::core::Zbdd::Minimize (const VertexPtr & vertex) protected noexcept
Removes subsets in ZBDD.
Parameters
[in] vertex The variable node in the set.
Returns
Processed vertex.
Definition at line 613 of file zbdd.cc.
References scram::core::NonTerminal< T >::coherent(), FindOrAddVertex(), scram::core::NonTerminal< T >::index(), kEmpty_, scram::core::SetNode::minimal(), scram::core::NonTerminal< T >::module(), scram::core::Settings::prime_implicants(), scram::core::IntrusivePtrCast< SetNode >::Ptr(), scram::core::IntrusivePtrCast< T, Terminal< T > >::Ref(), scram::core::IntrusivePtrCast< SetNode >::Ref(), and scram::core::Terminal< T >::value().
Referenced by Analyze(), Apply(), ApplySubstitutions(), EliminateComplements(), EliminateConstantModules(), scram::core::zbdd::CutSetContainer::Minimize(), and Zbdd().
int scram::core::Zbdd::GatherModules (const VertexPtr & vertex, int current_order, std::map< int, std::pair< bool, int >> * modules) protected noexcept
Traverses ZBDD to find modules and adjusted cut-offs.
Modules within modules are not gathered.
Parameters
[in] vertex The root vertex to start with.
[in] current_order The product order from the top to the module.
[in,out] modules A map of module indices, coherence, and cut-offs.
Returns
The minimum product order from the bottom.
-1 if the vertex is terminal Empty on low branch only.
Precondition
The ZBDD is minimal.
Definition at line 716 of file zbdd.cc.
References scram::core::NonTerminal< T >::coherent(), scram::core::NonTerminal< T >::high(), scram::core::NonTerminal< T >::index(), scram::core::Settings::limit_order(), scram::core::NonTerminal< T >::low(), scram::core::NonTerminal< T >::module(), modules(), scram::core::IntrusivePtrCast< SetNode >::Ref(), and scram::core::Terminal< T >::value().
Referenced by scram::core::zbdd::CutSetContainer::GatherModules(), and Zbdd().
void scram::core::Zbdd::ApplySubstitutions (const std::vector< Pdag::Substitution > & substitutions) protected noexcept
Applies non-declarative substitutions at the end of analysis.
Parameters
[in] substitutions The substitutions defined in PDAG.
Definition at line 744 of file zbdd.cc.
References ClearTables(), scram::core::SetNode::count(), FindOrAddVertex(), scram::core::NonTerminal< T >::high(), scram::core::NonTerminal< T >::index(), kBase_, kEmpty_, scram::core::Settings::limit_order(), scram::core::NonTerminal< T >::low(), scram::core::NonTerminal< T >::mark(), scram::core::SetNode::minimal(), Minimize(), scram::core::NonTerminal< T >::module(), modules(), scram::core::NonTerminal< T >::order(), scram::core::IntrusivePtrCast< SetNode >::Ref(), scram::core::IntrusivePtrCast< T, Terminal< T > >::Ref(), and scram::core::Terminal< T >::value().
Referenced by Analyze().
void scram::core::Zbdd::Freeze () inline protected noexcept
Freezes the graph.
Releases all possible memory from memoization and unique tables.
Precondition
No more graph modifications after the freeze.
Definition at line 539 of file zbdd.h.
References ClearTables().
Referenced by Analyze().
void scram::core::Zbdd::JoinModule (int index, std::unique_ptr< Zbdd > container) inline protected noexcept
Joins a ZBDD representing a module gate.
Parameters
[in] index The index of the module.
[in] container The container of the module graph.
Precondition
The module products are final, and no more processing or sanitizing is needed.
Definition at line 555 of file zbdd.h.
References scram::core::SetNode::minimal(), and scram::core::IntrusivePtrCast< SetNode >::Ref().
Referenced by scram::core::zbdd::CutSetContainer::GatherModules(), and Zbdd().
Member Data Documentation
const TerminalPtr scram::core::Zbdd::kBase_ protected
Terminal Base (Unity/1) set.
Todo:
Redesign vertex management and creation.
The management mechanism must be encapsulated. Invariants must be private.
Definition at line 565 of file zbdd.h.
Referenced by Apply(), ApplySubstitutions(), scram::core::zbdd::CutSetContainer::ConvertGate(), FindOrAddVertex(), and Zbdd().
The documentation for this class was generated from the following files:
zbdd.h
zbdd.cc