scram::core::Preprocessor::GateSet Class Reference
scram::core::Preprocessor::GateSet Class Reference
Container of unique gates.
Public Member Functions
std::pair< GatePtr, bool > insert (const GatePtr &gate) noexcept
Inserts a gate into the set if it is semantically unique.
Detailed Description
Container of unique gates.
This container acts like an unordered set of gates. The gates are equivalent if they have the same semantics. However, this set does not test for the isomorphism of the gates' Boolean formulas.
Definition at line 192 of file preprocessor.cc.
Member Function Documentation
std::pair<GatePtr, bool> scram::core::Preprocessor::GateSet::insert (const GatePtr & gate) inline noexcept
Inserts a gate into the set if it is semantically unique.
Parameters
[in] gate The gate to insert.
Returns
A pair of the unique gate and the insertion success flag.
Definition at line 201 of file preprocessor.cc.
References scram::core::Gate::args(), scram::core::Gate::constant(), scram::core::Node::index(), scram::core::Gate::mark(), scram::core::Gate::min_number(), and scram::core::Gate::type().
The documentation for this class was generated from the following file:
preprocessor.cc