cycle.h File Reference
cycle.h File Reference
Validation facilities to detect and print cycles in graphs.
#include <array>
#include <string>
#include <vector>
#include <boost/algorithm/string/join.hpp>
#include <boost/range/adaptor/filtered.hpp>
#include <boost/range/adaptor/reversed.hpp>
#include <boost/range/adaptor/transformed.hpp>
#include "element.h"
#include "error.h"
#include "event.h"
#include "event_tree.h"
#include "instruction.h"
#include "parameter.h"
Functions
template<class T , class N >
bool scram::mef::cycle::ContinueConnector (T *connector, std::vector< N * > *cycle)
Helper function to check for cyclic references through connectors.
template<class T >
bool scram::mef::cycle::DetectCycle (T *node, std::vector< T * > *cycle)
Traverses nodes with connectors to find a cycle.
template<>
bool scram::mef::cycle::ContinueConnector (Branch *connector, std::vector< NamedBranch * > *cycle)
Cycle detection specialization for event tree named branches.
template<>
bool scram::mef::cycle::ContinueConnector (const Instruction *connector, std::vector< Rule * > *cycle)
Cycle detection specialization for visitor-based traversal of instructions.
template<>
bool scram::mef::cycle::ContinueConnector (const EventTree *connector, std::vector< Link * > *cycle)
Cycle detection specialization for visitor-based traversal of event-trees.
template<class T >
const std::string & scram::mef::cycle::GetUniqueName (const T *node)
Retrieves a unique name for a node.
template<>
const std::string & scram::mef::cycle::GetUniqueName (const Link *node)
Specialization for event-tree link name retrieval.
template<class T >
std::string scram::mef::cycle::PrintCycle (const std::vector< T * > &cycle)
Prints the detected cycle from the output produced by cycle detection functions.
template<class T , class SinglePassRange >
void scram::mef::cycle::CheckCycle (const SinglePassRange &container, const char *type)
Checks for cycles in a model constructs.
const Formula * scram::mef::cycle::GetConnector (Gate *node)
Determines the connectors between nodes.
Expression * scram::mef::cycle::GetConnector (Parameter *node)
Determines the connectors between nodes.
Branch * scram::mef::cycle::GetConnector (NamedBranch *node)
Determines the connectors between nodes.
const Instruction * scram::mef::cycle::GetConnector (Rule *node)
Determines the connectors between nodes.
const EventTree * scram::mef::cycle::GetConnector (Link *node)
Determines the connectors between nodes.
auto scram::mef::cycle::GetNodes (const Formula *connector)
Retrieves nodes from a connector.
auto scram::mef::cycle::GetNodes (Expression *connector)
Retrieves nodes from a connector.
auto scram::mef::cycle::GetConnectors (const Formula *connector)
Retrieves connectors from a connector.
auto scram::mef::cycle::GetConnectors (Expression *connector)
Retrieves connectors from a connector.
Detailed Description
Validation facilities to detect and print cycles in graphs.
Definition in file cycle.h.
Function Documentation
const Formula* scram::mef::cycle::GetConnector (Gate * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 48 of file cycle.h.
References scram::mef::Gate::formula(), and scram::mef::cycle::GetConnector().
Referenced by scram::mef::cycle::DetectCycle(), and scram::mef::cycle::GetConnector().
Expression* scram::mef::cycle::GetConnector (Parameter * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 49 of file cycle.h.
References scram::mef::cycle::GetConnector().
Branch* scram::mef::cycle::GetConnector (NamedBranch * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 50 of file cycle.h.
References scram::mef::cycle::GetConnector().
const Instruction* scram::mef::cycle::GetConnector (Rule * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 51 of file cycle.h.
References scram::mef::cycle::GetConnector().
const EventTree* scram::mef::cycle::GetConnector (Link * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 52 of file cycle.h.
References scram::mef::Link::event_tree(), and scram::mef::cycle::GetConnector().
auto scram::mef::cycle::GetNodes (const Formula * connector) inline
Retrieves nodes from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of nodes on the other end of connection.
Definition at line 62 of file cycle.h.
References scram::mef::Formula::args(), scram::mef::Formula::Arg::event, and scram::mef::cycle::GetNodes().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetNodes().
auto scram::mef::cycle::GetNodes (Expression * connector) inline
Retrieves nodes from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of nodes on the other end of connection.
Definition at line 71 of file cycle.h.
References scram::mef::Expression::args(), and scram::mef::cycle::GetNodes().
auto scram::mef::cycle::GetConnectors (const Formula * connector) inline
Retrieves connectors from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of connectors.
Definition at line 86 of file cycle.h.
References scram::mef::cycle::GetConnectors().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetConnectors().
auto scram::mef::cycle::GetConnectors (Expression * connector) inline
Retrieves connectors from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of connectors.
Definition at line 90 of file cycle.h.
References scram::mef::Expression::args(), scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetConnectors().
template<class T , class N > bool scram::mef::cycle::ContinueConnector (T * connector, std::vector< N * > * cycle)
Helper function to check for cyclic references through connectors.
Connectors may get market upon traversal.
Connectors and nodes of the connector are retrieved via unqualified calls: GetConnectors(connector) and GetNodes(connector).
Template Parameters
T The type managing the connectors (nodes, edges).
N The node type.
Parameters
[in,out] connector Connector to nodes.
[out] cycle The cycle path if detected.
Returns
True if a cycle is detected.
Definition at line 150 of file cycle.h.
References scram::mef::cycle::DetectCycle(), scram::mef::cycle::GetConnectors(), and scram::mef::cycle::GetNodes().
template<class T > bool scram::mef::cycle::DetectCycle (T * node, std::vector< T * > * cycle)
Traverses nodes with connectors to find a cycle.
Interrupts the detection at first cycle. Nodes get marked.
The connector of the node is retrieved via unqualified call to GetConnector(node).
Template Parameters
T The type of nodes in the graph.
Parameters
[in,out] node The node to start with.
[out] cycle If a cycle is detected, it is given in reverse, ending with the cycle node.
Returns
True if a cycle is found.
Postcondition
All traversed nodes are marked with non-clear marks.
Definition at line 131 of file cycle.h.
References scram::mef::cycle::DetectCycle(), and scram::mef::cycle::GetConnector().
Referenced by scram::mef::cycle::CheckCycle(), scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::DetectCycle().
template<class T > std::string scram::mef::cycle::PrintCycle (const std::vector< T * > & cycle)
Prints the detected cycle from the output produced by cycle detection functions.
Template Parameters
T The node type with GetUniqueName(T*) defined.
Parameters
[in] cycle Cycle containing nodes in reverse order.
Returns
String representation of the cycle.
Definition at line 195 of file cycle.h.
References scram::mef::cycle::GetUniqueName(), and scram::mef::cycle::PrintCycle().
Referenced by scram::mef::cycle::CheckCycle(), and scram::mef::cycle::PrintCycle().
template<class T , class SinglePassRange > void scram::mef::cycle::CheckCycle (const SinglePassRange & container, const char * type)
Checks for cycles in a model constructs.
Template Parameters
T The type of the node.
SinglePassRange The range type with nodes.
Parameters
[in] container The range with nodes to be tested.
[in] type The type of nodes for error messages.
Exceptions
CycleError A cycle is detected in the graph of nodes.
Definition at line 215 of file cycle.h.
References scram::mef::cycle::CheckCycle(), scram::mef::cycle::DetectCycle(), scram::mef::cycle::GetUniqueName(), scram::mef::cycle::PrintCycle(), and SCRAM_THROW.
Referenced by scram::mef::cycle::CheckCycle().