element.h File Reference
element.h File Reference
Base/mixin classes, structs, and properties common to all MEF classes/constructs.
#include <cstdint>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/multi_index/hashed_index.hpp>
#include <boost/multi_index/mem_fun.hpp>
#include <boost/multi_index_container.hpp>
#include <boost/noncopyable.hpp>
#include "error.h"
#include "ext/linear_set.h"
#include "ext/multi_index.h"
Classes
class scram::mef::ContainerElement
Elements in MEF containers.
class scram::mef::Attribute
MEF Element Attributes.
class scram::mef::Element
The MEF Element with attributes and a label.
class scram::mef::Role
Mixin class that manages private or public roles for elements as needed.
class scram::mef::Id
Mixin class for assigning unique identifiers to elements.
class scram::mef::TableRange< T >
Wraps the element container tables into ranges of plain references to hide the memory smart or raw pointers.
class scram::mef::TableRange< T >::iterator
The proxy forward iterator to extract values instead of pointers.
class scram::mef::Container< Self, T, Ownership, ById >
The MEF Container of unique elements.
struct scram::mef::detail::container_of_impl< E, T, Ts >
Implementation of container_of to deal w/ empty type list.
struct scram::mef::detail::container_of_impl< E, void >
Specialization for an empty type list.
struct scram::mef::detail::container_of< T, Ts >
Finds the container type for the given element type.
class scram::mef::Composite< Ts >
The composition of multiple mef::Containers.
class scram::mef::NodeMark
Mixin class for providing marks for graph nodes.
class scram::mef::Usage
Mixin class for providing usage marks for elements.
Typedefs
template<typename T >
using scram::mef::ElementTable = boost::multi_index_container< T, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< boost::multi_index::const_mem_fun< Element, std::string_view,&Element::name_view >, std::hash< std::string_view >>>>
Table of elements with unique names.
template<typename T >
using scram::mef::IdTable = boost::multi_index_container< T, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< boost::multi_index::const_mem_fun< Id, std::string_view,&Id::id_view >, std::hash< std::string_view >>>>
Table of elements with unique ids.
template<class T , class... Ts>
using scram::mef::MultiContainer = Composite< Container< T, Ts >... >
Convenience alias for a homogeneous composite of containers.
Enumerations
enum scram::mef::RoleSpecifier : std::uint8_t { kPublic, kPrivate }
Role, access attributes for elements.
Functions
template<typename T >
std::string scram::mef::GetFullPath (const T *element)
Computes the full path of an element.
Detailed Description
Base/mixin classes, structs, and properties common to all MEF classes/constructs.
Definition in file element.h.
Typedef Documentation
template<typename T > using scram::mef::ElementTable = typedef boost::multi_index_container< T, boost::multi_index::indexed_by<boost::multi_index::hashed_unique< boost::multi_index::const_mem_fun<Element, std::string_view, &Element::name_view>, std::hash<std::string_view>>>>
Table of elements with unique names.
Template Parameters
T Value or (smart/raw) pointer type deriving from Element class.
Precondition
The element names are not modified while it is in the container.
Definition at line 256 of file element.h.
template<typename T > using scram::mef::IdTable = typedef boost::multi_index_container< T, boost::multi_index::indexed_by<boost::multi_index::hashed_unique< boost::multi_index::const_mem_fun<Id, std::string_view, &Id::id_view>, std::hash<std::string_view>>>>
Table of elements with unique ids.
Template Parameters
T Value or (smart/raw) pointer type deriving from Id class.
Precondition
The element IDs are not modified while it is in the container.
Definition at line 367 of file element.h.
template<class T , class... Ts> using scram::mef::MultiContainer = typedef Composite<Container<T, Ts>...>
Convenience alias for a homogeneous composite of containers.
Template Parameters
T The MEF container type for the CRTP.
Ts The MEF element types for the containers.
Definition at line 640 of file element.h.
Function Documentation
template<typename T > std::string scram::mef::GetFullPath (const T * element)
Computes the full path of an element.
Template Parameters
T Element type deriving from Role.
Parameters
[in] element A valid element with a name and base path.
Returns
A string representation of the full path.
Definition at line 301 of file element.h.
References scram::mef::GetFullPath().
Referenced by scram::mef::GetFullPath(), scram::mef::Id::Id(), and scram::mef::Id::id().