env.cc File Reference
env.cc File Reference
The environment variables discovered at run-time.
#include "env.h"
#include <boost/dll/runtime_symbol_info.hpp>
Functions
const std::string & scram::env::project_schema ()
const std::string & scram::env::input_schema ()
const std::string & scram::env::report_schema ()
const std::string & scram::env::install_dir ()
Detailed Description
The environment variables discovered at run-time.
Definition in file env.cc.
Function Documentation
const std::string & scram::env::project_schema ()
Returns
The location of the RELAX NG schema for project files.
Definition at line 27 of file env.cc.
References scram::env::install_dir(), and scram::env::project_schema().
Referenced by scram::env::project_schema().
const std::string & scram::env::input_schema ()
Returns
The location of the RELAX NG schema for input files.
Definition at line 33 of file env.cc.
References scram::env::input_schema(), and scram::env::install_dir().
Referenced by scram::env::input_schema().
const std::string & scram::env::report_schema ()
Returns
The location of the RELAX NG schema for output report files.
Definition at line 39 of file env.cc.
References scram::env::install_dir(), and scram::env::report_schema().
Referenced by scram::env::report_schema().
const std::string & scram::env::install_dir ()
Returns
The path to the installation directory.
Definition at line 45 of file env.cc.
References scram::env::install_dir().
Referenced by scram::env::input_schema(), scram::env::install_dir(), scram::env::project_schema(), and scram::env::report_schema().