fault_tree_analysis.h File Reference
fault_tree_analysis.h File Reference
Fault Tree Analysis.
#include <cstdlib>
#include <memory>
#include <unordered_set>
#include <vector>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/iterator/transform_iterator.hpp>
#include "analysis.h"
#include "pdag.h"
#include "preprocessor.h"
#include "settings.h"
#include "zbdd.h"
Classes
struct scram::core::Literal
Event or its complement that may appear in products.
class scram::core::Product
Collection of unique literals.
class scram::core::ProductContainer
A container of analysis result products with Literals.
class scram::core::FaultTreeAnalysis
Fault tree analysis functionality.
class scram::core::FaultTreeAnalyzer< Algorithm >
Fault tree analysis facility with specific algorithms.
Functions
void scram::core::Print (const ProductContainer &products)
Prints a collection of products to the standard error.
Detailed Description
Fault Tree Analysis.
Definition in file fault_tree_analysis.h.
Function Documentation
void scram::core::Print (const ProductContainer & products)
Prints a collection of products to the standard error.
This is a helper function for easier debugging and visual comparison of analysis results. Summary of the number of products and its size distribution is printed first. Then, all products are grouped by size and sorted. The literals of a product are sorted by their names.
Parameters
[in] products Valid, unique collection of analysis results.
Definition at line 34 of file fault_tree_analysis.cc.
References scram::core::ProductContainer::begin(), scram::core::ProductContainer::distribution(), scram::core::ProductContainer::empty(), scram::core::Print(), and scram::core::ProductContainer::size().
Referenced by scram::core::FaultTreeAnalysis::Analyze(), scram::core::Pdag::basic_events(), scram::core::ProductContainer::distribution(), and scram::core::Print().