fault_tree_analysis.cc File Reference
fault_tree_analysis.cc File Reference
Implementation of fault tree analysis.
#include "fault_tree_analysis.h"
#include <iostream>
#include <utility>
#include <boost/container/flat_set.hpp>
#include <boost/range/algorithm.hpp>
#include "event.h"
#include "logger.h"
Functions
void scram::core::Print (const ProductContainer &products)
Prints a collection of products to the standard error.
Detailed Description
Implementation of fault tree analysis.
Definition in file fault_tree_analysis.cc.
Function Documentation
void scram::core::Print (const ProductContainer & products)
Prints a collection of products to the standard error.
This is a helper function for easier debugging and visual comparison of analysis results. Summary of the number of products and its size distribution is printed first. Then, all products are grouped by size and sorted. The literals of a product are sorted by their names.
Parameters
[in] products Valid, unique collection of analysis results.
Definition at line 34 of file fault_tree_analysis.cc.
References scram::core::ProductContainer::begin(), scram::core::ProductContainer::distribution(), scram::core::ProductContainer::empty(), scram::core::Print(), and scram::core::ProductContainer::size().
Referenced by scram::core::FaultTreeAnalysis::Analyze(), scram::core::Pdag::basic_events(), scram::core::ProductContainer::distribution(), and scram::core::Print().