find_iterator.h File Reference
find_iterator.h File Reference
Convenience iterator adaptor to wrap find calls and results.
#include <utility>
Classes
class ext::find_iterator< Iterator >
Iterator adaptor for indication of container find call results.
Functions
template<class T , typename Arg >
auto ext::find (T &&container, Arg &&arg)
Wraps container::find() calls for convenient and efficient lookup with find_iterator adaptor.
Detailed Description
Convenience iterator adaptor to wrap find calls and results.
Definition in file find_iterator.h.
Function Documentation
template<class T , typename Arg > auto ext::find (T && container, Arg && arg)
Wraps container::find() calls for convenient and efficient lookup with find_iterator adaptor.
Template Parameters
T Container type supporting find() and end() calls.
Arg The argument type to the find() call.
Parameters
[in] container The container to operate upon.
[in] arg The argument to the find() function.
Returns
find_iterator wrapping the resultant iterator.
Definition at line 59 of file find_iterator.h.
References ext::find().
Referenced by ext::find(), and ext::linear_set< Attribute, AttributeKey >::rend().