pdag.h File Reference
pdag.h File Reference
Classes and facilities to represent fault trees as PDAGs with event and gate indices instead of ID names.
#include <cstdint>
#include <cstdlib>
#include <algorithm>
#include <iosfwd>
#include <memory>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#include <boost/container/flat_set.hpp>
#include <boost/noncopyable.hpp>
#include <boost/range/adaptor/transformed.hpp>
#include "ext/find_iterator.h"
#include "ext/index_map.h"
#include "ext/linear_map.h"
Classes
class scram::core::NodeParentManager
A manager of information about parents.
class scram::core::Node
An abstract base class that represents a node in a PDAG.
class scram::core::Constant
Representation of a node that is a Boolean constant TRUE.
class scram::core::Variable
Boolean variables in a Boolean formula or graph.
class scram::core::Gate
An indexed gate for use in a PDAG.
class scram::core::Pdag
PDAG is a propositional directed acyclic graph.
class scram::core::Pdag::NodeIndexGenerator
Generator of unique indices for graph nodes.
class scram::core::Pdag::NullGateRegistrar
Registers pass-through or Null logic gates belonging to the graph.
struct scram::core::Pdag::Substitution
Non-declarative substitutions.
Typedefs
using scram::core::GatePtr = std::shared_ptr< Gate >
Shared gates in the graph.
using scram::core::GateWeakPtr = std::weak_ptr< Gate >
An acyclic ptr to parent gates.
using scram::core::NodePtr = std::shared_ptr< Node >
Shared base nodes in the graph.
using scram::core::ConstantPtr = std::shared_ptr< Constant >
Shared Boolean constants.
using scram::core::VariablePtr = std::shared_ptr< Variable >
Shared Boolean variables.
Enumerations
enum scram::core::Connective : std::uint8_t {
scram::core::kAnd = 0, scram::core::kOr, scram::core::kAtleast, scram::core::kXor,
scram::core::kNot, scram::core::kNand, scram::core::kNor, scram::core::kNull
}
Boolean connectives of gates for representation, preprocessing, and analysis purposes.
Functions
std::ostream & scram::core::operator<< (std::ostream &os, Pdag *graph)
Prints the PDAG as a fault tree in the Aralia format.
template<bool Mark = true, typename T >
void scram::core::TraverseGates (const GatePtr &gate, T &&visit) noexcept
Traverses and visits gates and nodes in the graph.
template<typename T >
void scram::core::TraverseNodes (const GatePtr &gate, T &&visit) noexcept
Traverses and visits gates and nodes in the graph.
std::ostream & scram::core::operator<< (std::ostream &os, const Constant &constant)
Prints PDAG nodes in the Aralia format.
std::ostream & scram::core::operator<< (std::ostream &os, const Variable &variable)
Prints PDAG nodes in the Aralia format.
std::ostream & scram::core::operator<< (std::ostream &os, const GatePtr &gate)
Prints PDAG nodes in the Aralia format.
Variables
const int scram::core::kNumConnectives = 8
The number of connectives in the enum.
Detailed Description
Classes and facilities to represent fault trees as PDAGs with event and gate indices instead of ID names.
These facilities are designed to work with FaultTreeAnalysis and Preprocessor classes.
The terminologies of the graphs and Boolean logic are mixed to represent the PDAG; however, if there is a conflict, the Boolean terminology is preferred. For example, instead of "children", "arguments" are preferred.
Definition in file pdag.h.
Enumeration Type Documentation
enum scram::core::Connective : std::uint8_t
Boolean connectives of gates for representation, preprocessing, and analysis purposes.
The connective defines a type and logic of a gate.
Warning
If a new connective is added, all the preprocessing and PDAG algorithms must be reviewed and updated. The algorithms may assume for performance and simplicity reasons that these are the only kinds of connectives possible.
Enumerator
kAnd
AND gate.
kOr
OR gate.
kAtleast
Combination, K/N, or Vote gate representation.
kXor
Exclusive OR gate with two inputs.
kNot
Boolean negation.
kNand
NAND gate.
kNor
NOR gate.
kNull
Special pass-through or NULL gate. This is not NULL set.
Definition at line 261 of file pdag.h.
Function Documentation
template<bool Mark = true, typename T > void scram::core::TraverseGates (const GatePtr & gate, T && visit) noexcept
Traverses and visits gates and nodes in the graph.
Template Parameters
Mark The "visited" gate mark.
T The visitor type.
Parameters
[in,out] gate The starting gate.
[in] visit The visitor for graph nodes.
Definition at line 1152 of file pdag.h.
References scram::core::TraverseGates().
Referenced by scram::core::Pdag::Clear(), scram::core::Pdag::RemoveNullGates(), and scram::core::TraverseGates().
template<typename T > void scram::core::TraverseNodes (const GatePtr & gate, T && visit) noexcept
Traverses and visits gates and nodes in the graph.
Template Parameters
Mark The "visited" gate mark.
T The visitor type.
Parameters
[in,out] gate The starting gate.
[in] visit The visitor for graph nodes.
Definition at line 1162 of file pdag.h.
References scram::core::TraverseNodes().
Referenced by scram::core::Pdag::Clear(), and scram::core::TraverseNodes().
std::ostream & scram::core::operator<< (std::ostream & os, Pdag * graph)
Prints the PDAG as a fault tree in the Aralia format.
This function is mostly for debugging purposes.
Parameters
[in,out] os Output stream.
[in] graph The PDAG to be printed.
Returns
The provided output stream in its original state.
Warning
Visits of nodes must be clean. Visit information may get changed.
Definition at line 1047 of file pdag.cc.
References scram::core::Pdag::constant(), scram::core::operator<<(), and scram::core::Pdag::root().
Variable Documentation
const int scram::core::kNumConnectives = 8
The number of connectives in the enum.
This number is useful for optimizations and algorithms.
Definition at line 274 of file pdag.h.