pdag.cc File Reference
pdag.cc File Reference
Implementation of a Propositional Directed Acyclic Graph with indexed nodes, variables, and gates.
#include "pdag.h"
#include <iostream>
#include <string>
#include <unordered_set>
#include <boost/math/special_functions/sign.hpp>
#include <boost/range/algorithm.hpp>
#include "event.h"
#include "ext/algorithm.h"
#include "logger.h"
#include "model.h"
#include "substitution.h"
Macros
#define CONNECTIVE_EQ(op) static_cast<int>(op) == static_cast<int>(mef::op)
Compares connective enums from mef::Connective and core::Connective.
Functions
std::ostream & scram::core::operator<< (std::ostream &os, Pdag *graph)
Prints the PDAG as a fault tree in the Aralia format.
std::ostream & scram::core::operator<< (std::ostream &os, const Constant &constant)
Prints PDAG nodes in the Aralia format.
std::ostream & scram::core::operator<< (std::ostream &os, const Variable &variable)
Prints PDAG nodes in the Aralia format.
std::ostream & scram::core::operator<< (std::ostream &os, const GatePtr &gate)
Prints PDAG nodes in the Aralia format.
Detailed Description
Implementation of a Propositional Directed Acyclic Graph with indexed nodes, variables, and gates.
The implementation caters other algorithms like preprocessing. The main goal is to make manipulations and transformations of the graph easier to achieve for graph algorithms.
Definition in file pdag.cc.
Function Documentation
std::ostream & scram::core::operator<< (std::ostream & os, Pdag * graph)
Prints the PDAG as a fault tree in the Aralia format.
This function is mostly for debugging purposes.
Parameters
[in,out] os Output stream.
[in] graph The PDAG to be printed.
Returns
The provided output stream in its original state.
Warning
Visits of nodes must be clean. Visit information may get changed.
Definition at line 1047 of file pdag.cc.
References scram::core::Pdag::constant(), scram::core::operator<<(), and scram::core::Pdag::root().