preprocessor.h File Reference
preprocessor.h File Reference
A collection of PDAG transformation/preprocessing algorithms that simplify fault trees for analysis.
#include <memory>
#include <set>
#include <unordered_map>
#include <utility>
#include <vector>
#include <boost/noncopyable.hpp>
#include <boost/unordered_map.hpp>
#include "pdag.h"
Classes
class scram::core::Preprocessor
The class provides main preprocessing operations over a PDAG to simplify the fault tree and to help analysis run more efficiently.
struct scram::core::Preprocessor::MergeTable
Helper struct for algorithms that must make an optimal decision how to merge or factor out common arguments of gates into new gates.
class scram::core::Preprocessor::DecompositionProcessor
Functor for processing of decomposition setups with common nodes.
class scram::core::CustomPreprocessor< Algorithm >
Undefined template class for specialization of Preprocessor for needs of specific analysis algorithms.
class scram::core::CustomPreprocessor< Bdd >
Specialization of preprocessing for BDD based analyses.
class scram::core::CustomPreprocessor< Zbdd >
Specialization of preprocessing for ZBDD based analyses.
class scram::core::CustomPreprocessor< Mocus >
Specialization of preprocessing for MOCUS based analyses.
Functions
template<typename T , typename... Ts>
void scram::core::pdag::Transform (Pdag *graph, T &&unary_op, Ts &&...unary_ops) noexcept
Applies graph transformations consecutively.
template<class T >
std::vector< T * > scram::core::pdag::OrderArguments (Gate *gate) noexcept
Determines the order of traversal for gate arguments.
void scram::core::pdag::TopologicalOrder (Pdag *graph) noexcept
Assigns topological ordering to nodes of the PDAG.
void scram::core::pdag::MarkCoherence (Pdag *graph) noexcept
Marks coherence of the whole graph.
Detailed Description
A collection of PDAG transformation/preprocessing algorithms that simplify fault trees for analysis.
Definition in file preprocessor.h.
Function Documentation
template<typename T , typename... Ts> void scram::core::pdag::Transform (Pdag * graph, T && unary_op, Ts &&... unary_ops) noexcept
Applies graph transformations consecutively.
Parameters
[in,out] graph The graph to be transformed.
[in] unary_op The first operation to be applied.
[in] unary_ops The rest of transformations to apply.
Definition at line 45 of file preprocessor.h.
References scram::core::Pdag::IsTrivial(), scram::core::pdag::MarkCoherence(), scram::core::pdag::OrderArguments(), scram::core::pdag::TopologicalOrder(), and scram::core::pdag::Transform().
Referenced by scram::core::pdag::Transform().
template<class T > std::vector< T * > scram::core::pdag::OrderArguments (Gate * gate) noexcept
Determines the order of traversal for gate arguments.
This function does not assign the order of nodes.
Template Parameters
T Type of the arguments.
Parameters
[in] gate The host gate parent.
Returns
An ordered, stable list of arguments.
Definition at line 97 of file preprocessor.cc.
References scram::core::pdag::OrderArguments().
Referenced by scram::core::pdag::OrderArguments(), and scram::core::pdag::Transform().
void scram::core::pdag::TopologicalOrder (Pdag * graph) noexcept
Assigns topological ordering to nodes of the PDAG.
The ordering is assigned to the node order marks. The nodes are sorted in descending optimization value. The highest order value belongs to the root.
Parameters
[in,out] graph The graph to be processed.
Postcondition
The root and descendant node order marks contain the ordering.
Definition at line 108 of file preprocessor.cc.
References scram::core::Gate::constant(), scram::core::Node::order(), and scram::core::pdag::TopologicalOrder().
Referenced by scram::core::pdag::TopologicalOrder(), and scram::core::pdag::Transform().
void scram::core::pdag::MarkCoherence (Pdag * graph) noexcept
Marks coherence of the whole graph.
Parameters
[in,out] graph The graph to be processed.
Postcondition
Gate traversal marks are dirty.
Definition at line 129 of file preprocessor.cc.
References scram::core::Pdag::kGateMark, and scram::core::pdag::MarkCoherence().
Referenced by scram::core::pdag::MarkCoherence(), and scram::core::pdag::Transform().