preprocessor.cc File Reference
preprocessor.cc File Reference
Implementation of preprocessing algorithms.
#include "preprocessor.h"
#include <cstdlib>
#include <algorithm>
#include <array>
#include <list>
#include <queue>
#include <unordered_set>
#include <boost/functional/hash.hpp>
#include <boost/math/special_functions/sign.hpp>
#include <boost/range/algorithm.hpp>
#include <boost/range/algorithm_ext.hpp>
#include "ext/algorithm.h"
#include "ext/find_iterator.h"
#include "logger.h"
Classes
class scram::core::Preprocessor::GateSet
Container of unique gates.
Macros
#define SANITY_ASSERT
A collection of sanity checks between preprocessing phases.
Functions
template<class T >
std::vector< T * > scram::core::pdag::OrderArguments (Gate *gate) noexcept
Determines the order of traversal for gate arguments.
void scram::core::pdag::TopologicalOrder (Pdag *graph) noexcept
Assigns topological ordering to nodes of the PDAG.
void scram::core::pdag::MarkCoherence (Pdag *graph) noexcept
Marks coherence of the whole graph.
Detailed Description
Implementation of preprocessing algorithms.
The main goal of preprocessing algorithms is to make PDAGs simpler, modular, easier for analysis.
If a preprocessing algorithm has its limitations, side-effects, and assumptions, the documentation in the header file must contain all the relevant information within its description, preconditions, postconditions, notes, or warnings. The default assumption for all algorithms is that the PDAG is valid and well-formed.
Some suggested contracts/notes for preprocessing algorithms:
Works with coherent graphs only
Works with positive gates or nodes only
Depends on node visit information, gate marks, or other node flags.
May introduce NULL or UNITY state gates or constants
May introduce NULL/NOT type gates
Operates on certain gate types only
Works with normalized gates or structure only
Cannot accept a graph with gates of certain types
May destroy modules
Can accept graphs with constants or constant gates
Depends on other preprocessing functions or algorithms
Swaps the root gate of the graph with another (arg) gate
Removes gates or other kind of nodes
May introduce new gate clones or subgraphs, making the graph more complex.
Works on particular cases or setups only
Has trade-offs
Runs better/More effective before/after some preprocessing step(s)
Coupled with another preprocessing algorithms
Idempotent (consecutive, repeated application doesn't yield any change)
One-time operation (any repetition is pointless or dangerous)
Assuming that the PDAG is provided in the state as described in the contract, the algorithms should never throw an exception.
The algorithms must guarantee that, given a valid and well-formed PDAG, the resulting PDAG will at least be valid, well-formed, and semantically equivalent (isomorphic) to the input PDAG. Moreover, the algorithms must be deterministic and produce stable results.
If the contract is violated, the result or behavior of the algorithm can be undefined. There is no requirement to check for the contract violations and to exit gracefully.
Definition in file preprocessor.cc.
Macro Definition Documentation
#define SANITY_ASSERT
Value:
assert(graph_->root() && "Corrupted pointer to the root gate.");         \
  assert(graph_->root()->parents().empty() && "Root can't have parents."); \
  assert(!(graph_->coherent() && graph_->complement()));                   \
  assert(!graph_->HasConstants() && "Const gate cleanup is broken!");      \
  assert(!graph_->HasNullGates() && "Null gate cleanup is broken!");       \
  assert(TestGateStructure()(*graph_->root()));                            \
  assert(TestGateMarks()(*graph_->root(), graph_->root()->mark()))
A collection of sanity checks between preprocessing phases.
Definition at line 311 of file preprocessor.cc.
Referenced by scram::core::Preprocessor::RunPhaseFive(), scram::core::Preprocessor::RunPhaseFour(), scram::core::Preprocessor::RunPhaseOne(), scram::core::Preprocessor::RunPhaseThree(), and scram::core::Preprocessor::RunPhaseTwo().
Function Documentation
template<class T > std::vector< T * > scram::core::pdag::OrderArguments (Gate * gate) noexcept
Determines the order of traversal for gate arguments.
This function does not assign the order of nodes.
Template Parameters
T Type of the arguments.
Parameters
[in] gate The host gate parent.
Returns
An ordered, stable list of arguments.
Definition at line 97 of file preprocessor.cc.
References scram::core::pdag::OrderArguments().
Referenced by scram::core::pdag::OrderArguments(), and scram::core::pdag::Transform().
void scram::core::pdag::TopologicalOrder (Pdag * graph) noexcept
Assigns topological ordering to nodes of the PDAG.
The ordering is assigned to the node order marks. The nodes are sorted in descending optimization value. The highest order value belongs to the root.
Parameters
[in,out] graph The graph to be processed.
Postcondition
The root and descendant node order marks contain the ordering.
Definition at line 108 of file preprocessor.cc.
References scram::core::Gate::constant(), scram::core::Node::order(), and scram::core::pdag::TopologicalOrder().
Referenced by scram::core::pdag::TopologicalOrder(), and scram::core::pdag::Transform().
void scram::core::pdag::MarkCoherence (Pdag * graph) noexcept
Marks coherence of the whole graph.
Parameters
[in,out] graph The graph to be processed.
Postcondition
Gate traversal marks are dirty.
Definition at line 129 of file preprocessor.cc.
References scram::core::Pdag::kGateMark, and scram::core::pdag::MarkCoherence().
Referenced by scram::core::pdag::MarkCoherence(), and scram::core::pdag::Transform().