serialization.h File Reference
serialization.h File Reference
The MEF Model serialization facilities.
#include <cstdio>
#include <string>
#include "model.h"
Functions
void scram::mef::Serialize (const Model &model, std::FILE *out)
Serializes the model and its data into stream as XML.
void scram::mef::Serialize (const Model &model, const std::string &file)
Convenience function for serialization into a file.
Detailed Description
The MEF Model serialization facilities.
Note
This facility currently caters only models representable in the GUI.
Todo:
Implement serialization for all MEF constructs.
Definition in file serialization.h.
Function Documentation
void scram::mef::Serialize (const Model & model, std::FILE * out)
Serializes the model and its data into stream as XML.
Parameters
[in] model Fully initialized and valid model.
[in,out] out The stream for XML data.
Exceptions
IOError The write operation has failed.
Todo:
Implement serialization for the following unsupported constructs.
Definition at line 182 of file serialization.cc.
References scram::xml::StreamElement::AddChild(), scram::mef::Model::basic_events(), scram::mef::Model::ccf_groups(), scram::mef::Model::event_trees(), scram::mef::Model::fault_trees(), scram::mef::Model::HasDefaultName(), scram::mef::Model::house_events(), scram::mef::Model::initiating_events(), scram::mef::Element::name(), scram::mef::Model::parameters(), scram::xml::Stream::root(), scram::mef::Model::rules(), scram::mef::Model::sequences(), scram::mef::Serialize(), and scram::xml::StreamElement::SetAttribute().
void scram::mef::Serialize (const Model & model, const std::string & file)
Convenience function for serialization into a file.
Parameters
[in] model Fully initialized and valid model.
[out] file The output destination.
Exceptions
IOError The output file is not accessible, or the write operation has failed.
Definition at line 39 of file serialization.cc.
References scram::xml::StreamElement::AddChild(), scram::xml::StreamElement::AddText(), scram::mef::Expression::args(), scram::mef::Formula::args(), scram::mef::Element::attributes(), scram::mef::Formula::Arg::complement, scram::mef::Component::components(), scram::mef::Formula::connective(), ext::linear_set< Value, KeyFromValue, Sequence >::empty(), scram::mef::Formula::Arg::event, scram::mef::BasicEvent::expression(), scram::mef::Gate::formula(), scram::mef::Component::gates(), scram::mef::BasicEvent::HasExpression(), scram::mef::kAtleast, scram::mef::HouseEvent::kFalse, scram::mef::kNand, scram::mef::kNor, scram::mef::kNot, scram::mef::kNull, scram::mef::HouseEvent::kTrue, scram::mef::kXor, scram::mef::Element::label(), scram::mef::Formula::min_number(), scram::mef::Element::name(), scram::mef::Role::role(), SCRAM_THROW, scram::mef::Serialize(), scram::xml::StreamElement::SetAttribute(), and scram::mef::HouseEvent::state().
Referenced by scram::mef::Serialize().