scram::mef::Initializer::Extractor< T,-1 > Struct Template Reference
scram::mef::Initializer::Extractor< T,-1 > Struct Template Reference
Specialization of Extractor to extract all expressions into arg vector.
Public Member Functions
std::unique_ptr< T > operator() (const xml::Element::Range &args, const std::string &base_path, Initializer *init)
Constructs an expression with a variable number of arguments.
Detailed Description
template<class T>
struct scram::mef::Initializer::Extractor< T,-1 >
Specialization of Extractor to extract all expressions into arg vector.
Definition at line 979 of file initializer.cc.
Member Function Documentation
template<class T > std::unique_ptr<T> scram::mef::Initializer::Extractor< T,-1 >::operator() (const xml::Element::Range & args, const std::string & base_path, Initializer * init) inline
Constructs an expression with a variable number of arguments.
Parameters
[in] args XML elements containing the arguments.
[in] base_path Series of ancestor containers in the path with dots.
[in,out] init The host Initializer.
Returns
The constructed expression.
Definition at line 987 of file initializer.cc.
References scram::mef::CcfGroup::AddFactor(), scram::mef::CcfGroup::AddMember(), scram::mef::ExternFunction< void >::apply(), scram::xml::Element::attribute(), scram::mef::Role::base_path(), scram::xml::Element::Range::begin(), scram::xml::Element::child(), scram::xml::Element::children(), scram::mef::ConstantExpression::kOne, scram::mef::ConstantExpression::kPi, scram::mef::kUnitsToString, scram::mef::ConstantExpression::kZero, scram::xml::Element::line(), scram::xml::Element::name(), scram::mef::Role::role(), SCRAM_THROW, scram::xml::Element::Range::size(), and scram::mef::Usage::usage().
The documentation for this struct was generated from the following file:
initializer.cc