xml.h File Reference
xml.h File Reference
XML helper facilities to work with libxml2.
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <boost/exception/errinfo_at_line.hpp>
#include <boost/exception/errinfo_errno.hpp>
#include <boost/exception/errinfo_file_name.hpp>
#include <boost/exception/errinfo_file_open_mode.hpp>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/range/adaptor/filtered.hpp>
#include <libxml/parser.h>
#include <libxml/relaxng.h>
#include <libxml/tree.h>
#include "error.h"
Classes
class scram::xml::Element
XML Element adaptor.
class scram::xml::Element::Range
The range for elements.
class scram::xml::Element::Range::iterator
Iterator over range elements.
class scram::xml::Document
XML DOM tree document.
class scram::xml::Validator
RelaxNG validator.
Functions
template<typename T >
std::enable_if_t< std::is_arithmetic_v< T >, T > scram::xml::detail::to (const std::string_view &value)
Gets a number from an XML value.
const char * scram::xml::detail::from_utf8 (const xmlChar *xml_string) noexcept
Reinterprets the XML library UTF-8 string into C string.
const xmlChar * scram::xml::detail::to_utf8 (const char *c_string) noexcept
Reinterprets C string as XML library UTF-8 string.
std::string_view scram::xml::detail::trim (const std::string_view &text) noexcept
Removes leading and trailing space characters from XML value string.
template<typename T >
T scram::xml::detail::GetError (xmlErrorPtr xml_error=nullptr)
Gets the last XML error converted from the library error codes.
Variables
const int scram::xml::kParserOptions
The parser options passed to the library parser.
Detailed Description
XML helper facilities to work with libxml2.
Adaptors and helper functions provide read-only facilities.
Note
All strings and characters are UTF-8 unless otherwise documented.
The facilities are designed specifically for SCRAM use cases. The XML assumed to be well formed and simple.
libxml2 older versions are not const correct in API.
Warning
Complex XML features are not handled or expected, for example, DTD, namespaces, entries.
Definition in file xml.h.
Function Documentation
template<typename T > std::enable_if_t<std::is_arithmetic_v<T>, T> scram::xml::detail::to (const std::string_view & value)
Gets a number from an XML value.
Template Parameters
T Numeric type.
Parameters
[in] value The non-empty value string.
Returns
The interpreted value.
Exceptions
ValidityError The interpretation is unsuccessful.
Definition at line 73 of file xml.h.
References SCRAM_THROW, and scram::xml::detail::to().
Referenced by scram::xml::detail::to().
const char* scram::xml::detail::from_utf8 (const xmlChar * xml_string) inline noexcept
Reinterprets the XML library UTF-8 string into C string.
Parameters
[in] xml_string The string provided by the XML library.
Returns
The same string adapted for use as C string.
Definition at line 112 of file xml.h.
References scram::xml::detail::from_utf8().
Referenced by scram::xml::detail::from_utf8().
const xmlChar* scram::xml::detail::to_utf8 (const char * c_string) inline noexcept
Reinterprets C string as XML library UTF-8 string.
Parameters
[in] c_string The C byte-array encoding the XML string.
Returns
The same string adapted for use in XML library functions.
Precondition
The C string has UTF-8 encoding.
Definition at line 124 of file xml.h.
References scram::xml::detail::to_utf8().
Referenced by scram::xml::detail::to_utf8().
std::string_view scram::xml::detail::trim (const std::string_view & text) inline noexcept
Removes leading and trailing space characters from XML value string.
Parameters
[in] text The text in XML attribute or text nodes.
Returns
View to the trimmed substring.
Precondition
The string is normalized by the XML parser.
Definition at line 136 of file xml.h.
References scram::xml::detail::trim().
Referenced by scram::xml::detail::trim().
template<typename T > T scram::xml::detail::GetError (xmlErrorPtr xml_error = nullptr)
Gets the last XML error converted from the library error codes.
Template Parameters
T The SCRAM error type to convert XML error into.
Parameters
[in] xml_error The error to translate. nullptr to retrieve the latest error in the library.
Returns
The exception object to be thrown.
Definition at line 156 of file xml.h.
References scram::xml::detail::GetError().
Referenced by scram::xml::detail::GetError().
Variable Documentation
const int scram::xml::kParserOptions
Initial value:
= XML_PARSE_XINCLUDE | XML_PARSE_NOBASEFIX |
                           XML_PARSE_NONET | XML_PARSE_NOXINCNODE |
                           XML_PARSE_COMPACT | XML_PARSE_HUGE
The parser options passed to the library parser.
Definition at line 394 of file xml.h.
Referenced by scram::xml::Document::Document().